function CBullet1(a,g,b){var c=!1,f,d,h,l,e,k,n,m;this._init=function(p,a,b){m=p;h=(f=b)?-1:1;e=[];p=s_oSpriteLibrary.getSprite(a);a=createBitmap(p);!1===b&&(a.scaleY=-1);a.x=-100;a.y=-100;a.regX=p.width/2;a.regY=p.height/2;m.addChild(a);e.push(a);d=[];n=[];for(b=0;b<e.length;b++)d.push({x:-100,y:-100}),n[b]=!0,e[b].visible=!1;l=Math.floor(p.width/2)};this.unload=function(){for(var p=0;p<e.length;p++)m.removeChild(e[p])};this.reset=function(p){n[p]=!1;e[p].x=d[p].x;e[p].y=d[p].y;!0===this._checkIfAllBulletInactive()&&
(c=!1,!1===f&&s_oGame.removeBullet(this))};this._checkIfAllBulletInactive=function(){for(var p=!0,a=0;a<n.length;a++)if(!0===n[a]){p=!1;break}return p};this.show=function(p,a,b){playSound("bullet1",1,0);k=[];for(var d=0;d<e.length;d++){e[d].x=p;e[d].y=a;var f=parseFloat(Math.cos(degreesToRadians(e[d].rotation*e[d].scaleY-90))).toFixed(2),g=Math.sin(degreesToRadians(e[d].rotation*e[d].scaleY+90));k[d]={x:f*(3+b),y:g*(3+b)*h};e[d].visible=!0}c=!0};this.getPos=function(){return e};this.getSprite=function(a){return e[a]};
this.getSprites=function(){return e};this.isUpdating=function(){return c};this.getRadius=function(){return l};this.update=function(){if(c)for(var a=0;a<e.length;a++)e[a].x+=k[a].x,e[a].y+=k[a].y,(0>e[a].x||e[a].x>CANVAS_WIDTH||0>e[a].y||e[a].y>CANVAS_HEIGHT)&&this.reset(a)};this._init(a,g,b)}
function CBullet2(a,g,b){var c=!1,f,d,h,l,e,k,n,m;this._init=function(a,b,c){m=a;h=(f=c)?-1:1;e=[];a=s_oSpriteLibrary.getSprite(b);b=createBitmap(a);b.regX=a.width/2;b.regY=a.height/2;b.x=-100;b.y=-100;!1===c?(b.scaleY=-1,b.rotation=45):b.rotation=-45;m.addChild(b);e.push(b);b=createBitmap(a);!1===c&&(b.scaleY=-1);b.x=-100;b.y=-100;b.regX=a.width/2;b.regY=a.height/2;m.addChild(b);e.push(b);b=createBitmap(a);b.x=-100;b.y=-100;b.regX=a.width/2;b.regY=a.height/2;!1===c?(b.scaleY=-1,b.rotation=-45):b.rotation=
45;m.addChild(b);e.push(b);d=[];n=[];for(c=0;c<e.length;c++)d.push({x:-100,y:-100}),n[c]=!0,e[c].visible=!1;l=Math.floor(a.width/2)};this.unload=function(){for(var a=0;a<e.length;a++)m.removeChild(e[a])};this.reset=function(a){n[a]=!1;e[a].x=d[a].x;e[a].y=d[a].y;!0===this._checkIfAllBulletInactive()&&(c=!1,!1===f&&s_oGame.removeBullet(this))};this._checkIfAllBulletInactive=function(){for(var a=!0,b=0;b<n.length;b++)if(!0===n[b]){a=!1;break}return a};this.show=function(a,b,d){playSound("bullet2",1,
0);k=[];for(var f=0;f<e.length;f++){e[f].x=a;e[f].y=b;var g=parseFloat(Math.cos(degreesToRadians(e[f].rotation*e[f].scaleY-90))).toFixed(2),l=Math.sin(degreesToRadians(e[f].rotation*e[f].scaleY+90));k[f]={x:g*(3+d),y:l*(3+d)*h};e[f].visible=!0}c=!0};this.getPos=function(){return e};this.getSprite=function(a){return e[a]};this.getSprites=function(){return e};this.isUpdating=function(){return c};this.getRadius=function(){return l};this.update=function(){if(c)for(var a=0;a<e.length;a++)e[a].x+=k[a].x,
e[a].y+=k[a].y,(0>e[a].x||e[a].x>CANVAS_WIDTH||0>e[a].y||e[a].y>CANVAS_HEIGHT)&&this.reset(a)};this._init(a,g,b)}
function CBullet3(a,g,b){var c=!1,f,d,h,l,e,k,n,m;this._init=function(a,b,c){m=a;h=(f=c)?-1:1;e=[];a=s_oSpriteLibrary.getSprite(b);b=createBitmap(a);b.regX=a.width/2;b.regY=a.height/2;b.x=-100;b.y=-100;m.addChild(b);e.push(b);b=createBitmap(a);b.x=-100;b.y=-100;b.regX=a.width/2;b.regY=a.height/2;m.addChild(b);e.push(b);d=[];n=[];for(b=0;b<e.length;b++)d.push({x:-100,y:-100}),n[b]=!0,e[b].visible=!1;l=Math.floor(a.width/2)};this.unload=function(){for(var a=0;a<e.length;a++)m.removeChild(e[a])};this.reset=
function(a){n[a]=!1;e[a].x=d[a].x;e[a].y=d[a].y;!0===this._checkIfAllBulletInactive()&&(c=!1,!1===f&&s_oGame.removeBullet(this))};this._checkIfAllBulletInactive=function(){for(var a=!0,b=0;b<n.length;b++)if(!0===n[b]){a=!1;break}return a};this.show=function(a,b,d){playSound("bullet3",1,0);k=[];e[0].x=a-40;e[0].y=b;k[0]={x:0,y:(8+d)*h};e[0].visible=!0;e[1].x=a+40;e[1].y=b;k[1]={x:0,y:(8+d)*h};c=e[1].visible=!0};this.getPos=function(){return e};this.getSprite=function(a){return e[a]};this.getSprites=
function(){return e};this.isUpdating=function(){return c};this.getRadius=function(){return l};this.update=function(){if(c)for(var a=0;a<e.length;a++)e[a].x+=k[a].x,e[a].y+=k[a].y,(0>e[a].x||e[a].x>CANVAS_WIDTH||0>e[a].y||e[a].y>CANVAS_HEIGHT)&&this.reset(a)};this._init(a,g,b)}
function CBullet4(a,g,b){var c=!1,f,d,h,l,e,k,n,m;this._init=function(a,b,c){m=a;h=(f=c)?-1:1;e=[];a=s_oSpriteLibrary.getSprite(b);b=createBitmap(a);b.regX=a.width/2;b.regY=a.height/2;b.x=-100;b.y=-100;!1===c?(b.scaleY=-1,b.rotation=45):b.rotation=-45;m.addChild(b);e.push(b);b=createBitmap(a);b.x=-100;b.y=-100;b.regX=a.width/2;b.regY=a.height/2;!1===c?(b.scaleY=-1,b.rotation=-45):b.rotation=45;m.addChild(b);e.push(b);d=[];n=[];for(c=0;c<e.length;c++)d.push({x:-100,y:-100}),n[c]=!0,e[c].visible=!1;
l=Math.floor(a.width/2)};this.unload=function(){for(var a=0;a<e.length;a++)m.removeChild(e[a])};this.reset=function(a){n[a]=!1;e[a].x=d[a].x;e[a].y=d[a].y;!0===this._checkIfAllBulletInactive()&&(c=!1,!1===f&&s_oGame.removeBullet(this))};this._checkIfAllBulletInactive=function(){for(var a=!0,b=0;b<n.length;b++)if(!0===n[b]){a=!1;break}return a};this.show=function(a,b,d){playSound("bullet4",1,0);k=[];for(var f=0;f<e.length;f++){e[f].x=a;e[f].y=b;var g=parseFloat(Math.cos(degreesToRadians(e[f].rotation*
e[f].scaleY-90))).toFixed(2),l=Math.sin(degreesToRadians(e[f].rotation*e[f].scaleY+90));k[f]={x:g*(3+d),y:l*(3+d)*h};e[f].visible=!0}c=!0};this.getPos=function(){return e};this.getSprite=function(a){return e[a]};this.getSprites=function(){return e};this.isUpdating=function(){return c};this.getRadius=function(){return l};this.update=function(){if(c)for(var a=0;a<e.length;a++)e[a].x+=k[a].x,e[a].y+=k[a].y,(0>e[a].x||e[a].x>CANVAS_WIDTH||0>e[a].y||e[a].y>CANVAS_HEIGHT)&&this.reset(a)};this._init(a,g,
b)}
function CEndPanel(a){var g,b,c,f,d,h;this._init=function(a){g=createBitmap(a);d=new createjs.Text("","60px "+FONT_GAME,"#000");d.x=CANVAS_WIDTH/2+1;d.y=CANVAS_HEIGHT/2-160;d.textAlign="center";f=new createjs.Text("","60px "+FONT_GAME,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-162;f.textAlign="center";b=new createjs.Text("","40px "+FONT_GAME,"#000");b.x=CANVAS_WIDTH/2+1;b.y=CANVAS_HEIGHT/2+50;b.textAlign="center";c=new createjs.Text("","40px "+FONT_GAME,"#ffffff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/
2+52;c.textAlign="center";h=new createjs.Container;h.alpha=0;h.visible=!1;h.addChild(g,b,c,d,f);s_oStage.addChild(h)};this.unload=function(){h.off("mousedown",this._onExit)};this._initListener=function(){h.on("mousedown",this._onExit);$(s_oMain).trigger("show_interlevel_ad")};this.show=function(a){playSound("game_over",1,0);d.text=TEXT_GAMEOVER;f.text=TEXT_GAMEOVER;b.text=TEXT_SCORE+": "+a;c.text=TEXT_SCORE+": "+a;h.visible=!0;var e=this;createjs.Tween.get(h).to({alpha:1},500).call(function(){e._initListener()});
$(s_oMain).trigger("save_score",a)};this._onExit=function(){h.off("mousedown",this._onExit);s_oStage.removeChild(h);s_oGame.onExit()};this._init(a);return this}
function CEnemy(a,g){var b=!1,c,f,d,h,l,e,k,n,m;this._init=function(a,b){c=a;m=b;var e={images:[s_oSpriteLibrary.getSprite("enemies")],frames:{width:100,height:100,regX:50,regY:50},animations:{enemy_1:[0],enemy_2:[1],enemy_3:[2],enemy_4:[3]}},e=new createjs.SpriteSheet(e);k=createSprite(e,"enemy_1",50,50,100,100);k.y=c;k.stop();s_oStage.addChild(k);e={images:[s_oSpriteLibrary.getSprite("explosion")],frames:{width:149,height:149,regX:74,regY:74},animations:{show:[0,19,"hide"],hide:[20,21]}};e=new createjs.SpriteSheet(e,
"hide");n=createSprite(e,"hide",74,74,149,149);n.addEventListener("animationend",this.onAnimationEnd);n.stop();n.visible=!1;s_oStage.addChild(n);d=44};this.unload=function(){s_oStage.removeChild(k)};this.reset=function(){b=!1;playSound("explosion",1,0);n.x=k.x;n.y=k.y;n.visible=!0;n.gotoAndPlay("show");k.y=c};this.show=function(a,e,d){k.alpha=1;k.x=a;k.y=c;f=e;k.gotoAndStop("enemy_"+d);this._assignBulletType(d);b=!0};this._assignBulletType=function(a){l=Math.floor(Math.random()*MAX_SHOT_OCCURENCE)+
MIN_SHOT_OCCURENCE;e=0;h=a};this._shot=function(){var a;switch(h){case 1:a=new CBullet1(m,"bullet",!1);break;case 2:a=new CBullet2(m,"bullet",!1);break;case 3:a=new CBullet3(m,"bullet3",!1);break;case 4:a=new CBullet4(m,"bullet",!1)}a.show(k.x,k.y+40,f);s_oGame.addEnemyBullets(a)};this.onAnimationEnd=function(){n.x=k.x;n.y=k.y};this.getPos=function(){return{x:k.x,y:k.y}};this.getRadius=function(){return d};this.isMoving=function(){return b};this.getSprite=function(){return k};this.update=function(){b&&
(k.y+=f,s_oGame.checkCollision(this),e+=s_iTimeElaps,e>l&&(e=0,this._shot()))};this._init(a,g)}
function CGame(a){function g(a){if(!1!==c)if(f=!1,32===a.keyCode)s_oGame.onShot();else r.stop()}function b(a){if(!1===c||f)return a.preventDefault(),!1;a||(a=window.event);switch(a.keyCode){case 37:f=!0;s_oGame.onLeft();break;case 39:f=!0,s_oGame.onRight()}a.preventDefault();return!1}var c=!1,f=!1,d,h,l,e,k,n,m=-1,p,u,w,t=[],A,y,r,q,v,x,z=null;this._init=function(){d=0;A=new CScrollingMultipleBg([s_oSpriteLibrary.getSprite("parallax_1_1"),s_oSpriteLibrary.getSprite("parallax_1_2"),s_oSpriteLibrary.getSprite("parallax_1_3")]);
y=new CScrollingBg(s_oSpriteLibrary.getSprite("parallax_2"));var a=s_oSpriteLibrary.getSprite("hero");r=new CHero(HERO_START_X,CANVAS_HEIGHT-200,a);p=[];a=EDGEBOARD_X+50;do p.push(a),a+=100;while(a<CANVAS_WIDTH-50-EDGEBOARD_X);n=NUM_LIVES;v=new createjs.Container;s_oStage.addChild(v);this._initFallingObj();this._initBullets();q=new createjs.Shape;q.graphics.beginFill("red").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.alpha=.1;q.visible=!1;s_oStage.addChild(q);x=new CInterface;!1===s_bMobile&&(document.onkeydown=
b,document.onkeyup=g)};this.unload=function(){c=!1;s_oStage.removeAllChildren();r.unload();x.unload();null!==z&&z.unload();for(var a=0;a<u.length;a++)u[a].unload();for(a=0;a<w.length;a++)w[a].unload();for(a=0;a<t.length;a++)t[a].unload()};this._initFallingObj=function(){l=0;k=SPEED_FALLING_OBJ;u=[];for(var a=0;10>a;a++)u[a]=new CEnemy(START_Y_FALLING_OBJ,v)};this._initBullets=function(){e=0;w=[];for(var a=0;50>a;a++)w[a]=new CBullet1(v,"bullet2",!0)};this._showNextObj=function(){u[l].show(p[Math.floor(Math.random()*
p.length)],k,Math.floor(Math.random()*NUM_FALLING_OBJ)+1);l===u.length-1?(l=0,k<=MAX_SPEED_FALLING_OBJ&&(k+=1,TIME_OCCURENCE_FALLING_OBJ=6>k?2E3:7>k?1700:10>k?1500:15>k?1E3:700)):l++};this.addEnemyBullets=function(a){t.push(a)};this.removeBullet=function(a){for(var b=0;b<t.length;b++)t[b]===a&&(m=b)};this._lostLife=function(){q.visible=!0;var a=this;createjs.Tween.get(q).to({alpha:.6},400).call(function(){a._resetHurt()});r.hurt();n--;x.refreshLives(n);0===n&&(c=!1,r.gameOver())};this.gameOver=function(){$(s_oMain).trigger("end_level",
1);z=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));z.show(d)};this.checkCollision=function(a){!1===r.isHurting()&&checkRectCollision(a.getSprite(),r.getSprite())&&(a.reset(),this._lostLife())};this._checkBulletPlayerCollision=function(a){if(!1!==a.isUpdating())for(var b=a.getPos(),e=0;e<b.length;e++){for(var c=b[e],f=0;f<u.length;f++)if(u[f].isMoving()){var h=u[f].getPos(),g=u[f].getRadius(),h=Math.sqrt((h.x-c.x)*(h.x-c.x)+(h.y-c.y)*(h.y-c.y));if(h<g){u[f].reset();a.reset(e);d+=SCORE_HIT;x.refreshScore(d);
break}}for(f=0;f<t.length;f++)for(var g=t[f].getPos(),k=0;k<g.length;k++){var h=g[k],l=r.getRadius(),h=Math.sqrt((c.x-h.x)*(c.x-h.x)+(c.y-h.y)*(c.y-h.y));if(h<l){t[f].reset(k);a.reset(e);break}}}};this.checkBulletEnemyCollision=function(a){for(var b=a.getPos(),e=0;e<b.length;e++){var d=b[e],c=r.getPos(),f=r.getRadius();if(Math.sqrt((c.x-d.x)*(c.x-d.x)+(c.y-d.y)*(c.y-d.y))<f){this._lostLife();a.reset(e);break}}};this._resetHurt=function(){q.visible=!1;q.alpha=.5};this.onLeft=function(){r.moveLeft()};
this.onRight=function(){r.moveRight()};this.onShot=function(){var a=r.getBulletStartPoint();w[e].show(a.x,a.y,8);e===w.length-1?e=0:e++};this.onKeyReleased=function(){r.stop()};this.onExit=function(){this.unload();$(s_oMain).trigger("share_event",d);$(s_oMain).trigger("end_session");s_oMain.gotoMenu()};this._onExitHelp=function(){x.onExitFromHelp();h=TIME_OCCURENCE_FALLING_OBJ;c=!0;$(s_oMain).trigger("start_level",1)};this._updateParallaxes=function(){A.update(PARALLAX1_SPEED);y.update(PARALLAX2_SPEED)};
this.update=function(){if(c){h+=s_iTimeElaps;h>TIME_OCCURENCE_FALLING_OBJ&&(h=0,this._showNextObj());r.update();for(var a=0;a<u.length;a++)u[a].update();for(a=0;a<w.length;a++)w[a].update(),this._checkBulletPlayerCollision(w[a]);for(a=0;a<t.length;a++)t[a].update(),this.checkBulletEnemyCollision(t[a]);-1!==m&&(t[m].unload(),t.splice(m,1),m=-1);this._updateParallaxes()}};s_oGame=this;HERO_ACCELLERATION=a.hero_accelleration;HERO_FRICTION=a.hero_friction;MAX_HERO_SPEED=a.max_hero_speed;TIME_OCCURENCE_FALLING_OBJ=
a.time_occurence_falling_obj;SPEED_FALLING_OBJ=a.speed_enemy;MAX_SPEED_FALLING_OBJ=a.max_speed_enemy;NUM_LIVES=a.num_lives;SPEED_PLAYER_BULLET=a.speed_player_bullet;SCORE_HIT=a.score_hit;MIN_SHOT_OCCURENCE=a.min_shot_occurence;MAX_SHOT_OCCURENCE=a.max_shot_occurence;this._init()}var s_oGame;
function CGfxButton(a,g,b){var c,f,d;this._init=function(a,b,e){c=[];f=[];d=createBitmap(e);d.x=a;d.y=b;d.regX=e.width/2;d.regY=e.height/2;s_oStage.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);s_oStage.removeChild(d)};this.setVisible=function(a){d.visible=a};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){c[a]=b;f[a]=e};this.buttonRelease=
function(){d.scaleX=1;d.scaleY=1;playSound("click",1,0);c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};this.buttonDown=function(){d.scaleX=.9;d.scaleY=.9;c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this.setPosition=function(a,b){d.x=a;d.y=b};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};this._init(a,g,b);return this}
function CHelpPanel(a,g,b){var c,f,d,h,l,e;this._init=function(a,b,g){l=createBitmap(g);f=new createjs.Text(TEXT_HELP1,"24px "+FONT_GAME,"#000000");f.textAlign="center";f.lineWidth=300;f.x=CANVAS_WIDTH/2+152;f.y=422;c=new createjs.Text(TEXT_HELP1,"24px "+FONT_GAME,"#ffffff");c.textAlign="center";c.lineWidth=300;c.x=CANVAS_WIDTH/2+150;c.y=420;h=new createjs.Text(TEXT_HELP2,"24px "+FONT_GAME,"#000000");h.textAlign="center";h.lineWidth=300;h.x=CANVAS_WIDTH/2+152;h.y=732;d=new createjs.Text(TEXT_HELP2,
"24px "+FONT_GAME,"#ffffff");d.textAlign="center";d.lineWidth=300;d.x=CANVAS_WIDTH/2+150;d.y=730;e=new createjs.Container;e.x=a;e.y=b;e.addChild(l,f,c,h,d);s_oStage.addChild(e);var p=this;e.on("pressup",function(){p._onExitHelp()})};this.unload=function(){s_oStage.removeChild(e);var a=this;e.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){this.unload();s_oGame._onExitHelp()};this._init(a,g,b)}
function CHero(a,g,b){var c,f=!1,d=!1,h,l,e,k,n,m,p;this._init=function(a,b,d){e=0;k=1;n=0;c=!1;d={images:[d],frames:{width:65,height:100,regX:32,regY:50},animations:{idle:[0],move_right:[1,5,"idle_right"],idle_right:[5],back_right:[6,10,"idle"],move_left:[11,15,"idle_left"],idle_left:[15],back_left:[16,20,"idle"]}};d=new createjs.SpriteSheet(d);m=createSprite(d,"idle",32,50,65,100);m.x=a;m.y=b;m.stop();s_oStage.addChild(m);h=32.5;l=50;d={images:[s_oSpriteLibrary.getSprite("explosion_hero")],frames:{width:200,
height:200,regX:100,regY:100},animations:{show:[0,19,"hide"],hide:[20,21]}};a=new createjs.SpriteSheet(d,"hide");p=createSprite(a,"hide",100,100,200,200);p.addEventListener("animationend",this.onAnimationEnd);p.stop();p.visible=!1;s_oStage.addChild(p)};this.unload=function(){createjs.Tween.removeTweens(m);p.removeEventListener("animationend",oParent.onAnimationEnd)};this.moveLeft=function(){m.gotoAndPlay("move_left");f=!0};this.moveRight=function(){m.gotoAndPlay("move_right");d=!0};this.onAnimationEnd=
function(){p.stop();s_oGame.gameOver()};this.stop=function(){f?m.gotoAndPlay("back_left"):m.gotoAndPlay("back_right");d=f=!1};this.hurt=function(){k=1===k?0:1;n++;if(6>n){c=!0;var a=this;createjs.Tween.get(m).to({alpha:k},150,createjs.Ease.cubicOut).call(function(){a.hurt()})}else c=!1,n=0,k=1,createjs.Tween.get(m).to({alpha:k},150,createjs.Ease.cubicOut)};this.gameOver=function(){m.visible=!1;p.x=m.x;p.y=m.y;p.visible=!0;p.gotoAndPlay("show");playSound("final_explosion",1,0)};this.getPos=function(){return{x:m.x,
y:m.y}};this.getHeadY=function(){return m.y-l};this.getRadius=function(){return h};this.isHurting=function(){return c};this.getBulletStartPoint=function(){return{x:m.x,y:this.getHeadY()}};this.getSprite=function(){return m};this.update=function(){f&&(e-=HERO_ACCELLERATION);d&&(e+=HERO_ACCELLERATION);m.x+=e;e*=HERO_FRICTION;e>MAX_HERO_SPEED&&(e=MAX_HERO_SPEED);e<-MAX_HERO_SPEED&&(e=-MAX_HERO_SPEED);.1>Math.abs(e)&&(e=0);m.x+h+e>CANVAS_WIDTH&&(m.x=CANVAS_WIDTH-h-e);0>m.x-h+e&&(m.x=h-e)};this._init(a,
g,b)}
function CInterface(){var a,g,b,c,f,d,h,l,e,k,n,m,p,u,w,t,A,y,r,q,v,x,z;this._init=function(){f=CANVAS_WIDTH/2;d=30;r=new createjs.Text(TEXT_SCORE+": 0","40px "+FONT_GAME,"#ffffff");r.x=f;r.y=d;r.textAlign="center";s_oStage.addChild(r);n=70;m=CANVAS_HEIGHT-70;t=new CGfxButton(n,m,s_oSpriteLibrary.getSprite("but_left"),!0);t.addEventListener(ON_MOUSE_DOWN,this._onLeftPressed,this);t.addEventListener(ON_MOUSE_UP,this._onLeftReleased,this);e=180;k=CANVAS_HEIGHT-70;A=new CGfxButton(e,k,s_oSpriteLibrary.getSprite("but_right"),!0);
A.addEventListener(ON_MOUSE_DOWN,this._onRightPressed,this);A.addEventListener(ON_MOUSE_UP,this._onRightReleased,this);h=CANVAS_WIDTH-130;l=CANVAS_HEIGHT-70;y=new CTextButton(h,l,s_oSpriteLibrary.getSprite("but_play"),TEXT_SHOOT,FONT_GAME,"#ffffff",34);y.addEventListener(ON_MOUSE_DOWN,this._onShot,this);c=b=10;v=createBitmap(s_oSpriteLibrary.getSprite("life"));v.x=b;v.y=c;s_oStage.addChild(v);x=new createjs.Text("x"+NUM_LIVES,"30px "+FONT_GAME,"#ffffff");x.x=74;x.y=40;s_oStage.addChild(x);q=new CHelpPanel(0,
0,s_oSpriteLibrary.getSprite("bg_help"));var B=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-B.height/2-10;g=B.height/2+10;w=new CGfxButton(a,g,B,!0);w.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)B=s_oSpriteLibrary.getSprite("audio_icon"),p=a-B.height-10,u=g,z=new CToggle(p,u,B,s_bAudioActive),z.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(f,q){w.setPosition(a-
f,q+g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||z.setPosition(p-f,q+u);t.setPosition(n+f,m-q);A.setPosition(e+f,k-q);y.setPosition(h-f,l-q);r.y=d+q;v.x=b+f;v.y=c+q;x.x=v.x+66;x.y=v.y+32};this.unload=function(){w.unload();w=null;t.unload();t=null;A.unload();A=null;y.unload();y=null;q.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)z.unload(),z=null;s_oInterface=null};this.refreshScore=function(a){r.text=TEXT_SCORE+": "+a};this.refreshLives=function(a){x.text="x"+a};this._onLeftPressed=function(){s_oGame.onLeft()};
this._onLeftReleased=function(){s_oGame.onKeyReleased()};this._onRightPressed=function(){s_oGame.onRight()};this._onRightReleased=function(){s_oGame.onKeyReleased()};this._onShot=function(){s_oGame.onShot()};this.onExitFromHelp=function(){q.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};s_oInterface=this;this._init();return this}var s_oInterface=null;TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="SCORE";
TEXT_PLAY="PLAY";TEXT_HELP1="USE ARROW BUTTONS OR KEYS TO MOVE THE STARSHIP";TEXT_HELP2="CLICK SPACEBAR OR SHOOT BUTTON TO SHOOT!!";TEXT_SHOOT="SHOOT";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CMain(a){var g,b=0,c=0,f=STATE_LOADING,d,h,l;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=!1;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader;g=!0};this.soundLoaded=function(){b++;h.refreshLoader(Math.floor(b/c*100));b===c&&(h.unload(),playSound("soundtrack",1,-1),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/bullet1.ogg",
"bullet1",10),createjs.Sound.registerSound("./sounds/bullet2.ogg","bullet2",10),createjs.Sound.registerSound("./sounds/bullet4.ogg","bullet4",10),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/explosion.ogg","explosion"),createjs.Sound.registerSound("./sounds/final_explosion.ogg","final_explosion"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/bullet1.mp3","bullet1",10),createjs.Sound.registerSound("./sounds/bullet2.mp3","bullet2",10),createjs.Sound.registerSound("./sounds/bullet4.mp3","bullet4",10),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/explosion.mp3","explosion"),createjs.Sound.registerSound("./sounds/final_explosion.mp3","final_explosion"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack")),
c+=7)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("parallax_1_1","./sprites/parallax_1_1.jpg");s_oSpriteLibrary.addSprite("parallax_1_2","./sprites/parallax_1_2.jpg");s_oSpriteLibrary.addSprite("parallax_1_3","./sprites/parallax_1_3.jpg");
s_oSpriteLibrary.addSprite("parallax_2","./sprites/parallax_2.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("hero","./sprites/hero.png");s_oSpriteLibrary.addSprite("but_left","./sprites/but_left.png");s_oSpriteLibrary.addSprite("but_right","./sprites/but_right.png");s_oSpriteLibrary.addSprite("enemies","./sprites/enemies.png");s_oSpriteLibrary.addSprite("life","./sprites/life.png");s_oSpriteLibrary.addSprite("bullet",
"./sprites/bullet.png");s_oSpriteLibrary.addSprite("bullet2","./sprites/bullet2.png");s_oSpriteLibrary.addSprite("bullet3","./sprites/bullet3.png");s_oSpriteLibrary.addSprite("explosion","./sprites/explosion.png");s_oSpriteLibrary.addSprite("explosion_hero","./sprites/explosion_hero.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;h.refreshLoader(Math.floor(b/c*100));b===
c&&(h.unload(),playSound("soundtrack",1,-1),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();g=!0};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(){l=new CGame(d);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){g=!1;createjs.Ticker.paused=!0;$("#block_game").css("display",
"block")};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();g=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none")};this._update=function(a){if(!1!==g){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&l.update();s_oStage.update(a)}};s_oMain=this;d=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oSoundTrackSnd,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack;
function CMenu(){var a,g,b,c,f,d;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);var h=s_oSpriteLibrary.getSprite("but_play");c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-180,h,TEXT_PLAY,FONT_GAME,"#ffffff",40);c.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-h.height/2-10,g=h.height/2+10,d=new CToggle(a,g,h,s_bAudioActive),d.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(f);createjs.Tween.get(f).to({alpha:0},1E3).call(function(){f.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(b,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||d.setPosition(a-b,c+g)};this.unload=function(){c.unload();c=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d.unload(),d=null;s_oStage.removeAllChildren();s_oMenu=null};
this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoGame()};s_oMenu=this;this._init()}var s_oMenu=null;
function CPreloader(){var a,g,b,c,f,d,h;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();h=new createjs.Container;s_oStage.addChild(h)};this.unload=function(){h.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(d).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(l);l=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(l);c.x=CANVAS_WIDTH/2-l.width/2;c.y=CANVAS_HEIGHT-100;h.addChild(c);a=l.width;g=l.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,g);h.addChild(f);c.mask=
f;b=new createjs.Text("","30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-100;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";h.addChild(b);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;trace("create _oLoadingText");h.addChild(d)};this.refreshLoader=function(d){b.text=d+"%";f.graphics.clear();d=Math.floor(d*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,d,g)};this._init()}
function CScrollingBg(a){var g,b,c;this._init=function(a){c=a;b=[];for(var d=-a.height;d<CANVAS_HEIGHT;){var h=createBitmap(a);h.y=d;d+=a.height;b.push(h);s_oStage.addChild(h)}g=0};this.update=function(a){for(var d=0;d<b.length;d++)b[d].y>CANVAS_HEIGHT&&(b[d].y=b[g].y-c.height,g=d),b[d].y+=a};this._init(a)}
function CScrollingMultipleBg(a){var g,b,c;this._init=function(a){b=[];var d=-a[0].height;c=a[0].height;for(var h=0;d<2*CANVAS_HEIGHT;){var l=createBitmap(a[h]);l.y=d;d+=c;b.push(l);s_oStage.addChild(l);h++}g=0};this.update=function(a){for(var d=0;d<b.length;d++)b[d].y>CANVAS_HEIGHT&&(b[d].y=b[g].y-c,g=d),b[d].y+=a,b[d].visible=b[d].y>-c&&b[d].y<CANVAS_HEIGHT?!0:!1};this._init(a)}
function CTextButton(a,g,b,c,f,d,h){var l,e,k;this._init=function(a,b,d,c,f,h,g){l=[];e=[];var y=createBitmap(d),r=Math.ceil(g/20),q=new createjs.Text(c,"bold "+g+"px "+f,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var v=q.getBounds();q.x=d.width/2+r;q.y=Math.floor(d.height/2)+v.height/3+r;c=new createjs.Text(c,"bold "+g+"px "+f,h);c.textAlign="center";c.textBaseline="alphabetic";v=c.getBounds();c.x=d.width/2;c.y=Math.floor(d.height/2)+v.height/3;k=new createjs.Container;k.x=a;k.y=
b;k.regX=d.width/2;k.regY=d.height/2;k.addChild(y,q,c);s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown");k.off("pressup");s_oStage.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){oParent=this;k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){l[a]=b;e[a]=d};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(e[ON_MOUSE_UP])};
this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN])};this.setPosition=function(a,b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(a,g,b,c,f,d,h);return this}var s_iOffsetX=0,s_iOffsetY=0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var g=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var d=b.createElement("div");d.id="vpw-test-d";d.style.cssText="position:absolute;top:-1000px";d.innerHTML="<style>@media("+g+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+g+":7px!important}}</style>";f.appendChild(d);c.insertBefore(f,b.head);
a=7==d["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(f)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var g=getSize("Width");s_iScaleFactor=Math.min(a/CANVAS_HEIGHT,g/CANVAS_WIDTH);var b=CANVAS_WIDTH*s_iScaleFactor,c=CANVAS_HEIGHT*s_iScaleFactor,f=0;c<a?(f=a-c,c+=f,b+=CANVAS_WIDTH/CANVAS_HEIGHT*f):b<g&&(f=g-b,b+=f,c+=CANVAS_HEIGHT/CANVAS_WIDTH*f);var f=a/2-c/2,d=g/2-b/2,h=CANVAS_WIDTH/b;if(d*h<-EDGEBOARD_X||f*h<-EDGEBOARD_Y)s_iScaleFactor=Math.min(a/
(CANVAS_HEIGHT-2*EDGEBOARD_Y),g/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*s_iScaleFactor,c=CANVAS_HEIGHT*s_iScaleFactor,f=(a-c)/2,d=(g-b)/2,h=CANVAS_WIDTH/b;s_iOffsetX=-1*d*h;s_iOffsetY=-1*f*h;0<=f&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",b+"px");$("#canvas").css("height",c+"px");0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top",
"0px");$("#canvas").css("left",d+"px")}}function createBitmap(a,g,b){var c=new createjs.Bitmap(a),f=new createjs.Shape;g&&b?f.graphics.beginFill("#fff").drawRect(0,0,g,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=f;return c}function createSprite(a,g,b,c,f,d){a=null!==g?new createjs.Sprite(a,g):new createjs.Sprite(a);g=new createjs.Shape;g.graphics.beginFill("#000000").drawRect(-b,-c,f,d);a.hitArea=g;return a}
function randomFloatBetween(a,g,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(g-a),g).toFixed(b))}function shuffle(a){for(var g=a.length,b,c;0!==g;)c=Math.floor(Math.random()*g),--g,b=a[g],a[g]=a[c],a[c]=b;return a}function formatTime(a){a/=1E3;var g=Math.floor(a/60);a=parseFloat(a-60*g).toFixed(1);var b="",b=10>g?b+("0"+g+":"):b+(g+":");return b=10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,g){var b,c;b=getBounds(a,.9);c=getBounds(g,.98);return calculateIntersection(b,c)}function calculateIntersection(a,g){var b,c,f,d,h,l,e,k;b=a.x+(f=a.width/2);c=a.y+(d=a.height/2);h=g.x+(l=g.width/2);e=g.y+(k=g.height/2);b=Math.abs(b-h)-(f+l);c=Math.abs(c-e)-(d+k);return 0>b&&0>c?(b=Math.min(Math.min(a.width,g.width),-b),c=Math.min(Math.min(a.height,g.height),-c),{x:Math.max(a.x,g.x),y:Math.max(a.y,g.y),width:b,height:c,rect1:a,rect2:g}):null}
function getBounds(a,g){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,f=c.length,d,h;for(h=0;h<f;h++)d=getBounds(c[h],1),d.x<b.x&&(b.x=d.x),d.y<b.y&&(b.y=d.y),d.x+d.width>b.x2&&(b.x2=d.x+d.width),d.y+d.height>b.y2&&(b.y2=d.y+d.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var l,e;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,h=f.width*g,l=f.height*g):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),h=f.rect.width,l=f.rect.height,c=f.regX,e=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;h=h||0;e=e||0;l=l||0;b.regX=c;b.regY=e;f=a.localToGlobal(0-c,0-e);d=a.localToGlobal(h-c,l-e);h=a.localToGlobal(h-c,0-e);c=a.localToGlobal(0-c,l-e);b.x=Math.min(Math.min(Math.min(f.x,
d.x),h.x),c.x);b.y=Math.min(Math.min(Math.min(f.y,d.y),h.y),c.y);b.width=Math.max(Math.max(Math.max(f.x,d.x),h.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,d.y),h.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);a.dispatchEvent(g)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[g]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var g="hidden";g in document?document.addEventListener("visibilitychange",a):(g="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(g="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(g="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function playSound(a,g,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:g}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function setVolume(a,g){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=g}function setMute(a,g){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(g)}function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}function getParamValue(a){for(var g=window.location.search.substring(1).split("&"),b=0;b<g.length;b++){var c=g[b].split("=");if(c[0]==a)return c[1]}}
function CToggle(a,g,b,c){var f,d,h,l;this._init=function(a,b,c,g){d=[];h=[];var p=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=g;l=createSprite(p,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);l.x=a;l.y=b;l.stop();s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",this.buttonRelease);s_oStage.removeChild(l)};this._initListener=
function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){d[a]=b;h[a]=c};this.setActive=function(a){f=a;l.gotoAndStop("state_"+f)};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;playSound("click",1,0);f=!f;l.gotoAndStop("state_"+f);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(h[ON_MOUSE_UP],f)};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(a,b){l.x=a;l.y=
b};this._init(a,g,b,c)}
var CANVAS_WIDTH=968,CANVAS_HEIGHT=1224,EDGEBOARD_X=100,EDGEBOARD_Y=100,DISABLE_SOUND_MOBILE=!1,FONT_GAME="space_marinenominal",FPS_TIME=1E3/24,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,HERO_START_X=CANVAS_WIDTH/2,HERO_ACCELLERATION,HERO_FRICTION,MAX_HERO_SPEED,START_Y_FALLING_OBJ=-50,TIME_OCCURENCE_FALLING_OBJ,SPEED_FALLING_OBJ,MAX_SPEED_FALLING_OBJ,NUM_FALLING_OBJ=4,NUM_LIVES,SPEED_PLAYER_BULLET,
SCORE_HIT,PARALLAX1_SPEED=1,PARALLAX2_SPEED=10,MIN_SHOT_OCCURENCE,MAX_SHOT_OCCURENCE;
function CSpriteLibrary(){var a,g,b,c,f,d;this.init=function(h,l,e){b=g=0;c=h;f=l;d=e;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},g++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(d)};this._onSpriteLoaded=function(){c.call(d);++b==g&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return g}};
