var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
function getSize(a){var e=a.toLowerCase(),d=window.document,b=d.documentElement;if(void 0===window["inner"+a])a=b["client"+a];else if(window["inner"+a]!=b["client"+a]){var c=d.createElement("body");c.id="vpw-test-b";c.style.cssText="overflow:scroll";var k=d.createElement("div");k.id="vpw-test-d";k.style.cssText="position:absolute;top:-1000px";k.innerHTML="<style>@media("+e+":"+b["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";c.appendChild(k);b.insertBefore(c,d.head);
a=7==k["offset"+a]?b["client"+a]:window["inner"+a];b.removeChild(c)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width");_checkOrientation(e,a);var d=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),b=CANVAS_WIDTH*d,d=CANVAS_HEIGHT*d,c;d<a?(c=a-d,d+=c,b+=CANVAS_WIDTH/CANVAS_HEIGHT*c):b<e&&(c=e-b,b+=c,d+=CANVAS_HEIGHT/CANVAS_WIDTH*c);c=a/2-d/2;var k=e/2-b/2,f=CANVAS_WIDTH/b;if(k*f<-EDGEBOARD_X||c*f<-EDGEBOARD_Y)d=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
e/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*d,d*=CANVAS_HEIGHT,c=(a-d)/2,k=(e-b)/2,f=CANVAS_WIDTH/b;s_iOffsetX=-1*k*f;s_iOffsetY=-1*c*f;0<=c&&(s_iOffsetY=0);0<=k&&(s_iOffsetX=0);null!==s_oGame&&s_oGame.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oBetPanel&&s_oBetPanel.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*b,s_oStage.canvas.height=2*d,canvas.style.width=
b+"px",canvas.style.height=d+"px",a=Math.min(b/CANVAS_WIDTH,d/CANVAS_HEIGHT),s_iScaleFactor=2*a,s_oStage.scaleX=s_oStage.scaleY=2*a):s_bMobile&&!1===isIOS()?($("#canvas").css("width",b+"px"),$("#canvas").css("height",d+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=d,s_iScaleFactor=Math.min(b/CANVAS_WIDTH,d/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>c?$("#canvas").css("top",c+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",k+"px")}}
function _checkOrientation(a,e){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>e?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,e,d){var b=new createjs.Bitmap(a),c=new createjs.Shape;e&&d?c.graphics.beginFill("#fff").drawRect(0,0,e,d):c.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=c;return b}function createSprite(a,e,d,b,c,k){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-d,-b,c,k);a.hitArea=e;return a}
function randomFloatBetween(a,e,d){"undefined"===typeof d&&(d=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(d))}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=Math.floor(a-60*e);var d="",d=10>e?d+("0"+e+":"):d+(e+":");return 10>a?d+("0"+a):d+a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var e=a.length,d,b;0<e;)b=Math.floor(Math.random()*e),e--,d=a[e],a[e]=a[b],a[b]=d;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var e=window.location.search.substring(1).split("&"),d=0;d<e.length;d++){var b=e[d].split("=");if(b[0]==a)return b[1]}}Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var e=Array.prototype.slice.call(arguments);return a.sort(function(a,b){for(var c=e.slice(),d=c.shift();a[d]==b[d]&&c.length;)d=c.shift();return a[d]==b[d]?0:a[d]>b[d]?1:-1})};function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}
function playSound(a,e,d){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:d,volume:e}):null}function setVolume(a,e){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=e}function setMute(a,e){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(e)}function easeLinear(a,e,d,b){return d*a/b+e}function collisionWithCircle(a,e,d){var b=a.getX()-e.getX(),c=a.getY()-e.getY();return Math.sqrt(b*b+c*c)<a.getCollision()*d+e.getCollision()*d?!0:!1}
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[e]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var e="hidden";e in document?document.addEventListener("visibilitychange",a):(e="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(e="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(e="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CSpriteLibrary(){var a,e,d,b,c,k;this.init=function(f,h,g){d=e=0;b=f;c=h;k=g;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},e++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){c.call(k)};this._onSpriteLoaded=function(){b.call(k);++d===e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=1024,CANVAS_HEIGHT=768,EDGEBOARD_X=0,EDGEBOARD_Y=168,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="impactregular",SECONDARY_FONT="Digital-7",TERTIARY_FONT="InfiniteJustice",STATE_LOADING=0,STATE_MENU=1,STATE_BET_PANEL=2,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,CHIP_VALUES,BET_PANEL_X=70,BET_PANEL_Y=165,BET_PANEL_WIDTH,BET_PANEL_HEIGHT,GREYHOUND_WIDTH=338,GREYHOUND_HEIGHT=170,NUM_CHIPS,NUM_GREYHOUNDS,MIN_BET,
MAX_BET,WIN_OCCURRENCE,NUM_TRACK_BG=416,RACE_TIME=Math.round(NUM_TRACK_BG/(FPS/2)),ARRIVAL_X=491,TIME_CHECK_RANK=3E3,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SHOW_CREDITS;
function CGameSettings(a){var e,d,b,c,k,f,h,g,l;this._init=function(b){l=b;b=l.greyhound_names;NUM_GREYHOUNDS=b.length;e=[];for(var c=0;c<NUM_GREYHOUNDS;c++)e[c]=b[c];this._initSimpleOdd();this._initForecastOdd();this._initPaths();this._initGreyhoundInfo();f=CHIP_VALUES};this._initSimpleOdd=function(){var a=l.odd_win_bet,n=l.odd_place_bet,f=l.odd_show_bet;d=[];b=[];c=[];for(var e=0;e<a.length;e++)d[e]=a[e],b[e]=n[e],c[e]=f[e]};this._initForecastOdd=function(){var b=l.forecast;k=[];for(var c=0;c<NUM_GREYHOUNDS;c++)k[c]=
[];for(c=0;c<b.length;c++)k[b[c].first-1][b[c].second-1]=b[c].odd};this._initPaths=function(){h=[];var b=[{x:230,frame:30},{x:500,frame:180},{x:600,frame:180},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],c=[{x:250,frame:30},{x:600,frame:200},{x:650,frame:180},{x:450,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],a=[{x:170,frame:30},{x:400,frame:150},{x:450,frame:210},{x:400,frame:140},{x:300,
frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],d=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],e=[{x:220,frame:30},{x:350,frame:280},{x:480,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-450,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}],f=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-600,frame:480},{x:CANVAS_WIDTH+
GREYHOUND_WIDTH,frame:30}];h.push({place_1:b,place_2:c,place_3:a,place_4:d,place_5:e,place_6:f});b=[{x:230,frame:30},{x:450,frame:180},{x:500,frame:180},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:250,frame:30},{x:600,frame:200},{x:550,frame:180},{x:350,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];a=[{x:170,frame:30},{x:450,frame:150},{x:550,frame:210},{x:500,frame:140},{x:400,frame:130},
{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:190,frame:30},{x:300,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-450,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:210,frame:30},{x:360,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-600,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,
frame:30}];h.push({place_1:b,place_2:c,place_3:a,place_4:d,place_5:e,place_6:f});b=[{x:230,frame:30},{x:500,frame:180},{x:600,frame:180},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:250,frame:30},{x:600,frame:200},{x:650,frame:180},{x:500,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];a=[{x:170,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:450,frame:130},{x:ARRIVAL_X-
GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:220,frame:30},{x:350,frame:280},{x:480,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
h.push({place_1:b,place_2:c,place_3:a,place_4:d,place_5:e,place_6:f});b=[{x:330,frame:30},{x:450,frame:180},{x:550,frame:180},{x:650,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:250,frame:30},{x:350,frame:200},{x:450,frame:180},{x:600,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];a=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/
2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:290,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:210,frame:30},{x:360,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:b,
place_2:c,place_3:a,place_4:d,place_5:e,place_6:f});b=[{x:230,frame:30},{x:350,frame:180},{x:400,frame:180},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:250,frame:30},{x:350,frame:200},{x:450,frame:180},{x:500,frame:180},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];a=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,
frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:190,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:210,frame:30},{x:260,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:b,
place_2:c,place_3:a,place_4:d,place_5:e,place_6:f});b=[{x:230,frame:50},{x:350,frame:200},{x:400,frame:100},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:250},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:250,frame:100},{x:350,frame:150},{x:450,frame:150},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];a=[{x:270,frame:50},{x:400,frame:150},{x:450,frame:200},{x:400,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:200},{x:CANVAS_WIDTH+
GREYHOUND_WIDTH,frame:30}];d=[{x:190,frame:30},{x:340,frame:170},{x:360,frame:300},{x:380,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:220,frame:100},{x:350,frame:200},{x:400,frame:200},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:210,frame:50},{x:260,frame:300},{x:300,frame:200},{x:220,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:150},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,
frame:30}];h.push({place_1:b,place_2:c,place_3:a,place_4:d,place_5:e,place_6:f});b=[{x:230,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:250,frame:100},{x:350,frame:150},{x:450,frame:150},{x:500,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];a=[{x:270,frame:50},{x:200,frame:150},{x:450,frame:400},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,
frame:30}];d=[{x:190,frame:30},{x:340,frame:170},{x:360,frame:300},{x:380,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:220,frame:100},{x:350,frame:200},{x:400,frame:200},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:210,frame:50},{x:260,frame:300},{x:300,frame:200},{x:220,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:150},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
h.push({place_1:b,place_2:c,place_3:a,place_4:d,place_5:e,place_6:f});b=[{x:230,frame:50},{x:250,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:250,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];a=[{x:270,frame:50},{x:330,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:190,frame:50},{x:230,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/
2-390,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:220,frame:50},{x:300,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:210,frame:50},{x:130,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:b,place_2:c,place_3:a,place_4:d,place_5:e,place_6:f});b=[{x:210,frame:50},{x:130,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
c=[{x:220,frame:50},{x:300,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];a=[{x:270,frame:50},{x:330,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:250,frame:50},{x:430,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-390,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:190,frame:50},{x:190,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
f=[{x:230,frame:50},{x:250,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:450},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:b,place_2:c,place_3:a,place_4:d,place_5:e,place_6:f});b=[{x:330,frame:30},{x:450,frame:180},{x:550,frame:180},{x:650,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];c=[{x:250,frame:90},{x:450,frame:300},{x:600,frame:200},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-150,frame:210},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];
a=[{x:270,frame:30},{x:400,frame:150},{x:450,frame:210},{x:600,frame:140},{x:500,frame:130},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-250,frame:140},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];d=[{x:290,frame:30},{x:340,frame:150},{x:360,frame:300},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-410,frame:320},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];e=[{x:220,frame:30},{x:350,frame:280},{x:400,frame:190},{x:320,frame:100},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-550,frame:200},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];f=[{x:310,frame:30},
{x:400,frame:290},{x:ARRIVAL_X-GREYHOUND_WIDTH/2-650,frame:480},{x:CANVAS_WIDTH+GREYHOUND_WIDTH,frame:30}];h.push({place_1:b,place_2:c,place_3:a,place_4:d,place_5:e,place_6:f})};this._initGreyhoundInfo=function(){g=[];g[0]={start:new createjs.Point(208,342),scale:.66};g[1]={start:new createjs.Point(186,352),scale:.7};g[2]={start:new createjs.Point(163,363),scale:.74};g[3]={start:new createjs.Point(134,376),scale:.8};g[4]={start:new createjs.Point(99,394),scale:.9};g[5]={start:new createjs.Point(53,
415),scale:1}};this.getIndexForFiches=function(b){for(var c=0,a=0;a<f.length;a++)f[a]===b&&(c=a);return c};this.getGreyhoundPercentageArray=function(){for(var b=[],c=0;c<d.length;c++)for(var a=Math.floor(d[c]),e=0;e<a;e++)b.push(c);return b=shuffle(b)};this.getGreyhoundName=function(b){return e[b]};this.getAllGreyhoundNames=function(){return e};this.getOddWin=function(b){return d[b]};this.getOddPlace=function(c){return b[c]};this.getOddShow=function(b){return c[b]};this.getForecastOdd=function(b,
c){return k[b][c]};this.getRandomPath=function(){return h[Math.floor(Math.random()*h.length)]};this.getGreyhoundInfo=function(b){return g[b]};s_oGameSettings=this;this._init(a)}
var s_oGameSettings=null,TEXT_CURRENCY="$",TEXT_START_RACE="START RACE",TEXT_CLEAR_BET="CLEAR BET",TEXT_MONEY="MONEY",TEXT_BET="BET",TEXT_MIN_BET="MIN BET",TEXT_MAX_BET="MAX BET",TEXT_TRAP="TRAP",TEXT_GREYHOUND_NAME="GREYHOUND NAME",TEXT_ODDS="ODDS",TEXT_WINS="WINS",TEXT_PLACE="PLACE",TEXT_SHOW="SHOW",TEXT_WIN="WIN",TEXT_NO_WIN="NO WIN",TEXT_CREDITS_DEVELOPED="DEVELOPED BY",TEXT_NO_MONEY="NOT ENOUGH MONEY!!",TEXT_ERR_MAX_BET="YOUR BET IS HIGHER THAN MAXIMUM ONE!!",TEXT_ERR_MIN_BET="YOUR BET IS LOWER THAN MINIMUM ONE!!",
TEXT_ARE_YOU_SURE="ALL YOUR BETS WILL BE LOST!! ARE YOU SURE?";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,e,d,b,c,k,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this.hide=function(){var b=this;setTimeout(function(){createjs.Tween.get(k).to({alpha:1},500).call(function(){b.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));f.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");b=createBitmap(h);b.x=CANVAS_WIDTH/2-h.width/2;b.y=CANVAS_HEIGHT-240;f.addChild(b);a=h.width;e=h.height;c=new createjs.Shape;c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(b.x,b.y,1,e);f.addChild(c);
b.mask=c;d=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT-250;d.shadow=new createjs.Shadow("#000",2,2,2);d.textBaseline="alphabetic";d.textAlign="center";f.addChild(d);k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=0;f.addChild(k)};this.refreshLoader=function(f){d.text=f+"%";c.graphics.clear();f=Math.floor(f*a/100);c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(b.x,b.y,f,e)};this._init()}
function CMain(a){var e,d=0,b=0,c=STATE_LOADING,k,f;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(b){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;k=new CPreloader};this.preloaderReady=function(){jQuery.getJSON("greyhound_info.json",this.onLoadedJSON);e=!0};this.onLoadedJSON=function(b){s_oGameSettings=new CGameSettings(b);s_oBetList=new CBetList;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_oMain._initSounds();s_oMain._loadImages()};this.soundLoaded=function(){d++;k.refreshLoader(Math.floor(d/b*100));d===b&&this._onRemovePreloader()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&
(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/chip.ogg","chip"),createjs.Sound.registerSound("./sounds/start_race.ogg","start_race"),createjs.Sound.registerSound("./sounds/photo.ogg",
"photo")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/chip.mp3","chip"),createjs.Sound.registerSound("./sounds/start_race.mp3","start_race"),createjs.Sound.registerSound("./sounds/photo.mp3","photo")),b+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("but_credits",
"./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("arrow_left","./sprites/arrow_left.png");s_oSpriteLibrary.addSprite("arrow_right","./sprites/arrow_right.png");s_oSpriteLibrary.addSprite("fiche_0",
"./sprites/fiche_0.png");s_oSpriteLibrary.addSprite("fiche_1","./sprites/fiche_1.png");s_oSpriteLibrary.addSprite("fiche_2","./sprites/fiche_2.png");s_oSpriteLibrary.addSprite("fiche_3","./sprites/fiche_3.png");s_oSpriteLibrary.addSprite("fiche_4","./sprites/fiche_4.png");s_oSpriteLibrary.addSprite("fiche_5","./sprites/fiche_5.png");s_oSpriteLibrary.addSprite("bg_bet_panel","./sprites/bg_bet_panel.jpg");s_oSpriteLibrary.addSprite("money_panel","./sprites/money_panel.png");s_oSpriteLibrary.addSprite("simple_bet_panel",
"./sprites/simple_bet_panel.png");s_oSpriteLibrary.addSprite("forecast_panel","./sprites/forecast_panel.png");s_oSpriteLibrary.addSprite("bet_place","./sprites/bet_place.png");s_oSpriteLibrary.addSprite("fiche_highlight","./sprites/fiche_highlight.png");s_oSpriteLibrary.addSprite("odd_bg","./sprites/odd_bg.png");s_oSpriteLibrary.addSprite("rank_panel","./sprites/rank_panel.png");s_oSpriteLibrary.addSprite("panel_arrival","./sprites/panel_arrival.png");s_oSpriteLibrary.addSprite("bibs","./sprites/bibs.png");
s_oSpriteLibrary.addSprite("but_skip","./sprites/but_skip.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("but_start_race","./sprites/but_start_race.png");s_oSpriteLibrary.addSprite("but_clear_bet","./sprites/but_clear_bet.png");s_oSpriteLibrary.addSprite("fiche_panel","./sprites/fiche_panel.png");s_oSpriteLibrary.addSprite("fill_bar","./sprites/fill_bar.png");s_oSpriteLibrary.addSprite("win_panel","./sprites/win_panel.png");s_oSpriteLibrary.addSprite("lose_panel",
"./sprites/lose_panel.png");for(var c=0;c<NUM_GREYHOUNDS;c++)s_oSpriteLibrary.addSprite("bib_gui_"+c,"./sprites/bib_gui_"+c+".png"),s_oSpriteLibrary.addSprite("greyhound_"+(c+1),"./sprites/greyhound_"+(c+1)+".png");for(c=0;c<NUM_TRACK_BG;c++)s_oSpriteLibrary.addSprite("bg_track_"+c,"./sprites/bg_track/bg_track_"+c+".jpg");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){d++;k.refreshLoader(Math.floor(d/b*100));d===b&&this._onRemovePreloader()};this._onAllImagesLoaded=
function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=function(){try{saveItem("ls_available","ok")}catch(h){s_bStorageAvailable=!1}k.unload();isIOS()||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}));this.gotoMenu()};this.gotoMenu=function(){new CMenu;c=STATE_MENU};this.gotoBetPanel=function(){new CBetPanel;c=STATE_BET_PANEL;$(s_oMain).trigger("start_session")};this.gotoGame=function(b){f=new CGame(b);
c=STATE_GAME};this.stopUpdate=function(){e=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();e=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(b){if(!1!==e){var a=(new Date).getTime();s_iTimeElaps=a-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=a;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=
1E3,s_iCntFps=0);c===STATE_GAME&&f.update();s_oStage.update(b)}};s_oMain=this;s_iCurMoney=a.money;s_iGameCash=a.game_cash;CHIP_VALUES=a.chip_values;MIN_BET=a.min_bet;MAX_BET=a.max_bet;WIN_OCCURRENCE=a.win_occurrence;AD_SHOW_COUNTER=a.num_levels_for_ads;SHOW_CREDITS=a.show_credits;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;NUM_CHIPS=CHIP_VALUES.length;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_bStorageAvailable=!0,s_iCurMoney,s_iGameCash,s_iAdCounter=0;
function CTextButton(a,e,d,b,c,k,f,h){var g,l,m,n,q,u,r,p;this._init=function(b,c,a,d,e,f,k){g=[];l=[];var h=createBitmap(a),t=Math.ceil(k/20);q=new createjs.Text(d,k+"px "+e,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var x=q.getBounds();q.x=a.width/2+t;q.y=Math.floor(a.height/2)+x.height/3+t;n=new createjs.Text(d,k+"px "+e,f);n.textAlign="center";n.textBaseline="alphabetic";x=n.getBounds();n.x=a.width/2;n.y=Math.floor(a.height/2)+x.height/3;m=new createjs.Container;m.x=b;m.y=c;m.regX=
a.width/2;m.regY=a.height/2;m.addChild(h,q,n);p.addChild(m);s_bMobile||(m.cursor="pointer");this._initListener()};this.unload=function(){m.off("mousedown",u);m.off("pressup",r);p.removeChild(m)};this.setVisible=function(b){m.visible=b};this._initListener=function(){u=m.on("mousedown",this.buttonDown);r=m.on("pressup",this.buttonRelease)};this.addEventListener=function(b,c,a){g[b]=c;l[b]=a};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;playSound("click",1,0);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};
this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setTextPosition=function(b){n.y=b;q.y=b+2};this.setPosition=function(b,c){m.x=b;m.y=c};this.setX=function(b){m.x=b};this.setY=function(b){m.y=b};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};p=h;this._init(a,e,d,b,c,k,f);return this}
function CToggle(a,e,d,b,c){var k,f,h,g,l,m,n;this._init=function(b,c,a,d,e){n=void 0!==e?e:s_oStage;f=[];h=[];e=new createjs.SpriteSheet({images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{state_true:[0],state_false:[1]}});k=d;g=createSprite(e,"state_"+k,a.width/2/2,a.height/2,a.width/2,a.height);g.x=b;g.y=c;g.stop();s_bMobile||(g.cursor="pointer");n.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",l);g.off("pressup",m);n.removeChild(g)};
this._initListener=function(){l=g.on("mousedown",this.buttonDown);m=g.on("pressup",this.buttonRelease)};this.addEventListener=function(b,c,a){f[b]=c;h[b]=a};this.setCursorType=function(b){g.cursor=b};this.setActive=function(b){k=b;g.gotoAndStop("state_"+k)};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;playSound("click",1,0);k=!k;g.gotoAndStop("state_"+k);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(h[ON_MOUSE_UP],k)};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};
this.setPosition=function(b,c){g.x=b;g.y=c};this._init(a,e,d,b,c)}
function CGfxButton(a,e,d,b){var c,k,f,h,g,l,m,n,q,u=!1,r;this._init=function(b,a,d){c=[];k=[];h=[];f=createBitmap(d);f.x=b;f.y=a;l=g=1;f.regX=d.width/2;f.regY=d.height/2;s_bMobile||(f.cursor="pointer");r.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",n);f.off("pressup",q);r.removeChild(f)};this.setVisible=function(b){f.visible=b};this.setCursorType=function(b){f.cursor=b};this._initListener=function(){n=f.on("mousedown",this.buttonDown);q=f.on("pressup",this.buttonRelease)};
this.addEventListener=function(b,a,d){c[b]=a;k[b]=d};this.addEventListenerWithParams=function(b,a,d,e){c[b]=a;k[b]=d;h[b]=e};this.buttonRelease=function(){u||(f.scaleX=0<g?g:-g,f.scaleY=l,playSound("click",1,0),c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(k[ON_MOUSE_UP],h[ON_MOUSE_UP]))};this.buttonDown=function(){u||(f.scaleX=0<g?.9*g:.9*-g,f.scaleY=.9*l,c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN],h[ON_MOUSE_DOWN]))};this.rotation=function(b){f.rotation=b};this.getButton=function(){return f};
this.setPosition=function(b,c){f.x=b;f.y=c};this.setX=function(b){f.x=b};this.setY=function(b){f.y=b};this.getButtonImage=function(){return f};this.block=function(b){u=b;f.scaleX=g;f.scaleY=l};this.setScaleX=function(b){g=f.scaleX=b};this.setScale=function(b){l=g=b;f.scaleX=f.scaleY=b};this.getX=function(){return f.x};this.getY=function(){return f.y};this.pulseAnimation=function(){createjs.Tween.get(f).to({scaleX:.9*g,scaleY:.9*l},850,createjs.Ease.quadOut).to({scaleX:g,scaleY:l},650,createjs.Ease.quadIn).call(function(){m.pulseAnimation()})};
this.trebleAnimation=function(){createjs.Tween.get(f).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){m.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(f)};r=void 0!==b?b:s_oStage;this._init(a,e,d);m=this;return this}
function CMenu(){var a,e,d,b,c,k,f,h,g,l,m,n,q,u,r,p=null,t,v=null,w=null,x;this._init=function(){m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(m);var p=s_oSpriteLibrary.getSprite("but_play");g=CANVAS_WIDTH/2;l=CANVAS_HEIGHT-p.height/2-10;n=new CGfxButton(g,l,p);n.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);p=s_oSpriteLibrary.getSprite("but_credits");SHOW_CREDITS?(c=10+p.width/2,k=p.height/2+10,r=new CGfxButton(c,k,p),r.addEventListener(ON_MOUSE_UP,this._onCredits,
this),d=c+p.width+10,b=k):(d=10+p.width/2,b=p.height/2+10);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p=s_oSpriteLibrary.getSprite("audio_icon"),f=CANVAS_WIDTH-p.width/4-10,h=p.height/2+10,u=new CToggle(f,h,p,s_bAudioActive,s_oStage),u.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);var p=window.document,z=p.documentElement;v=z.requestFullscreen||z.mozRequestFullScreen||z.webkitRequestFullScreen||z.msRequestFullscreen;w=p.exitFullscreen||p.mozCancelFullScreen||p.webkitExitFullscreen||p.msExitFullscreen;
!1===ENABLE_FULLSCREEN&&(v=!1);v&&!1===inIframe()&&(p=s_oSpriteLibrary.getSprite("but_fullscreen"),t=new CToggle(d,b,p,s_bFullscreen,s_oStage),t.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));p=s_oSpriteLibrary.getSprite("logo_menu");a=CANVAS_WIDTH/2;e=10;x=createBitmap(p);x.regX=p.width/2;x.x=a;x.y=e;s_oStage.addChild(x);q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(q);createjs.Tween.get(q).to({alpha:0},1E3).call(function(){s_oStage.removeChild(q)});
this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){n.unload();n=null;SHOW_CREDITS&&r.unload();s_oStage.removeChild(m);m=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u.unload(),u=null;v&&!1===inIframe()&&t.unload();s_oMenu=null};this.refreshButtonPos=function(a,q){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||u.setPosition(f-a,h+q);v&&!1===inIframe()&&t.setPosition(d+a,b+q);n.setPosition(g,l-q);SHOW_CREDITS&&r.setPosition(c+a,k+q);null!==p&&p.refreshButtonPos(a,q);x.y=e+q};this.exitFromCredits=
function(){p=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCredits=function(){p=new CCreditsPanel};this._onButPlayRelease=function(){this.unload();s_oMain.gotoBetPanel();!isIOS()||null!==s_oSoundTrack||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}))};this._onFullscreenRelease=function(){s_bFullscreen?(w.call(window.document),s_bFullscreen=!1):(v.call(window.document.documentElement),
s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var e,d,b,c,k,f,h,g,l,m,n,q=null,u,r,p,t,v,w;this._init=function(){c=b=e=!1;h=f=0;n=s_oGameSettings.getAllGreyhoundNames();setVolume(s_oSoundTrack,0);s_oTweenController=new CTweenController;u=new createjs.Container;s_oStage.addChild(u);p=new CTrackBg(u);v=new CRankingGui(n,s_oStage);w=new CArrivalPanel(CANVAS_WIDTH,240,s_oStage);t=new CInterface;this.generateFinalRank();this._prepareGreyHounds();r=new createjs.Shape;r.graphics.beginFill("white").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);
r.alpha=0;s_oStage.addChild(r);$(s_oMain).trigger("start_level",1);setTimeout(function(){s_oGame.startRace()},1E3);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){stopSound(q);t.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();s_oGame=null};this.refreshButtonPos=function(b,c){t.refreshButtonPos(b,c);v.refreshButtonPos(b,c)};this.pause=function(){e=!1;null!==q&&(q.paused=!0);for(var b=0;b<NUM_GREYHOUNDS;b++)m[b].pauseAnim()};this.unpause=function(){e=!0;null!==
q&&(q.paused=!1);for(var b=0;b<NUM_GREYHOUNDS;b++)m[b].unpauseAnim()};this.onExit=function(){setVolume(s_oSoundTrack,1);s_oGame.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("share_event",[s_iCurMoney])};this.gotoBetPanel=function(){setVolume(s_oSoundTrack,1);s_oGame.unload();s_oMain.gotoBetPanel()};this.startRace=function(){q=playSound("start_race",1,0);t.blockExit(!1);e=!0};this.generateFinalRank=function(){s_oBetList.getMinWin()>
s_iGameCash?this._generateLosingResult():100*Math.random()<WIN_OCCURRENCE?this._generateWinResult():this._generateLosingResult()};this._generateWinResult=function(){d=!0;do{g=this._generateRandomRank();var b=s_oBetList.getTotWinWithCurRank(g);k=b.tot_win}while(k<=a);l=b.win_list;s_iCurMoney+=k;s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2));s_iGameCash-=k;s_iGameCash=parseFloat(s_iGameCash.toFixed(2))};this._generateLosingResult=function(){d=!1;do{g=this._generateRandomRank();var b=s_oBetList.getTotWinWithCurRank(g);
k=b.tot_win}while(k>a);l=b.win_list};this._generateRandomRank=function(){for(var b=[],c=s_oGameSettings.getGreyhoundPercentageArray();6>b.length;){var a=c[Math.floor(Math.random()*c.length)];b.unshift(a);for(var d=c.length-1;0<=d;)c[d]===a&&c.splice(d,1),d--}return b};this._prepareGreyHounds=function(){m=[];for(var b=s_oGameSettings.getRandomPath(),c=0;c<NUM_GREYHOUNDS;c++){var a=s_oGameSettings.getGreyhoundInfo(c),d=g.indexOf(c);m[c]=new CGreyhound(a.start,c+1,n[c],a.scale,b["place_"+(d+1)],u)}};
this.startGreyhounds=function(){for(var b=0;b<NUM_GREYHOUNDS;b++)m[b].startRace()};this.greyhoundPhotofinish=function(b,c){w.refreshRank(b,c);f++;4>f?(e=!1,h=TIME_CHECK_RANK,this._playFlashAnim()):6===f&&(d?t.showWinPanel(k,l,g):t.showLosePanel(g),stopSound(q),setVolume(s_oSoundTrack,1),$(s_oMain).trigger("save_score",s_iCurMoney))};this.checkGreyhoundArrival=function(){b=!0};this._playFlashAnim=function(){for(var b=0;b<NUM_GREYHOUNDS;b++)m[b].pauseAnim();playSound("photo",1,0);createjs.Tween.get(r).to({alpha:.8},
200).call(function(){var b=(new createjs.ColorMatrix).adjustSaturation(-100);u.filters=[new createjs.ColorMatrixFilter(b)];u.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c=!0;createjs.Tween.get(r).to({alpha:0},400).call(function(){s_oGame.restoreRaceAfterFlash()})})};this.restoreRaceAfterFlash=function(){setTimeout(function(){for(var b=0;b<NUM_GREYHOUNDS;b++)m[b].unpauseAnim();u.filters=[];u.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e=!0},1E3)};this._refreshRank=function(){for(var b=[],c=0;c<NUM_GREYHOUNDS;c++){var a=
m[c].getX();b[c]={index:c,x:a}}b.sort(this.compareXPos);v.refreshRank(b)};this.compareXPos=function(b,c){return b.x>c.x?-1:b.x<c.x?1:0};this.returnInBetPanel=function(){s_iAdCounter++;s_iAdCounter===AD_SHOW_COUNTER&&(s_iAdCounter=0,$(s_oMain).trigger("show_interlevel_ad"));s_oGame.gotoBetPanel()};this.update=function(){if(e){var a=p.update();v.refreshRadar(a-16);for(a=0;a<NUM_GREYHOUNDS;a++)m[a].update(b);c&&u.updateCache();h+=s_iTimeElaps;h>TIME_CHECK_RANK&&(h=0,this._refreshRank())}};s_oGame=this;
this._init()}var s_oGame=null,s_oTweenController;
function CInterface(){var a,e,d,b,c,k,f,h,g=null,l=null,m,n,q,u;this._init=function(){var r=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-r.width/2-10;e=r.height/2+10;m=new CGfxButton(a,e,r);m.block(!0);m.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(r=s_oSpriteLibrary.getSprite("audio_icon"),c=a-r.width/2-10,k=e,f=new CToggle(c,k,r,s_bAudioActive,s_oStage),f.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),d=c-r.width/2-10,b=k):(d=a-r.width-
10,b=e);var r=window.document,p=r.documentElement;g=p.requestFullscreen||p.mozRequestFullScreen||p.webkitRequestFullScreen||p.msRequestFullscreen;l=r.exitFullscreen||r.mozCancelFullScreen||r.webkitExitFullscreen||r.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(g=!1);g&&!1===inIframe()&&(r=s_oSpriteLibrary.getSprite("but_fullscreen"),h=new CToggle(d,b,r,s_bFullscreen,s_oStage),h.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));q=new CLosePanel(s_oStage);n=new CWinPanel(s_oStage);u=new CAreYouSurePanel(s_oStage)};
this.refreshButtonPos=function(l,n){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||f.setPosition(c-l,k+n);g&&!1===inIframe()&&h.setPosition(d-l,b+n);m.setPosition(a-l,e+n)};this.showWinPanel=function(b,c,a){n.show(b,c,a)};this.showLosePanel=function(b){q.show(b)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),f=null;g&&!1===inIframe()&&h.unload();n.unload();q.unload();s_oInterface=null};this.blockExit=function(b){m.block(b)};this._onExit=function(){s_oGame.pause();u.show()};
this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(l.call(window.document),s_bFullscreen=!1):(g.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CCreditsPanel(){var a,e,d,b,c,k,f,h,g,l;this._init=function(){l=new createjs.Container;s_oStage.addChild(l);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));l.addChild(a);k=new createjs.Shape;k.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);k.alpha=.01;g=k.on("click",this._onLogoButRelease);l.addChild(k);var m=s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(715,250,m,l);d.addEventListener(ON_MOUSE_UP,this.unload,this);c=new createjs.Text(TEXT_CREDITS_DEVELOPED,
"40px "+PRIMARY_FONT,"#000");c.textAlign="center";c.textBaseline="alphabetic";c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2-60;c.outline=4;l.addChild(c);b=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+PRIMARY_FONT,"#ffb400");b.textAlign="center";b.textBaseline="alphabetic";b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2-60;l.addChild(b);m=s_oSpriteLibrary.getSprite("logo_ctl");e=createBitmap(m);e.regX=m.width/2;e.regY=m.height/2;e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;l.addChild(e);h=new createjs.Text("www.codethislab.com",
"36px "+PRIMARY_FONT,"#000");h.textAlign="center";h.textBaseline="alphabetic";h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2+80;h.outline=4;l.addChild(h);f=new createjs.Text("www.codethislab.com","36px "+PRIMARY_FONT,"#ffb400");f.textAlign="center";f.textBaseline="alphabetic";f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2+80;l.addChild(f)};this.unload=function(){k.off("click",g);d.unload();d=null;s_oStage.removeChild(l);s_oMenu.exitFromCredits()};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en",
"_blank")};this._init()}
function CBetPanel(){var a,e,d,b,c,k,f,h,g,l,m,n,q,u,r,p,t,v;this._init=function(){f=c=0;g=[];v=new createjs.Container;s_oStage.addChild(v);var w=createBitmap(s_oSpriteLibrary.getSprite("bg_bet_panel"));v.addChild(w);w=s_oSpriteLibrary.getSprite("but_exit");d=CANVAS_WIDTH-w.width/2-10;b=w.height/2+10;r=new CGfxButton(d,b,w,v);r.addEventListener(ON_MOUSE_UP,this.onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var x=s_oSpriteLibrary.getSprite("audio_icon");a=d-w.width-10;e=x.height/2+10;
p=new CToggle(a,e,x,s_bAudioActive,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}w=s_oSpriteLibrary.getSprite("simple_bet_panel");BET_PANEL_WIDTH=w.width;BET_PANEL_HEIGHT=w.height;t=new createjs.Container;t.x=BET_PANEL_X;t.y=BET_PANEL_Y;v.addChild(t);h=[];h[0]=new CSimpleBetPanel(0,0,t);h[1]=new CForecastPanel(BET_PANEL_WIDTH,0,t);q=new CChipPanel(800,263,v);l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(BET_PANEL_X+6,BET_PANEL_Y,BET_PANEL_WIDTH-
12,BET_PANEL_HEIGHT);v.addChild(l);t.mask=l;k=0;m=new CGfxButton(BET_PANEL_X+7,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("arrow_left"),v);m.addEventListener(ON_MOUSE_UP,this._onArrowLeft,this);n=new CGfxButton(BET_PANEL_X+w.width-7,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("arrow_right"),v);n.addEventListener(ON_MOUSE_UP,this._onArrowRight,this);u=new CMsgBox;s_oBetList.reset();this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){m.unload();n.unload();r.unload();!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||p.unload();u.unload();q.unload();for(var b=0;b<h.length;b++)h[b].unload();s_oStage.removeAllChildren()};this.refreshButtonPos=function(c,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(a-c,e+f);r.setPosition(d-c,b+f)};this.setChipSelected=function(b){f=b};this.setSimpleBet=function(b,a,d,e){if(c+d>MAX_BET)return u.show(TEXT_ERR_MAX_BET),!1;if(d>s_iCurMoney)return u.show(TEXT_NO_MONEY),!1;s_oBetList.addSimpleBet(b,a,d);c+=d;c=Number(c.toFixed(2));s_iCurMoney-=d;s_iCurMoney=
parseFloat(s_iCurMoney.toFixed(2));s_iGameCash+=d;s_iGameCash=parseFloat(s_iGameCash.toFixed(2));q.refreshMoney();q.refreshBet(c);g.push(e);return!0};this.setForecastBet=function(b,a,d,e){if(c+d>MAX_BET)return u.show(TEXT_ERR_MAX_BET),!1;if(d>s_iCurMoney)return u.show(TEXT_NO_MONEY),!1;s_oBetList.addForecastBet(b,a,d);c+=d;c=Number(c.toFixed(2));s_iCurMoney-=d;s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2));s_iGameCash+=d;s_iGameCash=parseFloat(s_iGameCash.toFixed(2));q.refreshMoney();q.refreshBet(c);
g.push(e);return!0};this.refreshPagePos=function(b,c){t.x=BET_PANEL_X;h[k].setX(0);h[b].setX(c)};this.clearBet=function(){for(var b=0;b<g.length;b++)g[b].clearBet();s_iCurMoney+=c;s_iCurMoney=parseFloat(s_iCurMoney.toFixed(2));s_iGameCash-=c;s_iGameCash=parseFloat(s_iGameCash.toFixed());c=0;h[0].clearBet()};this._onArrowLeft=function(){var b=k;k++;k===h.length&&(k=0,b=h.length-1);h[k].setX(BET_PANEL_WIDTH);createjs.Tween.get(t).to({x:-BET_PANEL_WIDTH+BET_PANEL_X},500,createjs.Ease.cubicOut).call(function(){s_oBetPanel.refreshPagePos(b,
BET_PANEL_WIDTH)})};this._onArrowRight=function(){var b=k;k--;0>k&&(k=h.length-1);h[k].setX(-BET_PANEL_WIDTH);createjs.Tween.get(t).to({x:BET_PANEL_X+BET_PANEL_WIDTH},500,createjs.Ease.cubicOut).call(function(){s_oBetPanel.refreshPagePos(b,-BET_PANEL_WIDTH)})};this.onStartExit=function(){c<MIN_BET?u.show(TEXT_ERR_MIN_BET):(this.unload(),s_oMain.gotoGame(c))};this.onExit=function(){this.unload();s_oMain.gotoMenu()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=
!s_bAudioActive};this.getChipSelected=function(){return f};s_oBetPanel=this;this._init()}var s_oBetPanel=null;
function CChipPanel(a,e,d){var b,c,k,f,h,g,l,m,n,q;this._init=function(b,c){n=new createjs.Container;n.x=b;n.y=c;q.addChild(n);m=new CTextButton(73,2,s_oSpriteLibrary.getSprite("but_clear_bet"),TEXT_CLEAR_BET,PRIMARY_FONT,"#fff",24,n);m.addEventListener(ON_MOUSE_UP,this._onClearBet,this);var a=s_oSpriteLibrary.getSprite("money_panel"),d=createBitmap(s_oSpriteLibrary.getSprite("money_panel"));d.regX=a.width/2;d.x=73;d.y=22;n.addChild(d);f=new createjs.Text(TEXT_MIN_BET+": "+MIN_BET+TEXT_CURRENCY,"14px "+
SECONDARY_FONT,"#ffde00");f.textAlign="center";f.textBaseline="alphabetic";f.x=73;f.y=44;n.addChild(f);h=new createjs.Text(TEXT_MAX_BET+": "+MAX_BET+TEXT_CURRENCY,"14px "+SECONDARY_FONT,"#ffde00");h.textAlign="center";h.textBaseline="alphabetic";h.x=73;h.y=56;n.addChild(h);d=createBitmap(s_oSpriteLibrary.getSprite("money_panel"));d.regX=a.width/2;d.x=73;d.y=72;n.addChild(d);d=new createjs.Text(TEXT_BET,"11px "+TERTIARY_FONT,"#fff");d.textAlign="left";d.textBaseline="alphabetic";d.x=3;d.y=85;n.addChild(d);
g=new createjs.Text("0"+TEXT_CURRENCY,"26px "+SECONDARY_FONT,"#ffde00");g.textAlign="center";g.textBaseline="alphabetic";g.x=73;g.y=104;n.addChild(g);d=createBitmap(a);d.regX=a.width/2;d.x=73;d.y=122;n.addChild(d);d=new createjs.Text(TEXT_MONEY,"11px "+TERTIARY_FONT,"#fff");d.textAlign="left";d.textBaseline="alphabetic";d.x=3;d.y=136;n.addChild(d);k=new createjs.Text(s_iCurMoney+TEXT_CURRENCY,"26px "+SECONDARY_FONT,"#ffde00");k.textAlign="center";k.textBaseline="alphabetic";k.x=73;k.y=154;n.addChild(k);
this._initChips();l=new CButStartRace(73,304,s_oSpriteLibrary.getSprite("but_start_race"),TEXT_START_RACE,"#fff",24,n);l.addEventListener(ON_MOUSE_UP,this._onStartRace,this)};this.unload=function(){for(var c=0;c<b;c++)b[c].unload();l.unload()};this._initChips=function(){var a=createBitmap(s_oSpriteLibrary.getSprite("fiche_panel"));a.x=0;a.y=170;n.addChild(a);a=[{x:25,y:198},{x:76,y:198},{x:124,y:198},{x:25,y:242},{x:76,y:242},{x:124,y:242}];b=[];for(var d=0;d<NUM_CHIPS;d++){var e=s_oSpriteLibrary.getSprite("fiche_"+
d);b[d]=new CGfxButton(a[d].x,a[d].y,e,n);b[d].addEventListenerWithParams(ON_MOUSE_UP,this._onFicheClicked,this,d)}a=s_oSpriteLibrary.getSprite("fiche_highlight");c=createBitmap(a);c.regX=a.width/2;c.regY=a.height/2;c.x=b[0].getX()-1;c.y=b[0].getY()-1;n.addChild(c)};this.refreshMoney=function(){k.text=s_iCurMoney+TEXT_CURRENCY};this.refreshBet=function(b){g.text=b+TEXT_CURRENCY};this._onStartRace=function(){s_oBetPanel.onStartExit()};this._onClearBet=function(){s_oBetPanel.clearBet()};this._onFicheClicked=
function(a){c.x=b[a].getX()-1;c.y=b[a].getY()-1;s_oBetPanel.setChipSelected(a)};q=d;this._init(a,e)}
function CSimpleBetPanel(a,e,d){var b,c,k,f,h,g;this._init=function(b,c){h=new createjs.Container;h.x=b;h.y=c;g.addChild(h);var a=createBitmap(s_oSpriteLibrary.getSprite("simple_bet_panel"));h.addChild(a);a=new createjs.Text(TEXT_TRAP,"20px "+PRIMARY_FONT,"#fff");a.textAlign="center";a.textBaseline="alphabetic";a.x=56;a.y=24;h.addChild(a);a=new createjs.Text(TEXT_GREYHOUND_NAME,"20px "+PRIMARY_FONT,"#fff");a.textAlign="center";a.textBaseline="alphabetic";a.x=180;a.y=24;h.addChild(a);a=new createjs.Text(TEXT_WINS,
"20px "+PRIMARY_FONT,"#fff");a.textAlign="center";a.textBaseline="alphabetic";a.x=360;a.y=24;h.addChild(a);a=new createjs.Text(TEXT_PLACE,"20px "+PRIMARY_FONT,"#fff");a.textAlign="center";a.textBaseline="alphabetic";a.x=500;a.y=24;h.addChild(a);a=new createjs.Text(TEXT_SHOW,"20px "+PRIMARY_FONT,"#fff");a.textAlign="center";a.textBaseline="alphabetic";a.x=630;a.y=24;h.addChild(a);for(var a=s_oSpriteLibrary.getSprite("bibs"),d=new createjs.SpriteSheet({images:[a],frames:{width:a.width/3,height:a.height/
2},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}}),e=38,f=0;f<NUM_GREYHOUNDS;f++){var k=createSprite(d,"bib_"+f,0,0,a.width/3,a.height/2);k.x=28;k.y=e;h.addChild(k);e+=a.height/2+11}this._initGreyhoundInfos();this._initBetPlaces()};this._initGreyhoundInfos=function(){var a=s_oGameSettings.getAllGreyhoundNames();b=[];for(var c=104,d=0;d<NUM_GREYHOUNDS;d++){var e={framerate:40,images:[s_oSpriteLibrary.getSprite("greyhound_"+(d+1))],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,
regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[0,0],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}},e=new createjs.SpriteSheet(e),e=createSprite(e,"idle",GREYHOUND_WIDTH/2,GREYHOUND_HEIGHT,GREYHOUND_WIDTH,GREYHOUND_HEIGHT);e.x=150;e.y=c;e.scaleX=e.scaleY=.5;h.addChild(e);b.push(e);e=new createjs.Text(a[d].toUpperCase(),"14px "+TERTIARY_FONT,"#fff");e.textAlign="right";e.textBaseline="alphabetic";e.x=286;e.y=c-10;h.addChild(e);c+=67}};this._initBetPlaces=
function(){k=[];f=[];c=[];for(var b=66,a=s_oSpriteLibrary.getSprite("bet_place"),d=0;d<NUM_GREYHOUNDS;d++){var e=new createjs.Text(s_oGameSettings.getOddWin(d),"20px "+TERTIARY_FONT,"#fff");e.textAlign="center";e.textBaseline="middle";e.x=325;e.y=b;h.addChild(e);e=new CButBet(e.x+60,b,a,.7,h);e.addEventListenerWithParams(ON_MOUSE_UP,this._onWinClicked,this,d);c.push(e);e=new createjs.Text(s_oGameSettings.getOddPlace(d),"20px "+TERTIARY_FONT,"#fff");e.textAlign="center";e.textBaseline="middle";e.x=
465;e.y=b;h.addChild(e);e=new CButBet(e.x+60,b,a,.7,h);e.addEventListenerWithParams(ON_MOUSE_UP,this._onPlaceClicked,this,d);k.push(e);e=new createjs.Text(s_oGameSettings.getOddShow(d),"20px "+TERTIARY_FONT,"#fff");e.textAlign="center";e.textBaseline="middle";e.x=593;e.y=b;h.addChild(e);e=new CButBet(e.x+60,b,a,.7,h);e.addEventListenerWithParams(ON_MOUSE_UP,this._onShowClicked,this,d);f.push(e);b+=67}};this.unload=function(){for(var b=0;b<k.length;b++)c[b].unload(),f[b].unload(),k[b].unload()};this.setX=
function(b){h.x=b};this.clearBet=function(){for(var a=0;a<b.length;a++)b[a].gotoAndStop("idle")};this._onWinClicked=function(a){var d=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(a,1,d,c[a])&&(c[a].increaseBet(d),b[a].gotoAndPlay("anim"))};this._onPlaceClicked=function(a){var c=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setSimpleBet(a,2,c,k[a])&&(k[a].increaseBet(c),b[a].gotoAndPlay("anim"))};this._onShowClicked=function(a){var c=CHIP_VALUES[s_oBetPanel.getChipSelected()];
s_oBetPanel.setSimpleBet(a,3,c,f[a])&&(f[a].increaseBet(c),b[a].gotoAndPlay("anim"))};this.getContainer=function(){return h};g=d;this._init(a,e)}
function CForecastPanel(a,e,d){var b,c,k;this._init=function(){c=new createjs.Container;c.x=a;c.y=e;k.addChild(c);var b=createBitmap(s_oSpriteLibrary.getSprite("forecast_panel"));c.addChild(b);this._initForecastBets()};this.unload=function(){for(var a in b)-1<a.indexOf("forecast_")&&b[a].unload()};this._initForecastBets=function(){b=[];for(var a=[{x:26,y:10},{x:256,y:10},{x:486,y:10},{x:26,y:225},{x:256,y:225},{x:486,y:225}],c=0;c<NUM_GREYHOUNDS;c++)this._placeForecastBetForGreyhound(c,a[c].x,a[c].y)};
this._placeForecastBetForGreyhound=function(a,d,e){for(var f=s_oSpriteLibrary.getSprite("odd_bg"),k=s_oSpriteLibrary.getSprite("bet_place"),g=s_oSpriteLibrary.getSprite("bibs"),h=g.width/3,u=g.height/2,g=new createjs.SpriteSheet({images:[g],frames:{width:h,height:u},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}}),r=0;r<NUM_GREYHOUNDS;r++)if(r!==a){var p=createSprite(g,"bib_"+a,0,0,h,u);p.x=d;p.y=e;p.scaleX=p.scaleY=.65;c.addChild(p);var t=new createjs.Text("X","12px "+PRIMARY_FONT,
"#fff");t.textAlign="center";t.textBaseline="middle";t.x=d+.65*h+10;t.y=e+.65*u/2;c.addChild(t);var v=createSprite(g,"bib_"+r,0,0,h/3,u/2);v.x=t.x+10;v.y=p.y;v.scaleX=v.scaleY=.65;c.addChild(v);t=createBitmap(f);t.x=v.x+.65*h+10;t.y=p.y+2;c.addChild(t);p=new createjs.Text(s_oGameSettings.getForecastOdd(a,r),"18px "+PRIMARY_FONT,"#fff");p.textAlign="center";p.textBaseline="alphabetic";p.x=t.x+f.width/2;p.y=t.y+f.height/2+6;c.addChild(p);p=new CButBet(t.x+f.width+.72*k.width/2+5,t.y+.72*k.height/2,
k,.45,c);p.setScale(.72);p.addEventListenerWithParams(ON_MOUSE_UP,this._onForecastClicked,this,{first:a,second:r});b["forecast_"+a+"_"+r]=p;e+=.65*u+5}};this.setX=function(b){c.x=b};this._onForecastClicked=function(a){var c=CHIP_VALUES[s_oBetPanel.getChipSelected()];s_oBetPanel.setForecastBet(a.first,a.second,c,b["forecast_"+a.first+"_"+a.second])&&b["forecast_"+a.first+"_"+a.second].increaseBet(c)};k=d;this._init(a,e)}
function CBetList(){var a,e,d;this._init=function(){this.reset()};this.reset=function(){a=[];for(var b=0;b<NUM_GREYHOUNDS;b++)a[b]=[],a[b].place_1=0,a[b].place_2=0,a[b].place_3=0;e=[];for(b=0;b<NUM_GREYHOUNDS;b++){e[b]=[];for(var c=0;c<NUM_GREYHOUNDS;c++)e[b][c]=0}d=[]};this.addSimpleBet=function(b,c,e){a[b]["place_"+c]+=e;var f=0;switch(c){case 1:f=e*s_oGameSettings.getOddWin(b);break;case 2:f=e*s_oGameSettings.getOddPlace(b);break;case 3:f=e*s_oGameSettings.getOddShow(b)}d.push({type_bet:"simple",
greyhounds:[{index:b,place:c}],bet:e,win:f})};this.addForecastBet=function(b,a,k){e[b][a]+=k;d.push({type_bet:"forecast",greyhounds:[{index:b,place:1},{index:a,place:2}],bet:k,win:k*s_oGameSettings.getForecastOdd(b,a)})};this.getMinWin=function(){if(0<d.length){for(var b=d[0].win,a=1;a<d.length;a++)b>d[a].win&&(b=d[a].win);return b}return 0};this.getTotWinWithCurRank=function(b){var c=0,d=[];0<a[b[0]].place_1&&(c+=a[b[0]].place_1*s_oGameSettings.getOddWin(b[0]),c=parseFloat(c.toFixed(2)),d.push({win:c,
greyhounds:b[0],bet:a[b[0]].place_1,type:"win"}));0<a[b[0]].place_2&&(c+=a[b[0]].place_2*s_oGameSettings.getOddPlace(b[0]),c=parseFloat(c.toFixed(2)),d.push({win:c,greyhounds:b[0],bet:a[b[0]].place_2,type:"place"}));0<a[b[1]].place_2&&(c+=a[b[1]].place_2*s_oGameSettings.getOddPlace(b[1]),c=parseFloat(c.toFixed(2)),d.push({win:c,greyhounds:b[1],bet:a[b[1]].place_2,type:"place"}));0<a[b[0]].place_3&&(c+=a[b[0]].place_3*parseFloat(s_oGameSettings.getOddShow(b[0])),c=parseFloat(c.toFixed(2)),d.push({win:c,
greyhounds:b[0],bet:a[b[0]].place_3,type:"show"}));0<a[b[1]].place_3&&(c+=a[b[1]].place_3*s_oGameSettings.getOddShow(b[1]),c=parseFloat(c.toFixed(2)),d.push({win:c,greyhounds:b[1],bet:a[b[1]].place_3,type:"show"}));0<a[b[2]].place_3&&(c+=a[b[2]].place_3*s_oGameSettings.getOddShow(b[2]),c=parseFloat(c.toFixed(2)),d.push({win:c,greyhounds:b[2],bet:a[b[2]].place_3,type:"show"}));0<e[b[0]][b[1]]&&(c+=e[b[0]][b[1]]*s_oGameSettings.getForecastOdd(b[0],b[1]),c=parseFloat(c.toFixed(2)),d.push({win:c,greyhounds:[b[0],
b[1]],bet:e[b[0]][b[1]],type:"forecast"}));return{tot_win:c,win_list:d}};s_oBetList=this;this._init()}var s_oBetList=null;
function CFichesController(a,e){var d,b,c,k,f,h,g,l,m,n,q,u,r;this._init=function(a){k=a;m=new createjs.Container;r.addChild(m);h=new CVector2;h.set(m.x,m.y);n=new createjs.Container;r.addChild(n);a*=18;u=new createjs.Text("",a+"px "+TERTIARY_FONT,"#000");u.textAlign="center";n.addChild(u);q=new createjs.Text("",a+"px "+TERTIARY_FONT,"#fff");q.textAlign="center";n.addChild(q);c=f=b=0;d=!1};this.addEventListener=function(b,a,c){};this.reset=function(){d=!1;c=0;m.removeAllChildren();m.x=h.getX();m.y=
h.getY();u.text="";q.text=""};this.setPrevValue=function(b){f=b};this.refreshFiches=function(b,d,e){b=b.sortOn("value","index");for(var f=d,g=e,h=c=0,l=0;l<b.length;l++){var n=s_oSpriteLibrary.getSprite("fiche_"+b[l].index),p=createBitmap(n);p.regX=n.width/2;p.regY=n.height/2;p.scaleX=a;p.scaleY=a;m.addChild(p);p.x=f;p.y=g;g-=5;h++;9<h&&(h=0,f+=FICHE_WIDTH,g=e);c+=b[l].value}playSound("chip",1,0);q.x=d;q.y=e+25*k;q.text=c.toFixed(2)+TEXT_CURRENCY;u.x=d+2;u.y=e+27*k;u.text=c.toFixed(2)+TEXT_CURRENCY};
this.createFichesPile=function(b,a,c){this.reset();var d=CHIP_VALUES,e=[];do{for(var f=d[d.length-1],g=d.length-1;f>b;)g--,f=d[g];for(var g=Math.floor(b/f),h=0;h<g;h++)e.push({value:f,index:s_oGameSettings.getIndexForFiches(f)});f=Math.floor(b/f)===b/f?0:b%f;b=f.toFixed(2)}while(0<f);this.refreshFiches(e,a,c*k)};this.initMovement=function(b,a){f=c;g=new CVector2(m.x,m.y);l=new CVector2(b,a);q.text="";u.text="";d=!0};this.getValue=function(){return c};this.getPrevBet=function(){return f};this.update=
function(a){if(d)if(b+=a,b>TIME_FICHES_MOV)b=0,d=!1;else{a=easeInOutCubic(b,0,1,TIME_FICHES_MOV);var c=new CVector2,c=tweenVectors(g,l,a,c);m.x=c.getX();m.y=c.getY()}};r=e;this._init(a)}
function CButBet(a,e,d,b,c){var k,f,h,g,l,m,n,q,u,r,p=!1,t,v,w;this._init=function(b,a,c,d){k=0;f=[];h=[];l=[];v=new createjs.Container;v.x=b;v.y=a;w.addChild(v);g=createBitmap(c);n=m=1;g.regX=c.width/2;g.regY=c.height/2;s_bMobile||(g.cursor="pointer");v.addChild(g);this._initListener();t=new CFichesController(d,v)};this.unload=function(){g.off("mousedown",u);g.off("pressup",r);w.removeChild(v)};this.setVisible=function(b){g.visible=b};this.setCursorType=function(b){g.cursor=b};this._initListener=
function(){u=g.on("mousedown",this.buttonDown);r=g.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,c){f[b]=a;h[b]=c};this.addEventListenerWithParams=function(b,a,c,d){f[b]=a;h[b]=c;l[b]=d};this.buttonRelease=function(){p||(g.scaleX=0<m?m:-m,g.scaleY=n,playSound("chip",1,0),f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(h[ON_MOUSE_UP],l[ON_MOUSE_UP]))};this.buttonDown=function(){p||(g.scaleX=0<m?.9*m:.9*-m,g.scaleY=.9*n,f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN],l[ON_MOUSE_DOWN]))};
this.rotation=function(b){g.rotation=b};this.getButton=function(){return g};this.setPosition=function(b,a){g.x=b;g.y=a};this.setX=function(b){g.x=b};this.setY=function(b){g.y=b};this.getButtonImage=function(){return g};this.block=function(b){p=b;g.scaleX=m;g.scaleY=n};this.setScaleX=function(b){m=g.scaleX=b};this.setScale=function(b){n=m=b;g.scaleX=g.scaleY=b};this.increaseBet=function(b){k+=b;t.createFichesPile(k.toFixed(2),0,-4)};this.clearBet=function(){k=0;t.reset()};this.getX=function(){return g.x};
this.getY=function(){return g.y};this.pulseAnimation=function(){createjs.Tween.get(g).to({scaleX:.9*m,scaleY:.9*n},850,createjs.Ease.quadOut).to({scaleX:m,scaleY:n},650,createjs.Ease.quadIn).call(function(){q.pulseAnimation()})};this.trebleAnimation=function(){createjs.Tween.get(g).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){q.trebleAnimation()})};this.removeAllTweens=function(){createjs.Tween.removeTweens(g)};
w=void 0!==c?c:s_oStage;this._init(a,e,d,b);q=this;return this}
function CVector2(a,e){var d,b;this._init=function(a,e){d=a;b=e};this.add=function(a,e){d+=a;b+=e};this.addV=function(a){d+=a.getX();b+=a.getY()};this.scalarDivision=function(a){d/=a;b/=a};this.subV=function(a){d-=a.getX();b-=a.getY()};this.scalarProduct=function(a){d*=a;b*=a};this.invert=function(){d*=-1;b*=-1};this.dotProduct=function(a){return d*a.getX()+b*a.getY()};this.set=function(a,e){d=a;b=e};this.setV=function(a){d=a.getX();b=a.getY()};this.length=function(){return Math.sqrt(d*d+b*b)};this.length2=
function(){return d*d+b*b};this.normalize=function(){var a=this.length();0<a&&(d/=a,b/=a)};this.getNormalize=function(a){this.length();a.set(d,b);a.normalize()};this.rot90CCW=function(){var a=d;d=-b;b=a};this.rot90CW=function(){var a=d;d=b;b=-a};this.getRotCCW=function(a){a.set(d,b);a.rot90CCW()};this.getRotCW=function(a){a.set(d,b);a.rot90CW()};this.ceil=function(){d=Math.ceil(d);b=Math.ceil(b)};this.round=function(){d=Math.round(d);b=Math.round(b)};this.toString=function(){return"Vector2: "+d+", "+
b};this.print=function(){trace("Vector2: "+d+", "+b+"")};this.getX=function(){return d};this.getY=function(){return b};this._init(a,e)}
function CMsgBox(){var a,e,d,b;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d=new createjs.Text("","34px "+PRIMARY_FONT,"#000");d.x=CANVAS_WIDTH/2+2;d.y=CANVAS_HEIGHT/2-28;d.textAlign="center";d.lineWidth=400;d.textBaseline="middle";e=new createjs.Text("","34px "+PRIMARY_FONT,"#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-30;e.textAlign="center";e.lineWidth=400;e.textBaseline="middle";b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(a,d,e);s_oStage.addChild(b)};
this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(a){d.text=a;e.text=a;b.visible=!0;var c=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){c._initListener()});setTimeout(function(){c._onExit()},3E3)};this._onExit=function(){b.visible&&(b.off("mousedown"),b.visible=!1)};this._init();return this}
function CTrackBg(a){var e,d,b,c,k,f,h;this._init=function(){f=new createjs.Container;h.addChild(f);d=0;b=2;c=0;k=[];for(var a=0;a<NUM_TRACK_BG;a++){var l=createBitmap(s_oSpriteLibrary.getSprite("bg_track_"+a));0<a&&(l.visible=!1);f.addChild(l);k[a]=l}e=!0};this.update=function(){if(!e)return d;c++;c===b&&(c=0,d++,k[d].visible=!0,k[d-1].visible=!1,d===k.length-1?(e=!1,s_oGame.checkGreyhoundArrival()):17===d&&s_oGame.startGreyhounds());return d};h=a;this._init()}
function CGreyhound(a,e,d,b,c,k){var f,h,g,l,m,n,q,u,r,p,t,v;this._init=function(b,a,c,d,e){h=!1;g=a;q=0;u=ARRIVAL_X-GREYHOUND_WIDTH/2*d+30;r=c;p=e;a={framerate:40,images:[s_oSpriteLibrary.getSprite("greyhound_"+a)],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[0,0],anim:[0,21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}};a=new createjs.SpriteSheet(a);t=createSprite(a,"start",GREYHOUND_WIDTH/2,
GREYHOUND_HEIGHT,GREYHOUND_WIDTH,GREYHOUND_HEIGHT);t.x=b.x;t.y=b.y;t.scaleX=t.scaleY=d;t.alpha=0;v.addChild(t)};this.startRace=function(){var b="anim_"+(Math.floor(3*Math.random())+1);createjs.Tween.get(t).to({alpha:1},150).call(function(){t.gotoAndPlay(b)});n=t.x;l=0;m=p[q].frame;f=!0};this.pauseAnim=function(){t.paused=!0};this.unpauseAnim=function(){t.paused=!1};this.getX=function(){return t.x};this.update=function(b){if(f){l++;if(l>=m)q++,q<p.length?(l=0,m=p[q].frame,n=t.x):f=!1;else{var a=s_oTweenController.easeLinear(l,
0,1,m),a=s_oTweenController.tweenValue(n,p[q].x,a);t.x=a}b&&!h&&t.x>=u&&(h=!0,s_oGame.greyhoundPhotofinish(g-1,r))}};v=k;this._init(a,e,d,b,c)}
function CTweenController(){this.tweenValue=function(a,e,d){return a+d*(e-a)};this.easeLinear=function(a,e,d,b){return d*a/b+e};this.easeInCubic=function(a,e,d,b){b=(a/=b)*a*a;return e+d*b};this.easeBackInQuart=function(a,e,d,b){b=(a/=b)*a;return e+d*(2*b*b+2*b*a+-3*b)};this.easeInBack=function(a,e,d,b){return d*(a/=b)*a*(2.70158*a-1.70158)+e};this.easeOutCubic=function(a,e,d,b){return d*((a=a/b-1)*a*a+1)+e};this.getTrajectoryPoint=function(a,e){var d=new createjs.Point,b=(1-a)*(1-a),c=a*a;d.x=b*
e.start.x+2*(1-a)*a*e.traj.x+c*e.end.x;d.y=b*e.start.y+2*(1-a)*a*e.traj.y+c*e.end.y;return d}}
function CRankingGui(a,e){var d,b,c,k,f,h,g,l;this._init=function(a){var c=s_oSpriteLibrary.getSprite("rank_panel");d=CANVAS_HEIGHT-c.height+6;g=new createjs.Container;g.x=0;g.y=d;l.addChild(g);c=createBitmap(c);g.addChild(c);k=[];k[0]=new createjs.Point(780,48);k[1]=new createjs.Point(642,48);k[2]=new createjs.Point(504,48);k[3]=new createjs.Point(366,48);k[4]=new createjs.Point(228,48);k[5]=new createjs.Point(90,48);this._initBibs(a);b=2;f=createBitmap(s_oSpriteLibrary.getSprite("fill_bar"));f.x=
107;f.y=116;g.addChild(f);h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y-2,.01,10);g.addChild(h);f.mask=h;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(b,a){g.y=d-a};this._initBibs=function(b){c=[];for(var a=0;a<NUM_GREYHOUNDS;a++){var d=new createjs.Container;d.x=k[a].x;d.y=k[a].y;g.addChild(d);var e=createBitmap(s_oSpriteLibrary.getSprite("bib_gui_"+a));d.addChild(e);e=new createjs.Text(b[a].toUpperCase(),"12px "+PRIMARY_FONT,
"#fff");e.textAlign="right";e.textBaseline="alphabetic";e.x=50;e.y=10;d.addChild(e);c.push(d)}};this.refreshRank=function(b){for(var a=0;a<b.length;a++)createjs.Tween.get(c[b[a].index]).to({x:k[a].x},1E3,createjs.Ease.cubicOut)};this.refreshRadar=function(a){h.graphics.clear();h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y-2,b*a,10)};l=e;this._init(a)}
function CArrivalPanel(a,e,d){var b,c,k,f,h,g,l,m;this._init=function(a,d){f=0;c=a;k=d;l=new createjs.Container;l.x=c;l.y=k;m.addChild(l);var e=s_oSpriteLibrary.getSprite("panel_arrival"),e=createBitmap(e);l.addChild(e);var e=s_oSpriteLibrary.getSprite("bibs"),n=e.width/3,p=e.height/2,q=new createjs.SpriteSheet({images:[e],frames:{width:n,height:p},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});h=[];g=[];for(var v=6,w=0;w<NUM_GREYHOUNDS;w++){var x=createSprite(q,"bib_0",
0,0,n,p);x.x=10;x.y=v;x.visible=!1;x.scaleX=x.scaleY=.5;l.addChild(x);g.push(x);var y=new createjs.Text("","15px "+TERTIARY_FONT,"#fff");y.textAlign="left";y.textBaseline="alphabetic";y.x=x.x+.5*n+5;y.y=x.y+26;l.addChild(y);h.push(y);v+=.5*p+4}b=CANVAS_WIDTH-e.width};this.show=function(){createjs.Tween.get(l).to({x:b},500,createjs.Ease.cubicOut)};this.hide=function(){createjs.Tween.get(l).to({x:c},500,createjs.Ease.cubicOut)};this.refreshRank=function(b,a){h[f].text=a;g[f].gotoAndStop("bib_"+b);g[f].visible=
!0;0===f&&this.show();f++};m=d;this._init(a,e)}
function CWinPanel(a){var e,d,b,c,k,f,h;this._init=function(){f=new createjs.Container;f.visible=!1;h.addChild(f);var a=createBitmap(s_oSpriteLibrary.getSprite("win_panel"));f.addChild(a);a=s_oSpriteLibrary.getSprite("bibs");e=a.width/3;d=a.height/2;b=new createjs.SpriteSheet({images:[a],frames:{width:e,height:d},animations:{bib_0:[0],bib_1:[1],bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});k=new createjs.Text(TEXT_WIN,"30px "+SECONDARY_FONT,"#ffde00");k.textAlign="center";k.textBaseline="alphabetic";
k.x=CANVAS_WIDTH/2+70;k.y=476;k.lineHeight=42;f.addChild(k);c=new CGfxButton(700,491,s_oSpriteLibrary.getSprite("but_skip"),f);c.addEventListener(ON_MOUSE_UP,this.onSkip,this)};this.unload=function(){c.unload()};this.show=function(a,c,h){k.text=TEXT_WIN+"\n"+a+TEXT_CURRENCY;a=310;for(var g=0;3>g;g++){var l={images:[s_oSpriteLibrary.getSprite("greyhound_"+(h[g]+1))],frames:{width:GREYHOUND_WIDTH,height:GREYHOUND_HEIGHT,regX:GREYHOUND_WIDTH/2,regY:GREYHOUND_HEIGHT},animations:{idle:[18,18],anim:[0,
21],start:[22],anim_1:[5,21,"anim"],anim_2:[10,21,"anim"],anim_3:[15,21,"anim"]}},l=new createjs.SpriteSheet(l),l=createSprite(l,"idle",GREYHOUND_WIDTH/2,GREYHOUND_HEIGHT,GREYHOUND_WIDTH,GREYHOUND_HEIGHT);l.scaleX=l.scaleY=.5;l.x=CANVAS_WIDTH/2+150;l.y=a;f.addChild(l);a+=68}a=CANVAS_HEIGHT/2-150;for(h=0;h<c.length;h++){if("forecast"===c[h].type){var l=c[h].greyhounds,m=createSprite(b,"bib_"+l[0],0,0,e,d);m.x=280;m.y=a;m.scaleX=m.scaleY=.5;f.addChild(m);g=new createjs.Text("X","20px "+PRIMARY_FONT,
"#fff");g.textAlign="center";g.textBaseline="middle";g.x=m.x+.5*e+10;g.y=a+15;f.addChild(g);l=createSprite(b,"bib_"+l[1],0,0,e,d);l.x=g.x+10;l.y=a;l.scaleX=l.scaleY=.5;f.addChild(l);l=l.x+35}else m=createSprite(b,"bib_"+c[h].greyhounds,0,0,e,d),m.x=280,m.y=a,m.scaleX=m.scaleY=.5,f.addChild(m),l=m.x+35;g=new createjs.Text(c[h].type.toUpperCase(),"16px "+PRIMARY_FONT,"#ffb400");g.textAlign="left";g.textBaseline="alphabetic";g.x=l;g.y=a+22;f.addChild(g);l=new createjs.Text(TEXT_WIN+": "+c[h].win+TEXT_CURRENCY,
"16px "+PRIMARY_FONT,"#fff");l.textAlign="left";l.textBaseline="alphabetic";l.x=g.x+g.getBounds().width+10;l.y=a+22;f.addChild(l);a+=35}f.visible=!0;f.alpha=0;createjs.Tween.get(f).wait(1E3).to({alpha:1},500,createjs.Ease.cubicOut)};this.onSkip=function(){s_oGame.returnInBetPanel()};h=a;this._init()}
function CLosePanel(a){var e,d,b,c,k,f,h,g;this._init=function(){h=new createjs.Container;h.visible=!1;g.addChild(h);var a=createBitmap(s_oSpriteLibrary.getSprite("lose_panel"));h.addChild(a);a=new createjs.Text(TEXT_NO_WIN,"50px "+PRIMARY_FONT,"#fff");a.textAlign="center";a.textBaseline="alphabetic";a.x=CANVAS_WIDTH/2;a.y=285;h.addChild(a);a=s_oSpriteLibrary.getSprite("bibs");e=a.width/3;d=a.height/2;c=new createjs.SpriteSheet({images:[a],frames:{width:e,height:d},animations:{bib_0:[0],bib_1:[1],
bib_2:[2],bib_3:[3],bib_4:[4],bib_5:[5]}});b=[];a=createSprite(c,"bib_0",0,0,e,d);a.x=CANVAS_WIDTH/2-100-e/2;a.y=350;h.addChild(a);b.push(a);a=createSprite(c,"bib_0",0,0,e,d);a.x=CANVAS_WIDTH/2-e/2;a.y=350;h.addChild(a);b.push(a);a=createSprite(c,"bib_0",0,0,e,d);a.x=CANVAS_WIDTH/2+100-e/2;a.y=350;h.addChild(a);b.push(a);f=new createjs.Text(TEXT_WIN+": 0.00 "+TEXT_CURRENCY,"30px "+PRIMARY_FONT,"#fff");f.textAlign="center";f.textBaseline="alphabetic";f.x=CANVAS_WIDTH/2;f.y=510;h.addChild(f);k=new CGfxButton(700,
480,s_oSpriteLibrary.getSprite("but_skip"),h);k.addEventListener(ON_MOUSE_UP,this.onSkip,this)};this.unload=function(){k.unload()};this.show=function(a){for(var c=0;3>c;c++)b[c].gotoAndStop("bib_"+a[c]);h.visible=!0;h.alpha=0;createjs.Tween.get(h).wait(1E3).to({alpha:1},500,createjs.Ease.cubicOut)};this.onSkip=function(){s_oGame.returnInBetPanel()};g=a;this._init()}
function CButStartRace(a,e,d,b,c,k,f){var h,g,l,m,n,q,u,r;this._init=function(a,b,c,d,e,f){h=[];g=[];var k=createBitmap(c),p=Math.ceil(f/20);n=new createjs.Text(d,f+"px "+PRIMARY_FONT,"#000000");n.textAlign="center";n.textBaseline="alphabetic";n.x=c.width/2+p;n.y=28;m=new createjs.Text(d,f+"px "+PRIMARY_FONT,e);m.textAlign="center";m.textBaseline="alphabetic";m.x=c.width/2;m.y=26;l=new createjs.Container;l.x=a;l.y=b;l.regX=c.width/2;l.regY=c.height/2;l.addChild(k,n,m);r.addChild(l);s_bMobile||(l.cursor=
"pointer");this._initListener()};this.unload=function(){l.off("mousedown",q);l.off("pressup",u);r.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){q=l.on("mousedown",this.buttonDown);u=l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;g[a]=c};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;playSound("click",1,0);h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;h[ON_MOUSE_DOWN]&&
h[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.setTextPosition=function(a){m.y=a;n.y=a+2};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};r=f;this._init(a,e,d,b,c,k);return this}
function CAreYouSurePanel(a){var e,d,b,c;this._init=function(){b=new createjs.Container;b.visible=!1;c.addChild(b);_oBg=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));b.addChild(_oBg);var a=new createjs.Text(TEXT_ARE_YOU_SURE,"50px "+PRIMARY_FONT,"#fff");a.textAlign="center";a.textBaseline="alphabetic";a.x=CANVAS_WIDTH/2;a.y=300;a.lineWidth=400;a.lineHeight=48;b.addChild(a);e=new CGfxButton(CANVAS_WIDTH/2+170,460,s_oSpriteLibrary.getSprite("but_yes"),b);e.addEventListener(ON_MOUSE_UP,this._onReleaseYes,
this);d=new CGfxButton(CANVAS_WIDTH/2-170,460,s_oSpriteLibrary.getSprite("but_no"),b);d.addEventListener(ON_MOUSE_UP,this._onReleaseNo,this)};this.show=function(){b.visible=!0;b.alpha=0;createjs.Tween.get(b).to({alpha:1},500,createjs.Ease.cubicOut)};this._onReleaseYes=function(){s_oGame.onExit()};this._onReleaseNo=function(){b.visible=!1;s_oGame.unpause()};c=a;this._init(a)};
