(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var c=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var g=b.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var e=b.createElement("div");e.id="vpw-test-d";e.style.cssText="position:absolute;top:-1000px";e.innerHTML="<style>@media("+c+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";g.appendChild(e);d.insertBefore(g,b.head);
a=7==e["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(g)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function isIOS(){for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width");_checkOrientation(c,a);var b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),d=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,g;b<a?(g=a-b,b+=g,d+=CANVAS_WIDTH/CANVAS_HEIGHT*g):d<c&&(g=c-d,d+=g,b+=CANVAS_HEIGHT/CANVAS_WIDTH*g);g=a/2-b/2;var e=c/2-d/2,f=CANVAS_WIDTH/d;if(e*f<-EDGEBOARD_X||g*f<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
c/(CANVAS_WIDTH-2*EDGEBOARD_X)),d=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,g=(a-b)/2,e=(c-d)/2,f=CANVAS_WIDTH/d;s_iOffsetX=-1*e*f;s_iOffsetY=-1*g*f;0<=g&&(s_iOffsetY=0);0<=e&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oModeMenu&&s_oModeMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bMobile?($("#canvas").css("width",d+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=d,s_oStage.canvas.height=
b,s_oStage.scaleX=s_oStage.scaleY=Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT));0>g?$("#canvas").css("top",g+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",e+"px")}}
function _checkOrientation(a,c){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>c?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:b,volume:c}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,c){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=c}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(c)}
function createBitmap(a,c,b){var d=new createjs.Bitmap(a),g=new createjs.Shape;c&&b?g.graphics.beginFill("#fff").drawRect(0,0,c,b):g.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=g;return d}function createSprite(a,c,b,d,g,e){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,g,e);a.hitArea=c;return a}function pad(a,c,b){a+="";return a.length>=c?a:Array(c-a.length+1).join(b||"0")+a}
function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),d=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,d)}function tweenVectorsOnX(a,c,b){return a+b*(c-a)}function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}
function bubbleSort(a){var c;do{c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}function easeLinear(a,c,b,d){return b*a/d+c}function easeInQuad(a,c,b,d){return b*(a/=d)*a+c}function easeInSine(a,c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c}function easeInCubic(a,c,b,d){return b*(a/=d)*a*a+c}
function getTrajectoryPoint(a,c){var b=new createjs.Point,d=(1-a)*(1-a),g=a*a;b.x=d*c.start.x+2*(1-a)*a*c.traj.x+g*c.end.x;b.y=d*c.start.y+2*(1-a)*a*c.traj.y+g*c.end.y;return b}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=Math.floor(a-60*c);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,c){var b,d;b=getBounds(a,.9);d=getBounds(c,.98);return calculateIntersection(b,d)}
function calculateIntersection(a,c){var b,d,g,e,f,h,l,k;b=a.x+(g=a.width/2);d=a.y+(e=a.height/2);f=c.x+(h=c.width/2);l=c.y+(k=c.height/2);b=Math.abs(b-f)-(g+h);d=Math.abs(d-l)-(e+k);return 0>b&&0>d?(b=Math.min(Math.min(a.width,c.width),-b),d=Math.min(Math.min(a.height,c.height),-d),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:d,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,g=d.length,e,f;for(f=0;f<g;f++)e=getBounds(d[f],1),e.x<b.x&&(b.x=e.x),e.y<b.y&&(b.y=e.y),e.x+e.width>b.x2&&(b.x2=e.x+e.width),e.y+e.height>b.y2&&(b.y2=e.y+e.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var h,l;a instanceof createjs.Bitmap?
(g=a.sourceRect||a.image,f=g.width*c,h=g.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(g=a.spriteSheet.getFrame(a.currentFrame),f=g.rect.width,h=g.rect.height,d=g.regX,l=g.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);d=d||0;f=f||0;l=l||0;h=h||0;b.regX=d;b.regY=l;g=a.localToGlobal(0-d,0-l);e=a.localToGlobal(f-d,h-l);f=a.localToGlobal(f-d,0-l);d=a.localToGlobal(0-d,h-l);b.x=Math.min(Math.min(Math.min(g.x,
e.x),f.x),d.x);b.y=Math.min(Math.min(Math.min(g.y,e.y),f.y),d.y);b.width=Math.max(Math.max(Math.max(g.x,e.x),f.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(g.y,e.y),f.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,b,d;0<c;)d=Math.floor(Math.random()*c),c--,b=a[c],a[c]=a[d],a[d]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var d=c[b].split("=");if(d[0]==a)return d[1]}}
function CSpriteLibrary(){var a,c,b,d,g,e;this.init=function(f,h,l){b=c=0;d=f;g=h;e=l;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){g.call(e)};this._onSpriteLoaded=function(){d.call(e);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1280,CANVAS_HEIGHT=1920,EDGEBOARD_X=190,EDGEBOARD_Y=220,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="arialrounded",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,MODE_HUMAN=0,MODE_COMPUTER=1,EASY_MODE=0,MEDIUM_MODE=1,HARD_MODE=2,PAWN_BLACK=0,PAWN_WHITE=1,PAWN_NULL=-1,ALERT_TYPE_NOMOVES=0,ALERT_TYPE_STALL=1,BOARD_LENGTH=784,NUM_CELL=8,TOT_CELL=64,CELL_LENGTH=BOARD_LENGTH/NUM_CELL,
PAWN_SIZE=96,TIME_LOOP_WAIT=1E3,MIN_AI_THINKING=1E3,MAX_AI_THINKING=1500,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_GAMEOVER="WINS";TEXT_DRAW="DRAW";TEXT_THINKING="THINKING";TEXT_MODE="CHOOSE GAME MODE";TEXT_DIFFICULTY="DIFFICULTY";TEXT_AUDIO="MUTE/PLAY AUDIO";TEXT_COUNT="SHOW/HIDE FLIP NUMBER";TEXT_BLACK="BLACK";TEXT_WHITE="WHITE";TEXT_STALL="STALL";TEXT_NOMOVES="NO MORE MOVES";TEXT_HELP1="FLIP YOUR OPPONENT'S PIECES BY TRAPPING THEM BETWEEN TWO OF YOUR OWN.";TEXT_HELP2="YOUR AIM IS TO OWN MORE PIECES THAN YOUR OPPONENT WHEN THE GAME IS OVER.";
TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better?";
function CPreloader(){var a,c,b,d,g,e,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(e).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));f.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(h);d.x=CANVAS_WIDTH/2-h.width/2;d.y=CANVAS_HEIGHT-370;f.addChild(d);a=h.width;c=h.height;g=new createjs.Shape;g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,c);f.addChild(g);d.mask=
g;b=new createjs.Text("","30px Arial","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-325;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";f.addChild(b);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=0;f.addChild(e)};this.refreshLoader=function(e){b.text=e+"%";g.graphics.clear();e=Math.floor(e*a/100);g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,e,c)};this._init()}
function CMain(a){var c,b=0,d=0,g=STATE_LOADING,e,f,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;f=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){b++;f.refreshLoader(Math.floor(b/d*100));b===d&&this._onRemovePreloader()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/ot_soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/ot_game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/ot_click_cell.ogg","click_cell")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/ot_soundtrack.mp3",
"soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/ot_game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/ot_click_cell.mp3","click_cell")),createjs.Sound.registerSound("./sounds/ot_win.mp3","win"),d+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");
s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_mod_menu","./sprites/bg_mod_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("but_vs_man","./sprites/but_vs_man.png");s_oSpriteLibrary.addSprite("but_vs_pc","./sprites/but_vs_pc.png");s_oSpriteLibrary.addSprite("difficulty_panel","./sprites/difficulty_panel.png");s_oSpriteLibrary.addSprite("toggle_easy","./sprites/toggle_easy.png");s_oSpriteLibrary.addSprite("toggle_medium",
"./sprites/toggle_medium.png");s_oSpriteLibrary.addSprite("toggle_hard","./sprites/toggle_hard.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_settings","./sprites/but_settings.png");s_oSpriteLibrary.addSprite("white_chip","./sprites/chip_vertical_white.png");s_oSpriteLibrary.addSprite("black_chip","./sprites/chip_vertical_black.png");s_oSpriteLibrary.addSprite("bg_turn","./sprites/bg_turn.png");
s_oSpriteLibrary.addSprite("time_icon","./sprites/time_icon.png");s_oSpriteLibrary.addSprite("audio_icon_big","./sprites/audio_icon_big.png");s_oSpriteLibrary.addSprite("but_flip","./sprites/but_flip.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");s_oSpriteLibrary.addSprite("pawn","./sprites/pawn.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");d+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;f.refreshLoader(Math.floor(b/d*100));b===d&&this._onRemovePreloader()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=function(){f.unload();isIOS()||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}));this.gotoMenu()};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoModeMenu=function(){new CModeMenu;
g=STATE_MENU};this.gotoGame=function(a,b){s_iGameType=a;s_iDifficulty=b;switch(b){case EASY_MODE:s_bEdgeSensitive=s_bWeightSquares=!1;break;case MEDIUM_MODE:s_bWeightSquares=!1;s_bEdgeSensitive=!0;break;case HARD_MODE:s_bEdgeSensitive=s_bWeightSquares=!0}h=new CGame(e);g=STATE_GAME};this.gotoHelp=function(){new CHelp;g=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();
c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;e=a;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null,s_oCanvas,s_iGameType,s_bShowFlip=!0,s_iDifficulty,s_bWeightSquares=!1,s_bEdgeSensitive=!1,s_bFullscreen=!1;
function CTextButton(a,c,b,d,g,e,f){var h,l,k,q,p;this._init=function(a,b,c,d,e,g,f){h=[];l=[];var m=createBitmap(c),n=Math.ceil(f/20);p=new createjs.Text(d,"bold "+f+"px "+e,"#000000");p.textAlign="center";p.textBaseline="alphabetic";var t=p.getBounds();p.x=c.width/2+n;p.y=Math.floor(c.height/2)+t.height/3+n;q=new createjs.Text(d,"bold "+f+"px "+e,g);q.textAlign="center";q.textBaseline="alphabetic";t=q.getBounds();q.x=c.width/2;q.y=Math.floor(c.height/2)+t.height/3;k=new createjs.Container;k.x=a;
k.y=b;k.regX=c.width/2;k.regY=c.height/2;s_bMobile||(k.cursor="pointer");k.addChild(m,p,q);s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown");k.off("pressup");s_oStage.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){oParent=this;k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;l[a]=c};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};
this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setTextPosition=function(a){q.y=a;p.y=a+2};this.setPosition=function(a,b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(a,c,b,d,g,e,f);return this}
function CToggle(a,c,b,d,g){var e,f,h,l,k,q;this._init=function(a,b,c,d,g){q=void 0!==g?g:s_oStage;f=[];h=[];g=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=d;k=createSprite(g,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();s_bMobile||(k.cursor="pointer");q.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",
this.buttonRelease);q.removeChild(k)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;h[a]=c};this.addEventListenerWithParams=function(a,b,c,d){f[a]=b;h[a]=c;l=d};this.setCursorType=function(a){k.cursor=a};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;playSound("click",1,0);e=!e;k.gotoAndStop("state_"+e);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(h[ON_MOUSE_UP],
l)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN],l)};this.setPosition=function(a,b){k.x=a;k.y=b};this._init(a,c,b,d,g)}
function CGfxButton(a,c,b){var d,g,e;this._init=function(a,b,c){d=[];g=[];e=createBitmap(c);e.x=a;e.y=b;e.regX=c.width/2;e.regY=c.height/2;s_bMobile||(e.cursor="pointer");s_oStage.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);s_oStage.removeChild(e)};this.setVisible=function(a){e.visible=a};this._initListener=function(){e.on("mousedown",this.buttonDown);e.on("pressup",this.buttonRelease)};this.addEventListener=function(a,
b,c){d[a]=b;g[a]=c};this.buttonRelease=function(){e.scaleX=1;e.scaleY=1;d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){e.scaleX=.9;e.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.setPosition=function(a,b){e.x=a;e.y=b};this.setX=function(a){e.x=a};this.setY=function(a){e.y=a};this.getButtonImage=function(){return e};this.getX=function(){return e.x};this.getY=function(){return e.y};this._init(a,c,b);return this}
function CMenu(){var a,c,b,d,g,e,f,h,l,k,q,p,m=null,t=null;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(f);var r=s_oSpriteLibrary.getSprite("but_play");h=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-500,r);h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r=s_oSpriteLibrary.getSprite("audio_icon"),g=CANVAS_WIDTH-r.height/2-10,e=r.height/2+10,k=new CToggle(g,e,r,s_bAudioActive,s_oStage),k.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);r=s_oSpriteLibrary.getSprite("but_credits");b=r.height/2+10;d=r.height/2+10;q=new CGfxButton(b,d,r,s_oStage);q.addEventListener(ON_MOUSE_UP,this._onCredits,this);var r=window.document,n=r.documentElement;m=n.requestFullscreen||n.mozRequestFullScreen||n.webkitRequestFullScreen||n.msRequestFullscreen;t=r.exitFullscreen||r.mozCancelFullScreen||r.webkitExitFullscreen||r.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(m=!1);m&&!1===inIframe()&&(r=s_oSpriteLibrary.getSprite("but_fullscreen"),
a=b+r.width/2+10,c=d,p=new CToggle(a,c,r,s_bFullscreen,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},1E3).call(function(){l.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){h.unload();h=null;q.unload();l.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;m&&!1===inIframe()&&
p.unload();s_oStage.removeChild(f);s_oMenu=f=null};this.refreshButtonPos=function(f,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(g-f,h+e);m&&!1===inIframe()&&p.setPosition(a+f,c+h);q.setPosition(b+f,h+d)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCredits=function(){new CCreditsPanel};this._onButPlayRelease=function(){this.unload();if(isIOS()&&null===s_oSoundTrack){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack=
createjs.Sound.play("soundtrack",{loop:-1})}else playSound("click",1,0);$(s_oMain).trigger("start_session");s_oMain.gotoModeMenu()};this._onFullscreenRelease=function(){s_bFullscreen?(t.call(window.document),s_bFullscreen=!1):(m.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CModeMenu(){var a,c,b,d,g,e,f=MEDIUM_MODE,h,l,k,q,p,m=null,t,r,n,u,v=null,x=null;this._init=function(){var f=createBitmap(s_oSpriteLibrary.getSprite("bg_mod_menu"));s_oStage.addChild(f);f=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-f.height/2-20;d=f.height/2+10;p=new CGfxButton(b,d,f,!0);p.addEventListener(ON_MOUSE_UP,this._onExit,this);g=CANVAS_WIDTH-f.width/2-125;e=f.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=s_oSpriteLibrary.getSprite("audio_icon"),m=new CToggle(g,
e,f,s_bAudioActive,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);var f=window.document,w=f.documentElement;v=w.requestFullscreen||w.mozRequestFullScreen||w.webkitRequestFullScreen||w.msRequestFullscreen;x=f.exitFullscreen||f.mozCancelFullScreen||f.webkitExitFullscreen||f.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(v=!1);v&&!1===inIframe()&&(f=s_oSpriteLibrary.getSprite("but_fullscreen"),a=f.width/4+10,c=d,u=new CToggle(a,c,f,s_bFullscreen,s_oStage),u.addEventListener(ON_MOUSE_UP,
this._onFullscreenRelease,this));h=new createjs.Text(TEXT_MODE,"bold 80px "+PRIMARY_FONT,"#ffffff");h.x=CANVAS_WIDTH/2;h.y=300;h.textAlign="center";h.textBaseline="middle";h.lineWidth=600;s_oStage.addChild(h);f=s_oSpriteLibrary.getSprite("but_vs_man");k=new CGfxButton(CANVAS_WIDTH/2,700,f,!0);k.addEventListener(ON_MOUSE_UP,this._onButHumanRelease,this);f=s_oSpriteLibrary.getSprite("but_vs_pc");q=new CGfxButton(CANVAS_WIDTH/2,1200,f,!0);q.addEventListener(ON_MOUSE_UP,this._onButComputerRelease,this);
f=s_oSpriteLibrary.getSprite("difficulty_panel");w=createBitmap(f);w.regX=f.width/2;w.regY=f.height/2;w.x=CANVAS_WIDTH/2;w.y=1510;s_oStage.addChild(w);l=new createjs.Text(TEXT_DIFFICULTY,"bold 40px "+PRIMARY_FONT,"#ffffff");l.x=CANVAS_WIDTH/2;l.y=1440;l.textAlign="center";l.textBaseline="middle";l.lineWidth=600;s_oStage.addChild(l);f=s_oSpriteLibrary.getSprite("toggle_easy");t=new CToggle(CANVAS_WIDTH/2-170,1525,f,!1,s_oStage);t.addEventListenerWithParams(ON_MOUSE_UP,this._onDifficultyToggle,this,
EASY_MODE);f=s_oSpriteLibrary.getSprite("toggle_medium");r=new CToggle(CANVAS_WIDTH/2-5,1525,f,!0,s_oStage);r.addEventListenerWithParams(ON_MOUSE_UP,this._onDifficultyToggle,this,MEDIUM_MODE);f=s_oSpriteLibrary.getSprite("toggle_hard");n=new CToggle(CANVAS_WIDTH/2+165,1525,f,!1,s_oStage);n.addEventListenerWithParams(ON_MOUSE_UP,this._onDifficultyToggle,this,HARD_MODE);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){k.unload();q.unload();p.unload();t.unload();r.unload();n.unload();
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;v&&!1===inIframe()&&u.unload();s_oModeMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(f,h){p.setPosition(b-f,h+d);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(g-f,h+e);v&&!1===inIframe()&&u.setPosition(a+f,c+h)};this._onDifficultyToggle=function(a){switch(a){case EASY_MODE:t.setActive(!0);r.setActive(!1);n.setActive(!1);f=EASY_MODE;break;case MEDIUM_MODE:t.setActive(!1);r.setActive(!0);n.setActive(!1);
f=MEDIUM_MODE;break;case HARD_MODE:t.setActive(!1),r.setActive(!1),n.setActive(!0),f=HARD_MODE}};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){this.unload();s_oMain.gotoMenu()};this._onButHumanRelease=function(){playSound("click",1,0);this.unload();s_oMain.gotoGame(MODE_HUMAN)};this._onButComputerRelease=function(){playSound("click",1,0);this.unload();s_oMain.gotoGame(MODE_COMPUTER,f)};this._onFullscreenRelease=function(){s_bFullscreen?
(x.call(window.document),s_bFullscreen=!1):(v.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oModeMenu=this;this._init()}var s_oModeMenu=null;
function CGame(a){var c,b,d,g,e,f,h,l,k,q,p,m,t,r=null,n,u,v=null;this._init=function(){b=c=!1;d=PAWN_BLACK;q=k=h=l=e=0;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);t=new CInterface;u=new createjs.Container;u.x=CANVAS_WIDTH/2;u.y=CANVAS_HEIGHT/2;s_oStage.addChild(u);this._initGrid();this.calcFlipCounts();new CHelpPanel};this._initGrid=function(){var a=NUM_CELL,b=CELL_LENGTH,c=-BOARD_LENGTH/2+b/2;p=[];for(var d=0;d<a;d++){p[d]=[];for(var e=0;e<a;e++)p[d][e]={x:c+e*
b,y:c+d*b}}m=[];for(d=0;d<a;d++)for(m[d]=[],e=0;e<a;e++)m[d][e]=new CCell(p[d][e].x,p[d][e].y,-1,d,e,u);m[3][3].setColor(PAWN_WHITE);m[4][4].setColor(PAWN_WHITE);m[3][4].setColor(PAWN_BLACK);m[4][3].setColor(PAWN_BLACK);f=4;this.countPawn();t.activePlayer(PAWN_BLACK)};this.changeTurn=function(){f===TOT_CELL?(this.resetFlips(),this.gameOver()):(d=d===PAWN_BLACK?PAWN_WHITE:PAWN_BLACK,t.activePlayer(d),this.calcFlipCounts(),b)?d===PAWN_WHITE&&s_iGameType===MODE_COMPUTER&&(v=new CThinking,setTimeout(function(){v.unload();
v=null;n.othelloAI()},MIN_AI_THINKING+Math.random()*(MAX_AI_THINKING-MIN_AI_THINKING))):(e++,2===e?new CAlertPanel(TEXT_STALL,d,ALERT_TYPE_STALL):new CAlertPanel(TEXT_NOMOVES,d,ALERT_TYPE_NOMOVES))};this.cellClicked=function(a,b,c){playSound("click_cell",1,0);this.resetFlips();f++;g=c;m[a][b].setColor(d);this.cellFlips(a,b);this.countPawn()};this.setShowNumFlip=function(){this.calcFlipCounts()};this.restartGame=function(){this.unload();this._init()};this.pauseGame=function(a){c=!a};this.unload=function(){c=
!1;t.unload();null!==r&&r.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu()};this._onExitHelp=function(){c=!0};this.gameOver=function(){r=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));r.show(l,h,k,q);t.setInfoVisible(!1)};this.update=function(){c&&(null!==v&&v.update(),d===PAWN_WHITE?(q+=s_iTimeElaps,t.refreshWhiteTime(q)):(k+=s_iTimeElaps,t.refreshBlackTime(k)))};this.numFlips=function(a,b){var c,e,f,g,h,k=0;for(e=-1;1>=
e;e++)for(c=-1;1>=c;c++)for(f=1;;f++){g=a+f*c;h=b+f*e;if(0>g||g>=NUM_CELL||0>h||h>=NUM_CELL)break;if(m[g][h].getType()===PAWN_NULL)break;if(m[g][h].getType()===d){k+=f-1;break}}return k};this.cellFlips=function(a,b){var c,e,f,g,h;for(e=-1;1>=e;e++)for(c=-1;1>=c;c++)for(f=1;;f++){g=a+f*c;h=b+f*e;if(0>g||g>=NUM_CELL||0>h||h>=NUM_CELL)break;if(m[g][h].getType()===PAWN_NULL)break;if(m[g][h].getType()===d){for(f--;0<f;f--)g=a+f*c,h=b+f*e,m[g][h].reversi();break}}return 0};this.onFlipsEnd=function(){g--;
0===g&&this.changeTurn()};this.calcFlipCounts=function(){for(var a=0;a<NUM_CELL;a++)for(var c=0;c<NUM_CELL;c++)m[a][c].setNumFlips(0),m[a][c].getType()===PAWN_NULL&&(m[a][c].setNumFlips(this.numFlips(a,c)),0<m[a][c].getNumFlips()&&(b=!0,e=0,d===PAWN_WHITE&&s_iGameType===MODE_COMPUTER?m[a][c].setClickableArea(!1,!1,d):m[a][c].setClickableArea(!0,s_bShowFlip,d)))};this.resetFlips=function(){for(var a=0;a<NUM_CELL;a++)for(var c=0;c<NUM_CELL;c++)m[a][c].setClickableArea(!1);b=!1};this.countPawn=function(){for(var a,
b=h=l=0;b<NUM_CELL;b++)for(var c=0;c<NUM_CELL;c++)a=m[b][c].getType(),0===a?l++:1===a&&h++;t.refreshBlackPawnNumber(l);t.refreshWhitePawnNumber(h)};this.rate=function(a,b){var c;if(m[a][b].getType()!==PAWN_NULL||0>a||a>=NUM_CELL||0>b||b>=NUM_CELL)return 0;c=m[a][b].getNumFlips();s_bWeightSquares||(c=0<c?1:0);if(s_bEdgeSensitive&&0<c){c+=10;if(0===a||a===NUM_CELL-1)c+=4;if(0===b||b===NUM_CELL-1)c+=4;if(1===a||a===NUM_CELL-2)c-=5;if(1===b||b===NUM_CELL-2)c-=5;1>c&&(c=1)}return c};this.othelloAI=function(){var a,
b,c=0,d=0,e,f,g;for(b=0;b<NUM_CELL;b++)for(a=0;a<NUM_CELL;a++)e=this.rate(a,b),m[a][b].setWeight(e),e===c?d++:e>c&&(c=e,d=1);for(;0<d;)for(f=Math.floor(Math.random()*d),b=g=0;b<NUM_CELL;b++)for(a=0;a<NUM_CELL;a++)if(e=m[a][b].getWeight(),e===c){if(g===f){this.cellClicked(a,b,m[a][b].getNumFlips());return}g++}};s_oGame=this;n=this;this._init()}var s_oGame;
function CInterface(){var a,c,b,d,g,e,f,h,l,k,q,p,m,t=null,r=null;this._init=function(){var n,u=s_oSpriteLibrary.getSprite("but_exit");g=CANVAS_WIDTH-u.height/2-20;e=u.height/2+10;l=new CGfxButton(g,e,u,!0);l.addEventListener(ON_MOUSE_UP,this._onExit,this);n=CANVAS_WIDTH-u.width/2-125;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u=s_oSpriteLibrary.getSprite("but_settings"),b=n,d=10+u.height/2,k=new CGfxButton(b,d,u,!0),k.addEventListener(ON_MOUSE_UP,this._onButConfigRelease,this);n=window.document;
u=n.documentElement;t=u.requestFullscreen||u.mozRequestFullScreen||u.webkitRequestFullScreen||u.msRequestFullscreen;r=n.exitFullscreen||n.mozCancelFullScreen||n.webkitExitFullscreen||n.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(t=!1);t&&!1===inIframe()&&(u=s_oSpriteLibrary.getSprite("but_fullscreen"),a=u.width/4+10,c=e,m=new CToggle(a,c,u,s_bFullscreen,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));p=new CInfoTurn(815,1645,PAWN_BLACK,s_oStage);q=new CInfoTurn(490,300,PAWN_WHITE,
s_oStage);f=[];for(n=0;n<TOT_CELL;n++)f[n]=createBitmap(s_oSpriteLibrary.getSprite("white_chip")),f[n].x=300+10.5*n,f[n].y=422,s_oStage.addChild(f[n]);h=[];for(n=0;n<TOT_CELL;n++)h[n]=createBitmap(s_oSpriteLibrary.getSprite("black_chip")),h[n].x=960-10.5*n,h[n].y=1422,s_oStage.addChild(h[n]);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){l.unload();k.unload();t&&!1===inIframe()&&m.unload();p.unload();q.unload();for(var a=0;a<TOT_CELL;a++)s_oStage.removeChild(f[a]),s_oStage.removeChild(h[a]);
s_oInterface=null};this.refreshButtonPos=function(f,h){l.setPosition(g-f,h+e);k.setPosition(b-f,h+d);t&&!1===inIframe()&&m.setPosition(a+f,c+h)};this.refreshWhitePawnNumber=function(a){q.refreshPawnNumber(a);for(var b=0;b<a;b++)f[b].visible=!1;for(b=a;b<TOT_CELL;b++)f[b].visible=!0};this.refreshWhiteTime=function(a){50<a&&q.refreshTime(formatTime(a))};this.refreshBlackPawnNumber=function(a){p.refreshPawnNumber(a);for(var b=0;b<a;b++)h[b].visible=!1;for(b=a;b<TOT_CELL;b++)h[b].visible=!0};this.refreshBlackTime=
function(a){50<a&&p.refreshTime(formatTime(a))};this.activePlayer=function(a){a===PAWN_WHITE?(p.active(!1),q.active(!0)):(q.active(!1),p.active(!0))};this.setInfoVisible=function(a){q.setPanelVisible(a);p.setPanelVisible(a)};this._onButConfigRelease=function(){new CConfigPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){null.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){$(s_oMain).trigger("end_session");
$(s_oMain).trigger("show_interlevel_ad");s_oGame.onExit()};this._onFullscreenRelease=function(){s_bFullscreen?(r.call(window.document),s_bFullscreen=!1):(t.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CInfoTurn(a,c,b,d){var g,e,f,h,l,k,q,p;this._init=function(a,b,c,d){g=new createjs.Container;g.x=a;g.y=b;d.addChild(g);a=s_oSpriteLibrary.getSprite("bg_turn");b={images:[a],framerate:58,frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{off:[0,0,"on"],on:[1,1,"off"]}};b=new createjs.SpriteSheet(b);e=createSprite(b,0,a.width/2/2,a.height/2,a.width/2,a.height);e.stop();g.addChild(e);f=createSprite(b,1,a.width/2/2,a.height/2,a.width/2,a.height);f.stop();f.x=
10;f.alpha=0;g.addChild(f);a=s_oSpriteLibrary.getSprite("pawn");b={images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{off:[0],on:[1]}};b=new createjs.SpriteSheet(b);k=createSprite(b,c,a.width/2/2,a.height/2,a.width/2,a.height);k.stop();k.x=c===PAWN_WHITE?110:-220;k.y=-10;g.addChild(k);q=new createjs.Text("x2","bold 68px "+PRIMARY_FONT,"#ffffff");q.x=c===PAWN_WHITE?160:-160;q.y=-5;q.textAlign="left";q.textBaseline="middle";q.lineWidth=200;g.addChild(q);
a=s_oSpriteLibrary.getSprite("time_icon");h=createBitmap(a);h.regX=a.width/2;h.regY=a.height/2;h.scaleX=.8;h.scaleY=.8;h.x=c===PAWN_WHITE?-230:225;h.y=-5;g.addChild(h);l=new createjs.Text("00:00","bold 58px "+PRIMARY_FONT,"#ffffff");c===PAWN_WHITE?(l.x=-180,l.textAlign="left"):(l.x=175,l.textAlign="right");l.textBaseline="middle";l.lineWidth=200;g.addChild(l)};this.refreshPawnNumber=function(a){q.text="x"+a};this.refreshTime=function(a){l.text=a};this.active=function(a){a?(createjs.Tween.get(e).to({alpha:0},
750,createjs.Ease.cubicOut).to({alpha:1},750,createjs.Ease.cubicIn).call(function(){p.active(a)}),createjs.Tween.get(f).to({alpha:1},750,createjs.Ease.cubicOut).to({alpha:0},750,createjs.Ease.cubicIn)):(e.alpha=1,f.alpha=0,createjs.Tween.removeAllTweens())};this.unload=function(){d.removeChild(g)};this.setBgVisible=function(a){e.visible=a};this.setPanelVisible=function(a){g.visible=a};this.setPawn=function(a){k.gotoAndStop(a)};p=this;this._init(a,c,b,d)}
function CHelpPanel(){var a,c,b,d,g,e;this._init=function(){var e=this;d=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));var h={images:[s_oSpriteLibrary.getSprite("pawn")],frames:{width:PAWN_SIZE,height:PAWN_SIZE,regX:PAWN_SIZE/2,regY:PAWN_SIZE/2},animations:{black:[0],white:[1]}},h=new createjs.SpriteSheet(h);a=[];for(var l=0;4>l;l++)a[l]=createSprite(h,l%2,PAWN_SIZE/2,PAWN_SIZE/2,PAWN_SIZE,PAWN_SIZE),a[l].stop(),2>l?(a[l].y=850,a[l].x=0===l%2?CANVAS_WIDTH/2+50:CANVAS_WIDTH/2-50):(a[l].y=950,
a[l].x=0===l%2?CANVAS_WIDTH/2-50:CANVAS_WIDTH/2+50);h=CANVAS_WIDTH/2;l=CANVAS_HEIGHT/2-300;c=new createjs.Text(TEXT_HELP1," 40px "+PRIMARY_FONT,"#ffffff");c.x=h;c.y=l;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=600;h=CANVAS_WIDTH/2;l=CANVAS_HEIGHT/2+100;b=new createjs.Text(TEXT_HELP2," 40px "+PRIMARY_FONT,"#ffffff");b.x=h;b.y=l;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=600;g=new createjs.Container;g.addChild(d,c,b,a[0],a[1],a[2],a[3]);g.alpha=0;s_oStage.addChild(g);
createjs.Tween.get(g).to({alpha:1},700);g.on("pressup",function(){e._onExitHelp()})};this.unload=function(){s_oStage.removeChild(g);var a=this;g.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){e.unload();s_oGame._onExitHelp()};e=this;this._init()}
function CAlertPanel(a,c,b){var d,g,e,f;this._init=function(a,c){s_oGame.pauseGame(!0);d=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(d);if(b===ALERT_TYPE_NOMOVES){var h=s_oSpriteLibrary.getSprite("pawn"),h=new createjs.SpriteSheet({images:[h],frames:{width:PAWN_SIZE,height:PAWN_SIZE,regX:PAWN_SIZE/2,regY:PAWN_SIZE/2},animations:{black:[0],white:[1]}});f=createSprite(h,c,PAWN_SIZE/2,PAWN_SIZE/2,PAWN_SIZE,PAWN_SIZE);f.stop();f.x=CANVAS_WIDTH/2;f.y=800;s_oStage.addChild(f)}h=
s_oSpriteLibrary.getSprite("but_exit");g=new CGfxButton(993,640,h,!0);g.addEventListener(ON_MOUSE_UP,this._onExit,this);e=new createjs.Text(a,"bold 80px "+PRIMARY_FONT,"#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;e.textAlign="center";e.textBaseline="midlle";e.lineWidth=600;s_oStage.addChild(e)};this.unload=function(){g.unload();s_oStage.removeChild(d);s_oStage.removeChild(e);s_oStage.removeChild(f);s_oGame.pauseGame(!1)};this._onExit=function(){this.unload();b===ALERT_TYPE_NOMOVES?s_oGame.changeTurn():
s_oGame.gameOver()};this._init(a,c)}
function CThinking(){var a,c,b,d,g,e;this._init=function(){a=!0;c=0;b=new createjs.Container;var f=(new createjs.Graphics).beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e=new createjs.Shape(f);e.on("click",function(){});d=new createjs.Text(TEXT_THINKING,"bold 60px "+PRIMARY_FONT,"#ffffff");d.x=.5*CANVAS_WIDTH;d.y=.5*CANVAS_HEIGHT-100;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=800;g=new createjs.Text("","bold 180px "+PRIMARY_FONT,"#ffffff");g.x=.5*CANVAS_WIDTH-
76;g.y=.5*CANVAS_HEIGHT-50;g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=800;b.addChild(e,d,g);s_oStage.addChild(b)};this.unload=function(){a=!1;e.off("click",function(){});s_oStage.removeChild(b)};this.update=function(){a&&(c+=s_iTimeElaps,0<=c&&c<TIME_LOOP_WAIT/4?g.text="":c>=TIME_LOOP_WAIT/4&&c<2*TIME_LOOP_WAIT/4?g.text=".":c>=2*TIME_LOOP_WAIT/4&&c<3*TIME_LOOP_WAIT/4?g.text="..":c>=3*TIME_LOOP_WAIT/4&&c<TIME_LOOP_WAIT?g.text="...":c=0)};this._init()}
function CConfigPanel(){var a,c=null,b,d,g,e;this._init=function(){s_oGame.pauseGame(!0);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(a);var f=s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(993,640,f,!0);d.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(f=s_oSpriteLibrary.getSprite("audio_icon_big"),c=new CToggle(350,860,f,s_bAudioActive,s_oStage),c.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),b=new createjs.Text(TEXT_AUDIO,
"bold 60px "+PRIMARY_FONT,"#ffffff"),b.x=460,b.y=860,b.textAlign="left",b.textBaseline="middle",b.lineWidth=600,s_oStage.addChild(b),f=s_oSpriteLibrary.getSprite("but_flip"),g=new CToggle(350,1130,f,s_bShowFlip,s_oStage),g.addEventListener(ON_MOUSE_UP,this._onShowNumFlip,this),e=new createjs.Text(TEXT_COUNT,"bold 60px "+PRIMARY_FONT,"#ffffff"),e.x=460,e.y=1130):(f=s_oSpriteLibrary.getSprite("audio_icon_big"),g=new CToggle(350,860,f,s_bShowFlip,s_oStage),g.addEventListener(ON_MOUSE_UP,this._onShowNumFlip,
this),e=new createjs.Text(TEXT_COUNT,"bold 60px "+PRIMARY_FONT,"#ffffff"),e.x=460,e.y=860);e.textAlign="left";e.textBaseline="middle";e.lineWidth=600;s_oStage.addChild(e)};this.unload=function(){s_oStage.removeChild(e);s_oStage.removeChild(a);d.unload();g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oStage.removeChild(b),c.unload();s_oGame.pauseGame(!1)};this._onExit=function(){this.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};
this._onShowNumFlip=function(){s_bShowFlip=!s_bShowFlip;s_oGame.setShowNumFlip()};this._init()}
function CEndPanel(a){var c,b,d,g,e;this._init=function(a){s_oGame.pauseGame(!0);c=createBitmap(a);c.x=0;c.y=0;e=new createjs.Text("","bold 60px Arial","#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+200;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=500;b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(c,e);d=new CInfoTurn(CANVAS_WIDTH/2,820,PAWN_BLACK,b);d.setBgVisible(!1);g=new CInfoTurn(CANVAS_WIDTH/2,670,PAWN_BLACK,b);g.setBgVisible(!1);g.setPawn(PAWN_WHITE);s_oStage.addChild(b)};
this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(a,c,l,k){d.refreshTime(formatTime(l));g.refreshTime(formatTime(k));d.refreshPawnNumber(a);g.refreshPawnNumber(c);a>c?(playSound("win",1,0),e.text=TEXT_BLACK+" "+TEXT_GAMEOVER):a<c?(s_iGameType===MODE_COMPUTER?playSound("game_over",1,0):playSound("win",1,0),e.text=TEXT_WHITE+" "+TEXT_GAMEOVER):(playSound("game_over",1,0),e.text=TEXT_DRAW);b.visible=!0;var f=this;
createjs.Tween.get(b).to({alpha:1},500).call(function(){f._initListener()});$(s_oMain).trigger("save_score",[a,c,l,k,s_iGameType,s_iDifficulty]);$(s_oMain).trigger("share_event",[a,c,s_iGameType])};this._onExit=function(){b.off("mousedown",this._onExit);d.unload();g.unload();s_oStage.removeChild(b);$(s_oMain).trigger("end_session");$(s_oMain).trigger("show_interlevel_ad");s_oGame.onExit()};this._init(a);return this}
function CCell(a,c,b,d,g,e){var f,h,l,k=0,q,p,m,t,r,n;this._init=function(a,b,c,d,e,g){f=c;h=d;l=e;p=new createjs.Container;p.x=a;p.y=b;g.addChild(p);a={images:[s_oSpriteLibrary.getSprite("pawn")],frames:{width:PAWN_SIZE,height:PAWN_SIZE,regX:PAWN_SIZE/2,regY:PAWN_SIZE/2},animations:{black:[0],white:[1]}};a=new createjs.SpriteSheet(a);m=createSprite(a,c,PAWN_SIZE/2,PAWN_SIZE/2,PAWN_SIZE,PAWN_SIZE);m.stop();p.addChild(m);r=new createjs.Shape;r.graphics.setStrokeStyle(8);r.graphics.beginStroke("rgba(255,255,255,1)").drawCircle(0,
0,35);r.visible=!1;p.addChild(r);n=new createjs.Text(k,"bold 50px "+PRIMARY_FONT,"#ffffff");n.textAlign="center";n.textBaseline="middle";n.visible=!1;p.addChild(n);t=new createjs.Shape;t.graphics.beginFill("rgba(158,0,0,0.01)").drawRect(-CELL_LENGTH/2,-CELL_LENGTH/2,CELL_LENGTH,CELL_LENGTH);t.on("mousedown",this._onCellClick);t.visible=!1;p.addChild(t)};this.unload=function(){e.removeChild(p);t.off("mousedown",this._onCellClick)};this.setClickableArea=function(a,b,c){t.visible=a;n.text=k;c===PAWN_WHITE?
(n.color="white",r.graphics.beginStroke("rgba(255,255,255,1)").drawCircle(0,0,35)):(n.color="black",r.graphics.beginStroke("rgba(0,0,0,1)").drawCircle(0,0,35));b?(r.visible=a,n.visible=a,p.cursor="pointer"):(r.visible=!1,n.visible=!1,p.cursor=null)};this.setColor=function(a){f===PAWN_NULL&&(m.gotoAndStop(a),f=a)};this.reversi=function(){f===PAWN_WHITE?(f=PAWN_BLACK,createjs.Tween.get(p).to({scaleX:.1},200).call(function(){m.gotoAndStop(PAWN_BLACK)}).to({scaleX:1},200).call(function(){s_oGame.onFlipsEnd()})):
(f=PAWN_WHITE,createjs.Tween.get(p).to({scaleX:.1},200).call(function(){m.gotoAndStop(PAWN_WHITE)}).to({scaleX:1},200).call(function(){s_oGame.onFlipsEnd()}))};this._onCellClick=function(){s_oGame.cellClicked(h,l,k)};this.getType=function(){return f};this.setNumFlips=function(a){k=a};this.getNumFlips=function(){return k};this.setWeight=function(a){q=a};this.getWeight=function(){return q};this._init(a,c,b,d,g,e)}
function CCreditsPanel(){var a,c,b,d,g,e,f,h;this._init=function(){h=new createjs.Container;s_oStage.addChild(h);var l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(l);g=new createjs.Shape;g.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.addChild(g);l=s_oSpriteLibrary.getSprite("msg_box");c=createBitmap(l);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;c.regX=l.width/2;c.regY=l.height/2;h.addChild(c);e=new createjs.Shape;e.graphics.beginFill("#0f0f0f").drawRect(0,
0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=.01;e.on("click",this._onLogoButRelease);h.addChild(e);l=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH/2+340;b=new CGfxButton(a,650,l,h);b.addEventListener(ON_MOUSE_UP,this.unload,this);d=new createjs.Text(TEXT_CREDITS_DEVELOPED,"46px Arial","#ffffff");d.x=CANVAS_WIDTH/2;d.y=840;d.textAlign="center";h.addChild(d);var l=s_oSpriteLibrary.getSprite("logo_credits"),k=createBitmap(l);k.regX=l.width/2;k.regY=l.height/2;k.x=CANVAS_WIDTH/2;k.y=950;h.addChild(k);
f=new createjs.Text("www.codethislab.com","44px Arial","#ffffff");f.x=CANVAS_WIDTH/2;f.y=1010;f.textAlign="center";h.addChild(f)};this.unload=function(){e.off("click",this._onLogoButRelease);b.unload();b=null;s_oStage.removeChild(h)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};this._init()};
