var s_iScaleFactor=1,s_iOffsetX,s_iOffsetY,s_bIsIphone=!1,s_bIsRetina;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var d=a.toLowerCase(),c=window.document,f=c.documentElement;if(void 0===window["inner"+a])a=f["client"+a];else if(window["inner"+a]!=f["client"+a]){var h=c.createElement("body");h.id="vpw-test-b";h.style.cssText="overflow:scroll";var b=c.createElement("div");b.id="vpw-test-d";b.style.cssText="position:absolute;top:-1000px";b.innerHTML="<style>@media("+d+":"+f["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";h.appendChild(b);f.insertBefore(h,c.head);
a=7==b["offset"+a]?f["client"+a]:window["inner"+a];f.removeChild(h)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function isIOS(){isRetina();for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function isRetina(){s_bIsRetina=matchMedia("(-webkit-min-device-pixel-ratio: 2), (min-device-pixel-ratio: 2), (min-resolution: 192dpi)").matches?!0:!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width");_checkOrientation(d,a);var c=Math.min(a/CANVAS_HEIGHT,d/CANVAS_WIDTH),f=CANVAS_WIDTH*c,c=CANVAS_HEIGHT*c,h;c<a?(h=a-c,c+=h,f+=CANVAS_WIDTH/CANVAS_HEIGHT*h):f<d&&(h=d-f,f+=h,c+=CANVAS_HEIGHT/CANVAS_WIDTH*h);h=a/2-c/2;var b=d/2-f/2,e=CANVAS_WIDTH/f;if(b*e<-EDGEBOARD_X||h*e<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
d/(CANVAS_WIDTH-2*EDGEBOARD_X)),f=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,h=(a-c)/2,b=(d-f)/2,e=CANVAS_WIDTH/f;s_iOffsetX=-1*b*e;s_iOffsetY=-1*h*e;0<=h&&(s_iOffsetY=0);0<=b&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oModeMenu&&s_oModeMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oSandBoxMenu&&s_oSandBoxMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsRetina?(canvas=document.getElementById("canvas"),
s_oStage.canvas.width=2*f,s_oStage.canvas.height=2*c,canvas.style.width=f+"px",canvas.style.height=c+"px",a=Math.min(f/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=2*a,s_iScaleFactor=2*a):s_bMobile?($("#canvas").css("width",f+"px"),$("#canvas").css("height",c+"px")):(s_oStage.canvas.width=f,s_oStage.canvas.height=c,s_iScaleFactor=Math.min(f/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>h?$("#canvas").css("top",h+"px"):$("#canvas").css("top","0px");
$("#canvas").css("left",b+"px")}}
function _checkOrientation(a,d){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>d?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function playSound(a,d,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:c,volume:d}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,d){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=d}function setMute(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(d)}
function createBitmap(a,d,c){var f=new createjs.Bitmap(a),h=new createjs.Shape;d&&c?h.graphics.beginFill("#fff").drawRect(0,0,d,c):h.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);f.hitArea=h;return f}function createSprite(a,d,c,f,h,b){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-c,-f,h,b);a.hitArea=d;return a}function pad(a,d,c){a+="";return a.length>=d?a:Array(d-a.length+1).join(c||"0")+a}
function randomFloatBetween(a,d,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(c))}function rotateVector2D(a,d){var c=d.getX()*Math.cos(a)+d.getY()*Math.sin(a),f=d.getX()*-Math.sin(a)+d.getY()*Math.cos(a);d.set(c,f)}function tweenVectorsOnX(a,d,c){return a+c*(d-a)}function shuffle(a){for(var d=a.length,c,f;0!==d;)f=Math.floor(Math.random()*d),--d,c=a[d],a[d]=a[f],a[f]=c;return a}
function bubbleSort(a){var d;do{d=!1;for(var c=0;c<a.length-1;c++)a[c]>a[c+1]&&(d=a[c],a[c]=a[c+1],a[c+1]=d,d=!0)}while(d)}function compare(a,d){return a.index>d.index?-1:a.index<d.index?1:0}function easeLinear(a,d,c,f){return c*a/f+d}function easeInQuad(a,d,c,f){return c*(a/=f)*a+d}function easeInSine(a,d,c,f){return-c*Math.cos(a/f*(Math.PI/2))+c+d}function easeInCubic(a,d,c,f){return c*(a/=f)*a*a+d}function easeInQuart(a,d,c,f){return c*(a/=f)*a*a*a+d}
function easeOutQuart(a,d,c,f){return-c*((a=a/f-1)*a*a*a-1)+d}function getTrajectoryPoint(a,d){var c=new createjs.Point,f=(1-a)*(1-a),h=a*a;c.x=f*d.start.x+2*(1-a)*a*d.traj.x+h*d.end.x;c.y=f*d.start.y+2*(1-a)*a*d.traj.y+h*d.end.y;return c}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var c="",c=10>d?c+("0"+d+":"):c+(d+":");return 10>a?c+("0"+a):c+a}
function angleBetweenVector2D(a,d){var c=Math.acos(dotProductV2(a,d)/(a.length()*d.length()));return 1==isNaN(c)?0:c}function dotProductV2(a,d){return a.getX()*d.getX()+a.getY()*d.getY()}function radiansToDegree(a){return 180/Math.PI*a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,d){var c,f;c=getBounds(a,.9);f=getBounds(d,.98);return calculateIntersection(c,f)}
function calculateIntersection(a,d){var c,f,h,b,e,g,m,k;c=a.x+(h=a.width/2);f=a.y+(b=a.height/2);e=d.x+(g=d.width/2);m=d.y+(k=d.height/2);c=Math.abs(c-e)-(h+g);f=Math.abs(f-m)-(b+k);return 0>c&&0>f?(c=Math.min(Math.min(a.width,d.width),-c),f=Math.min(Math.min(a.height,d.height),-f),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:c,height:f,rect1:a,rect2:d}):null}
function getBounds(a,d){var c={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){c.x2=-Infinity;c.y2=-Infinity;var f=a.children,h=f.length,b,e;for(e=0;e<h;e++)b=getBounds(f[e],1),b.x<c.x&&(c.x=b.x),b.y<c.y&&(c.y=b.y),b.x+b.width>c.x2&&(c.x2=b.x+b.width),b.y+b.height>c.y2&&(c.y2=b.y+b.height);Infinity==c.x&&(c.x=0);Infinity==c.y&&(c.y=0);Infinity==c.x2&&(c.x2=0);Infinity==c.y2&&(c.y2=0);c.width=c.x2-c.x;c.height=c.y2-c.y;delete c.x2;delete c.y2}else{var g,m;a instanceof createjs.Bitmap?
(h=a.sourceRect||a.image,e=h.width*d,g=h.height*d):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(h=a.spriteSheet.getFrame(a.currentFrame),e=h.rect.width,g=h.rect.height,f=h.regX,m=h.regY):(c.x=a.x||0,c.y=a.y||0):(c.x=a.x||0,c.y=a.y||0);f=f||0;e=e||0;m=m||0;g=g||0;c.regX=f;c.regY=m;h=a.localToGlobal(0-f,0-m);b=a.localToGlobal(e-f,g-m);e=a.localToGlobal(e-f,0-m);f=a.localToGlobal(0-f,g-m);c.x=Math.min(Math.min(Math.min(h.x,
b.x),e.x),f.x);c.y=Math.min(Math.min(Math.min(h.y,b.y),e.y),f.y);c.width=Math.max(Math.max(Math.max(h.x,b.x),e.x),f.x)-c.x;c.height=Math.max(Math.max(Math.max(h.y,b.y),e.y),f.y)-c.y}return c}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,c,f;0<d;)f=Math.floor(Math.random()*d),d--,c=a[d],a[d]=a[f],a[f]=c;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var d=window.location.search.substring(1).split("&"),c=0;c<d.length;c++){var f=d[c].split("=");if(f[0]==a)return f[1]}}String.prototype.format=function(){for(var a=this,d=arguments.length;d--;)a=a.replace(new RegExp("\\{"+d+"\\}","gm"),arguments[d]);return a};function Timer(a,d){var c,f,h=d;this.pause=function(){window.clearTimeout(c);h-=new Date-f};this.resume=function(){f=new Date;window.clearTimeout(c);c=window.setTimeout(a,h)};this.resume()}
function CSpriteLibrary(){var a,d,c,f,h,b;this.init=function(e,g,m){c=d=0;f=e;h=g;b=m;a={}};this.addSprite=function(b,g){a.hasOwnProperty(b)||(a[b]={szPath:g,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){h.call(b)};this._onSpriteLoaded=function(){f.call(b);++c==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var SHIP_SMALL={map:[[!0],[!0],[!0]],sandbox_sprite:"ship5",battle_spritesheet:5,index_type:0,reg_points:{x:12,y:24,inverseX:74,inverseY:60},fill_pos:{x:151.5,y:-344.5},enemy_sunk_pos:{x:550,y:-26}},SHIP_SUB={map:[[!0],[!0],[!0],[!0]],sandbox_sprite:"ship4",battle_spritesheet:4,index_type:1,reg_points:{x:10,y:18,inverseX:100,inverseY:74},fill_pos:{x:147.5,y:-413},enemy_sunk_pos:{x:400,y:-26}},SHIP_MEDIUM={map:[[!0],[!0],[!0],[!0]],sandbox_sprite:"ship3",battle_spritesheet:3,index_type:2,reg_points:{x:10,
y:28,inverseX:106,inverseY:86},fill_pos:{x:150,y:-269},enemy_sunk_pos:{x:680,y:-26}},SHIP_LONG={map:[[!0],[!0],[!0],[!0],[!0]],sandbox_sprite:"ship2",battle_spritesheet:2,index_type:3,reg_points:{x:16,y:46,inverseX:134,inverseY:118},fill_pos:{x:151.5,y:-196},enemy_sunk_pos:{x:860,y:-26}},SHIP_BATTLE={map:[[!0],[!0],[!0],[!0],[!0],[!0]],sandbox_sprite:"ship1",battle_spritesheet:1,index_type:4,reg_points:{x:6,y:48,inverseX:166,inverseY:138},fill_pos:{x:149,y:-118.5},enemy_sunk_pos:{x:1060,y:-26}},SHIP_CARRIER=
{map:[[!0,!0],[!0,!0],[!0,!0],[!0,!0],[!0,!0]],sandbox_sprite:"ship0",battle_spritesheet:0,index_type:5,reg_points:{x:14,y:60,inverseX:170,inverseY:112},fill_pos:{x:154,y:-41},enemy_sunk_pos:{x:1280,y:-26}},CANVAS_WIDTH=1920,CANVAS_HEIGHT=1080,EDGEBOARD_X=250,EDGEBOARD_Y=80,PRIMARY_FONT="Arial",SECONDARY_FONT="Army",FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=
5,MODE_CLASSIC=0,MODE_ADVANCED=1,PLAYER=0,OPPONENT=1,SHIPS_TYPE=[SHIP_CARRIER,SHIP_BATTLE,SHIP_LONG,SHIP_MEDIUM,SHIP_SUB,SHIP_SMALL],MISSILE_TYPE_NORMAL=0,MISSILE_TYPE_TORPEDO=1,MISSILE_TYPE_AIRSTRIKE=2,SEA_PIECE_DIM=512,NUM_CELL=14,TOT_CELL=196,BOARD_LENGTH=710,BOARD_REG_POINTS={x:237,y:286},CELL_LENGTH=BOARD_LENGTH/NUM_CELL,CONTROL_CELL_DIM=52,CELL_STATE_VOID="void",CELL_STATE_HIT="hit",CELL_STATE_SUNK="sunk",CELL_STATE_WATER="water",AI_STATE_NEW_COORDINATE=0,AI_STATE_FIND_SHIP_NEIGHBOR=1,AI_FIND_DIRECTION=
2,AI_FOLLOW_DIRECTION=3,AI_REVERSE_DIRECTION=4,AI_FOLLOW_REVERSE=5,AI_FOLLOW_CARRIER=6,PREDICT_WATER=0,PREDICT_HIT=1,PREDICT_SUNK=2,COST_AIRSTRIKE=100,COST_RADAR=200,NUM_BOMB_AIRSTRIKE=5,MIN_AI_THINKING=1E3,MAX_AI_THINKING=1500,POINTS_TO_LOSE,POINTS_EARNED,AD_SHOW_COUNTER,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;TEXT_WIN="YOU WIN";TEXT_LOSE="YOU LOSE";TEXT_SCORE="SCORE";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_YOUR_FLEET="YOUR FLEET";TEXT_ENEMY_FLEET="ENEMY FLEET";TEXT_STRATEGY_PANEL="STRATEGY PANEL";
TEXT_GAME_MODE="GAME MODE";TEXT_CLASSIC="CLASSIC";TEXT_ADVANCED="ADVANCED";TEXT_COST="COST";TEXT_SUNK="SUNK";TEXT_HELP="HELP";TEXT_HELP_CLASSIC="CLICK ON A CELL AND GUESS THE POSITION OF YOUR ENEMY'S SHIP TO DESTROY THEM";TEXT_HELP_ADVANCED="COLLECT POINTS TO BUY THE POWER-UPS";TEXT_HELP_AIRSTRIKE="HITS RANDOM CELLS OT ONCE";TEXT_HELP_RADAR="REVEALS THE POSITION OF AN OPPONENT'S SHIP";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";
TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,d,c,f,h,b,e;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();e=new createjs.Container;s_oStage.addChild(e)};this.unload=function(){e.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(b).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));e.addChild(g);g=s_oSpriteLibrary.getSprite("progress_bar");f=createBitmap(g);f.x=CANVAS_WIDTH/2-g.width/2;f.y=CANVAS_HEIGHT-170;e.addChild(f);a=g.width;d=g.height;h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,1,d);e.addChild(h);f.mask=
h;c=new createjs.Text("","30px Arial","#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT-125;c.shadow=new createjs.Shadow("#000",2,2,2);c.textBaseline="alphabetic";c.textAlign="center";e.addChild(c);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=0;e.addChild(b)};this.refreshLoader=function(b){c.text=b+"%";h.graphics.clear();b=Math.floor(b*a/100);h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,b,d)};this._init()}
function CMain(a){var d,c=0,f=0,h=STATE_LOADING,b,e,g;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!0;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(FPS),$("body").on("contextmenu","#canvas",function(b){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;e=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){c++;e.refreshLoader(Math.floor(c/f*100));c===f&&this._onPreloaderComplete()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/missile_explosion.ogg","missile_explosion"),createjs.Sound.registerSound("./sounds/missile_launch.ogg","missile_launch"),createjs.Sound.registerSound("./sounds/missile_sink.ogg","missile_sink"),createjs.Sound.registerSound("./sounds/missile_torpedo.ogg",
"missile_torpedo"),createjs.Sound.registerSound("./sounds/missile_water.ogg","missile_water"),createjs.Sound.registerSound("./sounds/air_strike.ogg","air_strike"),createjs.Sound.registerSound("./sounds/sonar.ogg","sonar")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/game_over.mp3",
"game_over"),createjs.Sound.registerSound("./sounds/missile_explosion.mp3","missile_explosion"),createjs.Sound.registerSound("./sounds/missile_launch.mp3","missile_launch"),createjs.Sound.registerSound("./sounds/missile_sink.mp3","missile_sink"),createjs.Sound.registerSound("./sounds/missile_torpedo.mp3","missile_torpedo"),createjs.Sound.registerSound("./sounds/missile_water.mp3","missile_water"),createjs.Sound.registerSound("./sounds/air_strike.mp3","air_strike"),createjs.Sound.registerSound("./sounds/sonar.mp3",
"sonar")),f+=9)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_not","./sprites/but_not.png");s_oSpriteLibrary.addSprite("but_shuffle",
"./sprites/but_shuffle.png");s_oSpriteLibrary.addSprite("but_delete","./sprites/but_delete.png");s_oSpriteLibrary.addSprite("but_rotate","./sprites/but_rotate.png");s_oSpriteLibrary.addSprite("but_classic","./sprites/but_classic.png");s_oSpriteLibrary.addSprite("but_advanced","./sprites/but_advanced.png");s_oSpriteLibrary.addSprite("but_help","./sprites/but_help.png");s_oSpriteLibrary.addSprite("bg_sandbox_menu","./sprites/bg_sandbox_menu.jpg");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");
s_oSpriteLibrary.addSprite("bg_mode","./sprites/bg_mode.jpg");s_oSpriteLibrary.addSprite("score_panel","./sprites/score_panel.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("highlight","./sprites/highlight.png");s_oSpriteLibrary.addSprite("occupied_area","./sprites/occupied_area.png");s_oSpriteLibrary.addSprite("control_panel",
"./sprites/control_panel.png");s_oSpriteLibrary.addSprite("cell_control","./sprites/cell_control.png");s_oSpriteLibrary.addSprite("cell_battle","./sprites/cell_battle.png");for(var b=0;6>b;b++)s_oSpriteLibrary.addSprite("fill_"+b,"./sprites/ships/fill_"+b+".png"),s_oSpriteLibrary.addSprite("shape_"+b,"./sprites/ships/shape_"+b+".png"),s_oSpriteLibrary.addSprite("ship"+b,"./sprites/ships/ship"+b+".png"),s_oSpriteLibrary.addSprite("ship"+b+"_3d","./sprites/ships/ship"+b+"_3d.png");s_oSpriteLibrary.addSprite("final_explosion",
"./sprites/final_explosion.png");s_oSpriteLibrary.addSprite("torpedo","./sprites/torpedo.png");s_oSpriteLibrary.addSprite("missile","./sprites/missile.png");s_oSpriteLibrary.addSprite("missile_reactor","./sprites/missile_reactor.png");s_oSpriteLibrary.addSprite("missile_smoke","./sprites/missile_smoke.png");s_oSpriteLibrary.addSprite("missile_water","./sprites/missile_water.png");s_oSpriteLibrary.addSprite("missile_explosion","./sprites/missile_explosion.png");s_oSpriteLibrary.addSprite("fire","./sprites/fire.png");
for(b=0;37>=b;b++)s_oSpriteLibrary.addSprite("surface_"+b,"./sprites/sea_caustics/surface_"+b+".jpg");s_oSpriteLibrary.addSprite("bg_rocks","./sprites/bg_rocks.png");s_oSpriteLibrary.addSprite("enemy_fleet_panel","./sprites/enemy_fleet_panel.png");s_oSpriteLibrary.addSprite("your_fleet_panel","./sprites/your_fleet_panel.png");s_oSpriteLibrary.addSprite("wait_player","./sprites/wait_player.png");s_oSpriteLibrary.addSprite("but_air_strike","./sprites/but_air_strike.png");s_oSpriteLibrary.addSprite("but_radar",
"./sprites/but_radar.png");s_oSpriteLibrary.addSprite("air","./sprites/air.png");s_oSpriteLibrary.addSprite("air_shadow","./sprites/air_shadow.png");s_oSpriteLibrary.addSprite("sea_mobile","./sprites/sea_mobile.jpg");f+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;e.refreshLoader(Math.floor(c/f*100));c===f&&this._onPreloaderComplete()};this._onAllImagesLoaded=function(){};this._onPreloaderComplete=function(){e.unload();isIOS()||(s_oSoundtrack=
playSound("soundtrack",1,-1));this.gotoMenu();new CAnimationSettings};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;h=STATE_MENU};this.gotoModeMenu=function(){new CModeMenu;h=STATE_MENU};this.gotoSandBoxMenu=function(){new CSandBoxMenu;h=STATE_MENU};this.gotoGame=function(a){g=new CGame(b,a);h=STATE_GAME};this.gotoHelp=function(){new CHelp;h=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");
createjs.Sound.setMute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this._update=function(b){if(!1!==d){var a=(new Date).getTime();s_iTimeElaps=a-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=a;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&g.update();s_oStage.update(b)}};s_oMain=this;b=a;ENABLE_FULLSCREEN=a.fullscreen;
ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bFullscreen=!1,s_iMode,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack,s_oCanvas;
function CTextButton(a,d,c,f,h,b,e){var g,m,k,p,l;this._init=function(b,a,c,e,h,d,f){g=[];m=[];var n=createBitmap(c),q=Math.ceil(f/20);l=new createjs.Text(e," "+f+"px "+h,"#000000");l.textAlign="center";l.textBaseline="alphabetic";var r=l.getBounds();l.x=c.width/2+q;l.y=Math.floor(c.height/2)+r.height/3+q;p=new createjs.Text(e," "+f+"px "+h,d);p.textAlign="center";p.textBaseline="alphabetic";r=p.getBounds();p.x=c.width/2;p.y=Math.floor(c.height/2)+r.height/3;k=new createjs.Container;k.x=b;k.y=a;k.regX=
c.width/2;k.regY=c.height/2;k.addChild(n,l,p);s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown");k.off("pressup");s_oStage.removeChild(k)};this.setVisible=function(b){k.visible=b};this._initListener=function(){oParent=this;k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,c){g[b]=a;m[b]=c};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(m[ON_MOUSE_UP])};this.buttonDown=
function(){k.scaleX=.9;k.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN])};this.setTextPosition=function(b){p.y=b;l.y=b+2};this.setPosition=function(b,a){k.x=b;k.y=a};this.setX=function(b){k.x=b};this.setY=function(b){k.y=b};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(a,d,c,f,h,b,e);return this}
function CToggle(a,d,c,f,h){var b,e,g,m,k,p,l,n,q;this._init=function(a,c,g,h,d){e=!1;l=[];n=[];var f=new createjs.SpriteSheet({images:[g],frames:{width:g.width/2,height:g.height,regX:g.width/2/2,regY:g.height/2},animations:{state_true:[0],state_false:[1]}});b=h;q=createSprite(f,"state_"+b,g.width/2/2,g.height/2,g.width/2,g.height);q.x=a;q.y=c;q.stop();d.addChild(q);this._initListener()};this.setVisible=function(b){q.visible=b};this.unload=function(){s_bMobile?q.off("mousedown",g):(q.off("mousedown",
g),q.off("mouseover",k),q.off("mouseout",p));q.off("pressup",m);h.removeChild(q)};this._initListener=function(){s_bMobile?g=q.on("mousedown",this.buttonDown):(g=q.on("mousedown",this.buttonDown),k=q.on("mouseover",this.buttonOver),p=q.on("mouseout",this.buttonOut));m=q.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,c){l[b]=a;n[b]=c};this.setActive=function(a){b=a;q.gotoAndStop("state_"+b)};this.buttonRelease=function(){e||(q.scaleX=1,q.scaleY=1,!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||createjs.Sound.play("click"),b=!b,q.gotoAndStop("state_"+b),l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(n[ON_MOUSE_UP],b))};this.buttonDown=function(){e||(q.scaleX=.9,q.scaleY=.9,l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN]))};this.buttonOver=function(b){s_bMobile||e||(b.target.cursor="pointer",l[ON_MOUSE_OVER]&&l[ON_MOUSE_OVER].call(n[ON_MOUSE_OVER]))};this.buttonOut=function(b){s_bMobile||e||(b.target.cursor="pointer",l[ON_MOUSE_OUT]&&l[ON_MOUSE_OUT].call(n[ON_MOUSE_OUT]))};this.setPosition=
function(b,a){q.x=b;q.y=a};this.getPos=function(){return{x:q.x,y:q.y}};this.setClickable=function(b){e=!b};this.enable=function(b){b?(q.gotoAndPlay("state_true"),this.setClickable(!0)):(q.gotoAndPlay("state_false"),this.setClickable(!1))};this._init(a,d,c,f,h)}
function CGfxButton(a,d,c,f){var h,b,e,g,m,k,p,l,n,q;this._init=function(a,c,g,e){h=!1;b=1;p=[];l=[];n=new createjs.Container;n.x=a;n.y=c;e.addChild(n);a=createBitmap(g);a.scaleX=n.scaleY=b;a.regX=g.width/2;a.regY=g.height/2;n.addChild(a);this._initListener()};this.unload=function(){s_bMobile?n.off("mousedown",e):(n.off("mousedown",e),n.off("mouseover",m),n.off("mouseout",k));n.off("pressup",g);f.removeChild(n)};this.setVisible=function(b){n.visible=b};this.setClickable=function(b){h=!b};this._initListener=
function(){s_bMobile?e=n.on("mousedown",this.buttonDown):(e=n.on("mousedown",this.buttonDown),m=n.on("mouseover",this.buttonOver),k=n.on("mouseout",this.buttonOut));g=n.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,c){p[b]=a;l[b]=c};this.buttonRelease=function(){h||(n.scaleX=b,n.scaleY=b,p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(l[ON_MOUSE_UP]))};this.buttonDown=function(){h||(n.scaleX=.9*b,n.scaleY=.9*b,playSound("click",1,0),p[ON_MOUSE_DOWN]&&p[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN]))};
this.buttonOver=function(b){s_bMobile||h||(b.target.cursor="pointer")};this.buttonOut=function(b){s_bMobile||h||(b.target.cursor="pointer",p[ON_MOUSE_OUT]&&p[ON_MOUSE_OUT].call(l[ON_MOUSE_OUT]))};this.pulseAnimation=function(){createjs.Tween.get(n).to({scaleX:.9*b,scaleY:.9*b},850,createjs.Ease.quadOut).to({scaleX:b,scaleY:b},650,createjs.Ease.quadIn).call(function(){q.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(n).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},
140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){q.trebleAnimation()})};this.setPosition=function(b,a){n.x=b;n.y=a};this.setX=function(b){n.x=b};this.setY=function(b){n.y=b};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this.setText=function(b,a,c){b=new createjs.Text(b," 44px "+SECONDARY_FONT,"#1ef400");b.textAlign="center";b.textBaseline="middle";b.x=a;b.y=c;n.addChild(b)};q=this;this._init(a,
d,c,f);return this}
function CMenu(){var a,d,c,f,h,b,e,g,m,k,p,l,n=null,q=null;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(e);var r=s_oSpriteLibrary.getSprite("but_play");g=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-300,r,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);g.pulseAnimation();r=s_oSpriteLibrary.getSprite("but_info");h=r.height/2+10;b=r.height/2+10;p=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-240,r,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onCreditsBut,
this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r=s_oSpriteLibrary.getSprite("audio_icon"),c=CANVAS_WIDTH-r.height/2-10,f=r.height/2+10,k=new CToggle(c,f,r,s_bAudioActive,s_oStage),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);var r=window.document,t=r.documentElement;n=t.requestFullscreen||t.mozRequestFullScreen||t.webkitRequestFullScreen||t.msRequestFullscreen;q=r.exitFullscreen||r.mozCancelFullScreen||r.webkitExitFullscreen||r.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(n=!1);n&&!inIframe()&&
(r=s_oSpriteLibrary.getSprite("but_fullscreen"),a=h+r.width/2+10,d=r.height/2+10,l=new CToggle(a,d,r,s_bFullscreen,s_oStage),l.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(m);createjs.Tween.get(m).to({alpha:0},1E3).call(function(){m.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){g.unload();g=null;m.visible=!1;p.unload();if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)k.unload(),k=null;n&&!inIframe()&&l.unload();s_oStage.removeChild(e);s_oMenu=e=null};this.refreshButtonPos=function(g,e){p.setPosition(h+g,e+b);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(c-g,e+f);n&&!inIframe()&&l.setPosition(a+g,d+e)};this._onFullscreen=function(){s_bFullscreen?(q.call(window.document),s_bFullscreen=!1):(n.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=
!s_bAudioActive};this._onCreditsBut=function(){new CCreditsPanel};this._onButPlayRelease=function(){this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoModeMenu();!isIOS()||null!==s_oSoundtrack&&void 0!==s_oSoundtrack||(s_oSoundtrack=playSound("soundtrack",1,-1))};s_oMenu=this;this._init()}var s_oMenu=null;
function CModeMenu(){var a,d,c,f,h,b,e,g,m,k,p,l,n;this._init=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_mode"));s_oStage.addChild(k);k=new createjs.Text(TEXT_GAME_MODE," 160px "+SECONDARY_FONT,"#1ef400");k.textAlign="center";k.textBaseline="middle";k.x=CANVAS_WIDTH/2;k.y=260;s_oStage.addChild(k);k=s_oSpriteLibrary.getSprite("but_classic");g=new CGfxButton(CANVAS_WIDTH/2-220,CANVAS_HEIGHT/2+100,k,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onClassicBut,this);g.setText(TEXT_CLASSIC,
0,76);k=s_oSpriteLibrary.getSprite("but_advanced");m=new CGfxButton(CANVAS_WIDTH/2+220,CANVAS_HEIGHT/2+100,k,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onAdvancedBut,this);m.setText(TEXT_ADVANCED,0,76);k=s_oSpriteLibrary.getSprite("but_help");a=k.height/2+10;d=k.height/2+10;n=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-240,k,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onHelpBut,this);k=s_oSpriteLibrary.getSprite("but_exit");h=CANVAS_WIDTH-k.height/2-10;b=k.height/2+10;p=new CGfxButton(h,b,
k,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onExit,this);c=CANVAS_WIDTH-k.width/2-110;f=k.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=s_oSpriteLibrary.getSprite("audio_icon"),l=new CToggle(c,f,k,s_bAudioActive,s_oStage),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(e);createjs.Tween.get(e).to({alpha:0},1E3).call(function(){e.visible=!1});this.refreshButtonPos(s_iOffsetX,
s_iOffsetY)};this.unload=function(){s_oStage.removeAllChildren();m.unload();g.unload();p.unload();l.unload();n.unload();s_oModeMenu=null};this.refreshButtonPos=function(g,e){n.setPosition(a+g,e+d);p.setPosition(h-g,e+b);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(c-g,e+f)};this._onHelpBut=function(){new CHelpPanel};this._onExit=function(){this.unload();s_oMain.gotoMenu()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onClassicBut=
function(){k.unload();s_iMode=MODE_CLASSIC;s_oMain.gotoSandBoxMenu()};this._onAdvancedBut=function(){k.unload();s_iMode=MODE_ADVANCED;s_oMain.gotoSandBoxMenu()};s_oModeMenu=this;k=this;this._init()}var s_oModeMenu=null;
function CGame(a,d){var c,f,h,b,e=0,g,m,k,p,l=null,n,q,r,t,v,u,w,x,y,B,z,A,D,C;this._init=function(){setVolume(s_oSoundtrack,.4);$(s_oMain).trigger("start_level",1);c=!0;f=0;b=PLAYER;g=0;h=1;u=new CBackground(s_oStage);w=new createjs.Container;s_oStage.addChild(w);k=d;this._initEnemyBoard();x=new createjs.Container;s_oStage.addChild(x);y=new createjs.Container;s_oStage.addChild(y);q=new CPlayerBoard(CANVAS_WIDTH/2-150,CANVAS_HEIGHT/2+100,x,k,PLAYER,y);r=new CPlayerBoard(CANVAS_WIDTH/2+150,CANVAS_HEIGHT/
2-200,x,m,OPPONENT,y);t=new CMissile(y,w);A=new CTurnWaiter(s_oStage);v=null;D=new CAirStrike(x);p=new CInterface;p.refreshScore(f);if(!s_bMobile)s_oStage.on("stagemousemove",this.setMouseCoordinate);n=new CControlPanel;n.show();B=new CAI(q);z=new createjs.Shape;z.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(z);createjs.Tween.get(z).to({alpha:0},1E3).call(function(){z.visible=!1})};this._initEnemyBoard=function(){var b=new CSandBoxBoard(0,0,s_oStage,!1);m=
[];m[0]=new CShip(400,200,SHIP_SMALL,s_oStage,b);m[1]=new CShip(400,300,SHIP_SUB,s_oStage,b);m[2]=new CShip(400,400,SHIP_MEDIUM,s_oStage,b);m[3]=new CShip(400,500,SHIP_LONG,s_oStage,b);m[4]=new CShip(400,600,SHIP_BATTLE,s_oStage,b);m[5]=new CShip(400,700,SHIP_CARRIER,s_oStage,b);b.shuffle(m);for(var a=0;a<m.length;a++)m[a].unload();b.unload()};this.tryShowAd=function(){e++;e===AD_SHOW_COUNTER&&(e=0,$(s_oMain).trigger("show_interlevel_ad"))};this.onCellClick=function(b,a){n.hide();g=1;t.launchMissileForPlayer(b,
a)};this.onMissileArrived=function(a,c){var e=[r,q],d=e[b].isShipOn(a,c);if(null!==d){if(d.hitShip(a,c),e[b].setCellState(a,c,CELL_STATE_HIT),b===OPPONENT?(e[b].setFire(a,c),s_oGame.addScore(-POINTS_TO_LOSE)):(s_oGame.addScore(h*POINTS_EARNED),h++),e[b].playExplosion(a,c),d.isSunk()){for(var f=d.getListCellOccupied(),l=0;l<f.length;l++)for(var t=s_oBoardUtility.getAllNeighbor(f[l].row,f[l].col),x=0;x<t.length;x++)e[b].setCellState(t[x].row,t[x].col,CELL_STATE_WATER);for(l=0;l<f.length;l++)e[b].setCellState(f[l].row,
f[l].col,CELL_STATE_SUNK);b===OPPONENT&&B.resetToStartState();e[b].sunkAnimation(d)}}else e[b].setCellState(a,c,CELL_STATE_WATER),e[b].playWater(a,c),b===PLAYER&&(h=1);n.refresh(r.getCells());b===OPPONENT?p.setShipDamage(k):p.setEnemySunk(m);g--;0===g&&(this.tryShowAd(),this.changeTurn())};this.changeTurn=function(){this.checkEndGame()||(b===PLAYER?(b=OPPONENT,this._wakeUpAI()):(b=PLAYER,setTimeout(function(){n.show()},1E3)))};this._wakeUpAI=function(){A.show();g=1;var b=randomFloatBetween(MIN_AI_THINKING,
MAX_AI_THINKING),a;v=new Timer(function(){a=B.getCoordinate(k);t.launchMissileForOpponent(a.row,a.col);A.hide();v=null},b)};this.checkEndGame=function(){for(var b=!0,a=0;a<m.length;a++)if(!m[a].isSunk()){b=!1;break}for(var c=!0,a=0;a<k.length;a++)if(!k[a].isSunk()){c=!1;break}b?this.gameOver(PLAYER):c&&this.gameOver(OPPONENT);return b||c};this.setNumMissileShot=function(b){g=b};this.getRandomAvailableShip=function(b){for(var a=[k,m],c=[],g=0;g<a[b].length;g++)a[b][g].isSunk()||c.push(a[b][g]);return c[Math.floor(Math.random()*
c.length)]};this.getCellPos=function(b,a,c){return c===OPPONENT?r.getCellPos(b,a):q.getCellPos(b,a)};this.getBoardPos=function(b){if(b===PLAYER)return q.getPos();b=r.getBounds();var a=r.getPos();return{x:a.x-b.width/2,y:a.y}};this.getBoard=function(b){return b===PLAYER?q:r};this.launchAirStrike=function(){D.launch()};this.addScore=function(b){f+=b;0>=f&&(f=0);p.refreshScore(f)};this.getScore=function(){return f};this.restartGame=function(){$(s_oMain).trigger("show_interlevel_ad");this.unload();this._init()};
this.pauseGame=function(b){c=!b;null!==v&&(c?v.resume():v.pause())};this.unload=function(){c=!1;p.unload();null!==l&&l.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){$(s_oMain).trigger("end_session");s_oGame.unload();s_oMain.gotoMenu()};this._onExitHelp=function(){c=!0;$(s_oMain).trigger("start_level",1)};this.gameOver=function(b){l=CEndPanel(b);l.show(f)};this.setMouseCoordinate=function(b){C={x:b.stageX,y:b.stageY}};this.getMouseCoordinate=function(){return C};
this.update=function(){c&&(null!==A&&A.update(),t.update(),u.update(),n.update(C))};s_oGame=this;POINTS_TO_LOSE=a.points_to_lose;POINTS_EARNED=a.points_earned;AD_SHOW_COUNTER=a.ad_show_counter;this._init()}var s_oGame;
function CInterface(){var a,d,c,f,h,b,e,g,m,k,p,l=null,n,q=null,r=null;this._init=function(){var l=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-l.height/2-10;g=l.height/2+10;k=new CGfxButton(e,g,l,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onExit,this);h=CANVAS_WIDTH-l.width/2-110;b=l.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l=s_oSpriteLibrary.getSprite("audio_icon"),m=new CToggle(h,b,l,s_bAudioActive,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);
var l=window.document,v=l.documentElement;q=v.requestFullscreen||v.mozRequestFullScreen||v.webkitRequestFullScreen||v.msRequestFullscreen;r=l.exitFullscreen||l.mozCancelFullScreen||l.webkitExitFullscreen||l.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(q=!1);q&&!inIframe()&&(l=s_oSpriteLibrary.getSprite("but_fullscreen"),c=l.width/4+10,f=l.height/2+10,p=new CToggle(c,f,l,s_bFullscreen,s_oStage),p.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));a=0;d=CANVAS_HEIGHT;n=new CSummaryPanel(a,d,s_oStage);
this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;k.unload();q&&!inIframe()&&p.unload();s_oInterface=null};this.refreshButtonPos=function(l,r){k.setPosition(e-l,r+g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(h-l,r+b);q&&!inIframe()&&p.setPosition(c+l,f+r);n.setPos(a+l,d-r)};this.refreshScore=function(b){n.setScore(b)};this.setShipDamage=function(b){n.setDamage(b)};this.setEnemySunk=function(b){n.setEnemySunk(b)};
this._onButHelpRelease=function(){l=new CHelpPanel};this.onExitFromHelp=function(){l.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){new CAreYouSurePanel(s_oGame.onExit)};this._onFullscreen=function(){s_bFullscreen?(r.call(window.document),s_bFullscreen=!1):(q.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,d,c,f,h,b;this._init=function(){c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;d=c.on("mousedown",this.unload);s_oStage.addChild(c);(new createjs.Tween.get(c)).to({alpha:.7},500);f=new createjs.Container;s_oStage.addChild(f);var e=s_oSpriteLibrary.getSprite("control_panel"),g=createBitmap(e);g.regX=e.width/2;g.regY=e.height/2;f.addChild(g);f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT+e.height/2;a=f.y;(new createjs.Tween.get(f)).to({y:CANVAS_HEIGHT/
2},500,createjs.Ease.quartIn);g=new createjs.Text(TEXT_HELP," 120px "+SECONDARY_FONT,"#1ef400");g.y=-e.height/2+100;g.textAlign="center";g.textBaseline="middle";g.lineWidth=300;f.addChild(g);e=new createjs.Text(TEXT_CLASSIC+":"," 40px "+SECONDARY_FONT,"#1ef400");e.x=-550;e.y=-200;e.textAlign="left";e.textBaseline="alphabetic";e.lineWidth=1200;f.addChild(e);g=new createjs.Text(TEXT_HELP_CLASSIC," 34px "+PRIMARY_FONT,"#ffffff");g.x=e.x+e.getBounds().width+10;g.y=e.y;g.textAlign="left";g.textBaseline=
"alphabetic";g.lineWidth=1E3;f.addChild(g);g=new createjs.Text(TEXT_ADVANCED+":"," 40px "+SECONDARY_FONT,"#1ef400");g.x=-550;g.y=0;g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=1200;f.addChild(g);var m=new createjs.Text(TEXT_HELP_ADVANCED," 34px "+PRIMARY_FONT,"#ffffff");m.x=g.x+g.getBounds().width+10;m.y=g.y;m.textAlign="left";m.textBaseline="alphabetic";m.lineWidth=1E3;f.addChild(m);e=s_oSpriteLibrary.getSprite("but_air_strike");h=new CToggle(m.x+e.width/4,g.y+100,e,!0,f);h.setClickable(!1);
g=new createjs.Text(TEXT_HELP_AIRSTRIKE," 34px "+PRIMARY_FONT,"#ffffff");g.x=h.getPos().x+e.width/4+10;g.y=h.getPos().y;g.textAlign="left";g.textBaseline="middle";g.lineWidth=800;f.addChild(g);b=new CAnimatedButton(h.getPos().x,h.getPos().y+150,s_oRadarSpritesheet,f);b.enable(!0);b.setClickable(!1);g=new createjs.Text(TEXT_HELP_RADAR," 34px "+PRIMARY_FONT,"#ffffff");g.x=h.getPos().x+e.width/4+10;g.y=h.getPos().y+134;g.textAlign="left";g.textBaseline="middle";g.lineWidth=800;f.addChild(g)};this.unload=
function(){(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(f)).to({y:a},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(c);s_oStage.removeChild(f);h.unload();b.unload()});c.off("mousedown",d)};this._init()}
function CCreditsPanel(){var a,d,c,f,h;this._init=function(){d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;d.on("mousedown",function(){});s_oStage.addChild(d);(new createjs.Tween.get(d)).to({alpha:.7},500);c=new createjs.Container;s_oStage.addChild(c);var b=s_oSpriteLibrary.getSprite("msg_box"),e=createBitmap(b);e.regX=b.width/2;e.regY=b.height/2;c.addChild(e);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT+b.height/2;a=c.y;(new createjs.Tween.get(c)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);e=new createjs.Text("DEVELOPED BY"," 30px "+SECONDARY_FONT,"#1ef400");e.y=-b.height/2+100;e.textAlign="center";e.textBaseline="middle";e.lineWidth=300;c.addChild(e);b=new createjs.Text("www.codethislab.com"," 30px "+SECONDARY_FONT,"#1ef400");b.y=80;b.textAlign="center";b.textBaseline="middle";b.lineWidth=300;c.addChild(b);b=s_oSpriteLibrary.getSprite("ctl_logo");h=createBitmap(b);h.on("mousedown",this._onLogoButRelease);h.regX=b.width/2;h.regY=b.height/2;c.addChild(h);
b=s_oSpriteLibrary.getSprite("but_exit");f=new CGfxButton(210,-122,b,c);f.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){f.setClickable(!1);(new createjs.Tween.get(d)).to({alpha:0},500);(new createjs.Tween.get(c)).to({y:a},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(d);s_oStage.removeChild(c);f.unload()});d.off("mousedown",function(){});h.off("mousedown",this._onLogoButRelease)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};
this._onMoreGamesReleased=function(){window.open("http://codecanyon.net/collections/5409142-games")};this._init()}
function CAreYouSurePanel(a){var d,c,f,h,b,e;this._init=function(a){s_oGame.pauseGame(!0);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;h.on("mousedown",function(){});s_oStage.addChild(h);(new createjs.Tween.get(h)).to({alpha:.7},500);b=new createjs.Container;s_oStage.addChild(b);a=s_oSpriteLibrary.getSprite("msg_box");var g=createBitmap(a);g.regX=a.width/2;g.regY=a.height/2;b.addChild(g);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT+a.height/2;d=b.y;
(new createjs.Tween.get(b)).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartIn);g=new createjs.Text(TEXT_ARE_SURE," 50px "+SECONDARY_FONT,"#000000");g.y=-a.height/2+120;g.textAlign="center";g.textBaseline="middle";g.lineWidth=400;g.outline=5;b.addChild(g);a=new createjs.Text(TEXT_ARE_SURE," 50px "+SECONDARY_FONT,"#1ef400");a.y=g.y;a.textAlign="center";a.textBaseline="middle";a.lineWidth=400;b.addChild(a);c=new CGfxButton(110,80,s_oSpriteLibrary.getSprite("but_yes"),b);c.addEventListener(ON_MOUSE_UP,
this._onButYes,this);f=new CGfxButton(-110,80,s_oSpriteLibrary.getSprite("but_not"),b);f.addEventListener(ON_MOUSE_UP,this._onButNo,this);f.pulseAnimation()};this._onButYes=function(){f.setClickable(!1);c.setClickable(!1);s_oGame.pauseGame(!1);(new createjs.Tween.get(h)).to({alpha:0},500);(new createjs.Tween.get(b)).to({y:d},400,createjs.Ease.backIn).call(function(){e.unload();a()})};this._onButNo=function(){f.setClickable(!1);c.setClickable(!1);s_oGame.pauseGame(!1);(new createjs.Tween.get(h)).to({alpha:0},
500);(new createjs.Tween.get(b)).to({y:d},400,createjs.Ease.backIn).call(function(){e.unload()})};this.unload=function(){f.unload();c.unload();s_oStage.removeChild(h);s_oStage.removeChild(b);h.off("mousedown",function(){})};e=this;this._init(a)}
function CEndPanel(a){var d,c,f,h,b,e,g,m,k;this._init=function(a){d=null;setVolume(s_oSoundtrack,1);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=.7;a=s_oSpriteLibrary.getSprite("msg_box");f=createBitmap(a);f.regX=a.width/2;f.regY=a.height/2;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;e=new createjs.Text(""," 100px "+SECONDARY_FONT,"#000");e.x=CANVAS_WIDTH/2+1;e.y=CANVAS_HEIGHT/2-50;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=500;
g=new createjs.Text(""," 100px "+SECONDARY_FONT,"#1ef400");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-52;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=500;m=new createjs.Text(""," 40px "+SECONDARY_FONT,"#000");m.x=CANVAS_WIDTH/2+1;m.y=CANVAS_HEIGHT/2+50;m.textAlign="center";m.textBaseline="alphabetic";m.lineWidth=500;k=new createjs.Text(""," 40px  "+SECONDARY_FONT,"#1ef400");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2+52;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=500;h=new createjs.Container;
h.alpha=0;h.visible=!1;h.addChild(b,f,m,k,e,g);s_oStage.addChild(h)};this.unload=function(){null!==d&&clearTimeout(d);h.off("mousedown",this._onExit)};this._initListener=function(){h.on("mousedown",this._onExit)};this.show=function(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");a===PLAYER?(e.text=TEXT_WIN,g.text=TEXT_WIN,this._winnerAnim()):(e.text=TEXT_LOSE,g.text=TEXT_LOSE,this._loseAnim());m.text=TEXT_SCORE+": "+b;k.text=TEXT_SCORE+": "+b;h.visible=!0;var c=this;
createjs.Tween.get(h).to({alpha:1},500).call(function(){c._initListener()});$(s_oMain).trigger("save_score",b,s_iMode);$(s_oMain).trigger("end_level",1);var d="You collected <strong>"+b+" points</strong>!<br><br>Share your score with your friends!",f="My score is "+b+" points! Can you do better?";$(s_oMain).trigger("share_event",b,"200x200.jpg","Congratulations!",d,f)};this._winnerAnim=function(){d=setTimeout(function(){(new CAirStrike(h)).endAnim({x:CANVAS_WIDTH+(200+200*Math.random()),y:CANVAS_HEIGHT+
(-400-200*Math.random())},{x:-250-250*Math.random(),y:-300-300*Math.random()},2E3+2E3*Math.random());c._winnerAnim()},1E3+1E3*Math.random())};this._loseAnim=function(){d=setTimeout(function(){var b=new createSprite(s_oMissileExplosionSpritesheet,"idle",0,0,0,0);b.on("animationend",this._endExplosion,this,!1,{missile:b});playSound("missile_explosion",1,0);b.x=CANVAS_WIDTH*Math.random();b.y=CANVAS_HEIGHT*Math.random();h.addChild(b);c._loseAnim()},400+400*Math.random())};this._endExplosion=function(b,
a){b.remove();h.removeChild(a.missile)};this._onExit=function(){$(s_oMain).trigger("show_interlevel_ad");h.off("mousedown",this._onExit);s_oStage.removeChild(h);s_oGame.onExit()};this._init(a);c=this;return this}
function CSandBoxBoard(a,d,c,f){var h,b,e;this._init=function(a,c,d,f){b=[];e=null;this._initBoard();new CBoardUtility(h)};this.unload=function(){c.removeChild();for(var b=0;b<NUM_CELL;b++)for(var a=0;a<NUM_CELL;a++)h[b][a].unload()};this.getSandBoxMode=function(){return f};this._initBoard=function(){var b=NUM_CELL,a=CELL_LENGTH,e=-BOARD_LENGTH/2+a/2;h=[];for(var d=0;d<b;d++){h[d]=[];for(var l=0;l<b;l++)h[d][l]=new CSandBoxCell(e+l*a+-2,e+d*a+54,d,l,c),h[d][l].setVisible(f)}};this.snapFromRelease=
function(b){this.snapShip(e,b)};this.snapShip=function(a,e){var g=e.getShipContainer();if(null!==a){var d=this._checkFreeCells(a.row,a.col,e);if(d.free){var l=h[a.row][a.col],l=c.localToGlobal(l.getPos().x,l.getPos().y);g.x=l.x/s_iScaleFactor;g.y=l.y/s_iScaleFactor;this.setDeniedArea(d.list);e.setListCellOccupied(d.list);b.push(e);this.hideHighlight();this.printDebug()}else this.resetShip(e)}else this.resetShip(e);f&&s_oSandBoxMenu.checkPlayable()};this._checkFreeCells=function(b,a,c){c=c.getMap();
for(var e=[],g=!0,d=0;d<c.length;d++)for(var f=0;f<c[d].length;f++){var m=b+d,k=a+f;if(m>=NUM_CELL||k>=NUM_CELL||h[m][k].isShipOn())return g=!1,{free:g,list:[]};e.push({row:m,col:k})}return{free:g,list:e}};this.setShipOnCell=function(b,a){for(var c=0;c<b.length;c++)h[b[c].row][b[c].col].setShip(a)};this.resetShip=function(b){this.hideHighlight();var a=b.getListCellOccupied();this.setShipOnCell(a,!1);b.returnInStartPos()};this._findShipPos=function(b){b=b.getShipContainer();b=s_oStage.localToLocal(b.x,
b.y,c);for(var a=null,e=0;e<NUM_CELL;e++)for(var g=0;g<NUM_CELL;g++){var d=h[e][g],f=b.x-d.getPos().x,q=b.y-d.getPos().y;d.hitTest(f,q)&&(a={row:e,col:g})}return a};this._findAllPiecesPos=function(b,a,c){var e=[];e.push({row:b,col:a});for(var g=0;g<c.length;g++)for(var d=0;d<c[g].length;d++){var f=b+g,h=a+d;f<NUM_CELL&&h<NUM_CELL&&e.push({row:f,col:h})}return e};this.setDeniedArea=function(b){for(var a=[],c=0;c<b.length;c++){h[b[c].row][b[c].col].highlightDeniedArea(!0);a.push({row:b[c].row,col:b[c].col});
for(var e=s_oBoardUtility.getAllNeighbor(b[c].row,b[c].col),g=0;g<e.length;g++){var d=e[g].row,f=e[g].col;h[d][f].highlightDeniedArea(!0);a.push({row:d,col:f})}}this.setShipOnCell(a,!0)};this.highlightSnap=function(b){this.hideHighlight();var a=this._findShipPos(b);if(null!==a){b=this._findAllPiecesPos(a.row,a.col,b.getMap());for(var c=0;c<b.length;c++)h[b[c].row][b[c].col].highlight(!0)}e=a};this.hideHighlight=function(){for(var b=0;b<NUM_CELL;b++)for(var a=0;a<NUM_CELL;a++)h[b][a].highlight(!1)};
this.removeAllDenied=function(){for(var b=0;b<NUM_CELL;b++)for(var a=0;a<NUM_CELL;a++)h[b][a].highlightDeniedArea(!1),h[b][a].setShip(!1)};this.refreshDenied=function(){this.removeAllDenied();for(var a=0;a<b.length;a++)this.setDeniedArea(b[a].getListCellOccupied())};this.removeShip=function(a){for(var c=0;c<b.length;c++)b[c]===a&&(b[c].setListCellOccupied([]),b.splice(c,1));this.refreshDenied();this.highlightSnap(a);this.printDebug()};this.shuffle=function(b){this.clearAll(b);for(var a=0;a<b.length;a++)for(var c=
b[a].getListCellOccupied(),e=100;0===c.length;){var c=Math.floor(Math.random()*NUM_CELL),g=Math.floor(Math.random()*NUM_CELL);.5>Math.random()&&b[a].rotateMap();this.snapShip({row:c,col:g},b[a]);c=b[a].getListCellOccupied();e--;0===e&&this.shuffle(b)}};this.clearAll=function(b){for(var a=0;a<b.length;a++)b[a].isHorizontal()&&b[a].rotateMap(),this.removeShip(b[a]),this.resetShip(b[a])};this.printDebug=function(){for(var b=[],a=0;a<h.length;a++){b[a]=[];for(var c=0;c<h[a].length;c++)void 0!==h[a][c]&&
(h[a][c].isShipOn()?b[a][c]=1:b[a][c]=0)}this.printMat(b)};this.printMat=function(b){for(var a=0;a<b.length;a++)for(var c=0;c<b[a].length;c++);};this._init(a,d,c,f)}
function CSandBoxCell(a,d,c,f,h){var b,e,g,m,k,p;this._init=function(a,c,d,f,h){b=!1;e=new createjs.Container;e.x=a;e.y=c;h.addChild(e);g=null;a=s_oSpriteLibrary.getSprite("highlight");p=createBitmap(a);p.regX=a.width/2;p.regY=a.height/2;p.alpha=.8;p.visible=!1;e.addChild(p);a=s_oSpriteLibrary.getSprite("occupied_area");k=createBitmap(a);k.regX=a.width/2;k.regY=a.height/2;k.visible=!1;e.addChild(k);m=new createjs.Shape;m.graphics.beginFill("rgba(158,0,0,0.01)").drawRect(-CELL_LENGTH/2,-CELL_LENGTH/
2,CELL_LENGTH,CELL_LENGTH);e.addChild(m)};this.unload=function(){h.removeChild(e)};this.setClickableArea=function(b){m.visible=b};this.highlightDeniedArea=function(b){k.visible=b};this.highlight=function(b){p.visible=b};this.isHighlight=function(){return p.visible};this._onCellClick=function(){};this.setActive=function(b){null!==g&&g.setActive(b)};this.setVisible=function(b){e.visible=b};this.setShip=function(a){b=a};this.isShipOn=function(){return b};this.getPos=function(){return{x:a,y:d}};this.getLogicPos=
function(){return{row:c,col:f}};this.hitTest=function(b,a){return e.hitTest(b,a)};this._init(a,d,c,f,h)}
function CSandBoxMenu(a){var d,c,f,h,b,e,g,m,k,p,l,n,q,r,t,v;this._init=function(){n=null;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_sandbox_menu"));s_oStage.addChild(a);e=new createjs.Container;e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;s_oStage.addChild(e);q=new createjs.Text(TEXT_STRATEGY_PANEL," 80px "+SECONDARY_FONT,"#1ef400");q.textAlign="center";q.textBaseline="middle";q.x=CANVAS_WIDTH/2;q.y=160;s_oStage.addChild(q);a=s_oSpriteLibrary.getSprite("but_shuffle");g=new CGfxButton(1450,220,a,
s_oStage);g.addEventListener(ON_MOUSE_UP,this._onAuto,this);a=s_oSpriteLibrary.getSprite("but_delete");m=new CGfxButton(1450,425,a,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onButClear,this);a=s_oSpriteLibrary.getSprite("but_rotate");p=new CGfxButton(1450,630,a,s_oStage);p.setVisible(!1);p.addEventListener(ON_MOUSE_UP,this._onButRotate,this);a=s_oSpriteLibrary.getSprite("but_play");k=new CGfxButton(1472,CANVAS_HEIGHT-226,a,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);
k.setVisible(!1);a=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-a.height/2-10;h=a.height/2+10;t=new CGfxButton(f,h,a,s_oStage);t.addEventListener(ON_MOUSE_UP,this._onExit,this);d=CANVAS_WIDTH-a.width/2-110;c=a.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a=s_oSpriteLibrary.getSprite("audio_icon"),v=new CToggle(d,c,a,s_bAudioActive,s_oStage),v.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);l=new CSandBoxBoard(0,0,e,!0);a=new createjs.Container;s_oStage.addChild(a);b=[];
b[0]=new CShip(300,200,SHIP_SMALL,a,l);b[1]=new CShip(400,156,SHIP_SUB,a,l);b[2]=new CShip(300,440,SHIP_MEDIUM,a,l);b[3]=new CShip(400,390,SHIP_LONG,a,l);b[4]=new CShip(300,700,SHIP_BATTLE,a,l);b[5]=new CShip(400,750,SHIP_CARRIER,a,l);r=new createjs.Shape;r.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(r);createjs.Tween.get(r).to({alpha:0},1E3).call(function(){r.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(b,a){t.setPosition(f-
b,a+h);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||v.setPosition(d-b,a+c)};this.unload=function(){s_oSandBoxMenu=null;g.unload();m.unload();k.unload();s_oStage.removeAllChildren();l.unload();for(var a=0;a<b.length;a++)b[a].unload()};this.setActiveShip=function(b){n=b;null===n?p.setVisible(!1):p.setVisible(!0)};this.getShipList=function(){return b};this._onAuto=function(){l.shuffle(b)};this._onButClear=function(){l.clearAll(b);this.checkPlayable()};this._onButRotate=function(){null!==n&&n._onShipRotate()};
this.onExit=function(){$(s_oMain).trigger("end_session");s_oMain.gotoMenu()};this.checkPlayable=function(){for(var a=!0,c,e=0;e<b.length;e++)c=b[e].getListCellOccupied(),0===c.length&&(a=!1);a?k.setVisible(!0):k.setVisible(!1)};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame(b)};this._onExit=function(){this.unload();s_oMain.gotoMenu()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oSandBoxMenu=this;this._init()}
var s_oSandBoxMenu=null;
function CShip(a,d,c,f,h){var b,e,g,m,k,p,l,n,q,r,t,v,u,w,x,y;this._init=function(b,a,c,e,d){k=d.getSandBoxMode();p=!1;l=-4;n=40;g=b;m=a;q=c.map;r=[];t=[];u=new createjs.Container;u.x=b;u.y=a;k&&(u.on("mousedown",this._onShipClick),u.on("pressmove",this._onShipMove),u.on("dblclick",this._onShipRotate),u.on("pressup",this._onShipRelease),e.addChild(u));this.drawMap();this.drawShip()};this.drawMap=function(){for(var b=0;b<t.length;b++)for(var a=0;a<t[b].length;a++)u.removeChild(t[b][a]);var c=0,e=0;
t=[];for(b=0;b<q.length;b++){t[b]=[];for(a=0;a<q[b].length;a++)if(q[b][a]){var d=new createjs.Shape;d.graphics.beginFill("rgba(158,158,158,0.01)").drawRect(-CELL_LENGTH/2,-CELL_LENGTH/2,CELL_LENGTH,CELL_LENGTH);d.x=c;d.y=e;u.addChild(d);c+=CELL_LENGTH;t[b][a]=d}c=0;e+=CELL_LENGTH}};this.drawShip=function(){w=s_oSpriteLibrary.getSprite(c.sandbox_sprite);x=createBitmap(w);x.regX=w.width/2+l;x.regY=n;c===SHIP_CARRIER&&(x.regX=w.width/4);u.addChild(x);if(k){var b=s_oSpriteLibrary.getSprite("shape_"+c.battle_spritesheet);
y=createBitmap(b);y.x=a;y.y=d;y.regX=w.width/2+l-8;y.regY=n-10;c===SHIP_CARRIER&&(y.regX=w.width/4-8);f.addChild(y)}};this.unload=function(){k&&(u.off("mousedown",this._onShipClick),u.off("pressmove",this._onShipMove),u.off("dblclick",this._onShipRotate),u.off("pressup",this._onShipRelease),f.removeChild(u))};this._onShipClick=function(a){h.removeShip(v);k&&s_oSandBoxMenu.setActiveShip(v);b=a.localX;e=a.localY};this._onShipMove=function(a){u.x-=b-a.localX;u.y-=e-a.localY;b=a.localX;e=a.localY;h.highlightSnap(v)};
this._onShipRelease=function(){h.snapFromRelease(v)};this._onShipRotate=function(){v.rotateMap();h.removeShip(v);h.snapFromRelease(v)};this.rotateMap=function(){(p=!p)?(x.rotation=-90,x.scaleY=-1,x.regY=w.height-n,c===SHIP_CARRIER&&(x.regX=3*w.width/4-2)):(x.rotation=0,x.scaleY=1,x.regY=n,c===SHIP_CARRIER&&(x.regX=w.width/4));q=q[0].map(function(b,a){return q.map(function(b){return b[a]})});v.drawMap();r=[]};this.getShipContainer=function(){return u};this.getMap=function(){return q};this.returnInStartPos=
function(){u.x=g;u.y=m;r=[];p&&this._onShipRotate();k&&s_oSandBoxMenu.setActiveShip(null)};this.setListCellOccupied=function(b){r=[];for(var a=0;a<b.length;a++)r.push(b[a])};this.getListCellOccupied=function(){return r};this.getPos=function(){return{x:u.x,y:u.y}};this.getType=function(){return c};this.isHorizontal=function(){return p};this.hitShip=function(b,a){for(var c=0;c<r.length;c++)r[c].row===b&&r[c].col===a&&(r[c].hit=!0)};this.isPartiallyDamaged=function(){for(var b=!1,a=0;a<r.length;a++)r[a].hit&&
(b=!0);return b};this.isSunk=function(){for(var b=!0,a=0;a<r.length;a++)r[a].hit||(b=!1);return b};this.debugShips=function(){f.addChild(u)};this._init(a,d,c,f,h);v=this}
function CRuler(a){var d,c,f,h,b,e,g;this._init=function(a){d=new createjs.Container;d.x=-CANVAS_WIDTH/2;d.y=-CANVAS_HEIGHT/2;a.addChild(d);c=new createjs.Shape;c.graphics.beginFill("rgba(255,255,255,0.6)").drawRect(0,-1.5,CANVAS_WIDTH,3);d.addChild(c);f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.6)").drawRect(-1.5,0,3,CANVAS_HEIGHT);d.addChild(f);h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(356,118,1208,844);d.addChild(h);c.mask=h;f.mask=h;b=new createjs.Container;
b.mask=h;d.addChild(b);g=new createjs.Text("0"," 34px "+SECONDARY_FONT,"#000000");g.x=54;g.y=-46;g.textAlign="left";g.textBaseline="middle";b.addChild(g);e=new createjs.Text("0"," 34px "+SECONDARY_FONT,"#ffffff");e.x=50;e.y=-50;e.textAlign="left";e.textBaseline="middle";b.addChild(e)};this.updatePos=function(a,d){f.x=a/s_iScaleFactor;c.y=d/s_iScaleFactor;b.x=a/s_iScaleFactor;b.y=d/s_iScaleFactor;var h=parseInt(a),l=parseInt(d);e.text="("+h+","+l+")";g.text="("+h+","+l+")"};this.show=function(b){d.visible=
b};this._init(a)}
function CAI(a){var d,c,f,h,b,e,g,m,k;this._init=function(b){d=AI_STATE_NEW_COORDINATE;c=AI_FIND_DIRECTION;f=[];h=[DIR_RIGHT,DIR_BOT,DIR_LEFT,DIR_TOP];e=[];g=[];k=null};this.getCoordinate=function(b){switch(d){case AI_STATE_NEW_COORDINATE:return this._getRandomCoordinate(b);case AI_STATE_FIND_SHIP_NEIGHBOR:return this._getLastDirectionCoordinate()}};this._getRandomCoordinate=function(e){f=[];for(e=0;e<NUM_CELL;e++)for(var g=0;g<NUM_CELL;g++)a.getCellState(e,g)===CELL_STATE_VOID&&f.push({row:e,col:g});
e=f[Math.floor(Math.random()*f.length)];this._predictHit(e.row,e.col)===PREDICT_HIT&&(c=AI_FIND_DIRECTION,d=AI_STATE_FIND_SHIP_NEIGHBOR,b=[],b.push(e),this._setViableDirection(b[0]));return e};this._getLastDirectionCoordinate=function(){var e;switch(c){case AI_FIND_DIRECTION:k=h[Math.floor(Math.random()*h.length)];e=s_oBoardUtility.getNeighborByDir(b[0].row,b[0].col,k);var d=this._predictHit(e.row,e.col);d===PREDICT_HIT?(c=AI_FOLLOW_DIRECTION,b.push(e)):this._removeDirection();break;case AI_FOLLOW_DIRECTION:e=
b[b.length-1];e=s_oBoardUtility.getNeighborByDir(e.row,e.col,k);if(null===e||a.getCellState(e.row,e.col)===CELL_STATE_WATER)return c=AI_REVERSE_DIRECTION,this._getLastDirectionCoordinate();b.push(e);d=this._predictHit(e.row,e.col);d===PREDICT_WATER&&(c=AI_REVERSE_DIRECTION);break;case AI_REVERSE_DIRECTION:e=k;this._removeDirection();k=s_oBoardUtility.getReverseDirection(e);e=s_oBoardUtility.getNeighborByDir(b[0].row,b[0].col,k);if(null===e||a.getCellState(e.row,e.col)===CELL_STATE_WATER)return this._setCarrierFound(),
this._getLastDirectionCoordinate();d=this._predictHit(e.row,e.col);d===PREDICT_WATER?this._setCarrierFound():c=AI_FOLLOW_REVERSE;b.push(e);break;case AI_FOLLOW_REVERSE:e=b[b.length-1];e=s_oBoardUtility.getNeighborByDir(e.row,e.col,k);if(null===e||a.getCellState(e.row,e.col)===CELL_STATE_WATER)return this._setCarrierFound(),this._getLastDirectionCoordinate();b.push(e);d=this._predictHit(e.row,e.col);d===PREDICT_WATER&&this._setCarrierFound();break;case AI_FOLLOW_CARRIER:e=this._findCarrierCell()}return e};
this._findCarrierCell=function(){var c;if(0<e.length){c=e[0];e.splice(0,1);0===e.length&&(e=s_oBoardUtility.getNeighborByShift(m,g[0]),m=s_oBoardUtility.getNeighborByShift(m,g[0]),null===e[0]||a.getCellState(e[0].row,e[0].col)===CELL_STATE_WATER)&&(0<g.length?(g.splice(0,1),e=s_oBoardUtility.getNeighborByShift(b,g[0]),m=s_oBoardUtility.getNeighborByShift(b,g[0])):(d=AI_STATE_NEW_COORDINATE,k=null,b=[]));var f=this._predictHit(c.row,c.col);f===PREDICT_WATER&&0<g.length&&(b.push(c),e=[],g.splice(0,
1))}else{this._removeWaterCell();e=s_oBoardUtility.getNeighborByShift(b,g[0]);m=s_oBoardUtility.getNeighborByShift(b,g[0]);if(null===e[0]||a.getCellState(e[0].row,e[0].col)===CELL_STATE_WATER)g.splice(0,1),e=s_oBoardUtility.getNeighborByShift(b,g[0]),m=s_oBoardUtility.getNeighborByShift(b,g[0]);c=e[0];e.splice(0,1);f=this._predictHit(c.row,c.col);f===PREDICT_WATER&&(b.push(c),e=[],g.splice(0,1))}return c};this._predictHit=function(b,c){var e;e=a.isShipOn(b,c);if(null!==e){e=e.getListCellOccupied();
for(var d=[],g=0;g<e.length;g++)e[g].row===b&&e[g].col===c||d.push(e[g]);e=this._checkSunk(d)?PREDICT_SUNK:PREDICT_HIT}else e=PREDICT_WATER;return e};this._checkSunk=function(b){for(var a=!0,c=0;c<b.length;c++)b[c].hit||(a=!1);return a};this._setCarrierFound=function(){c=AI_FOLLOW_CARRIER;g=b[0].row===b[1].row?[DIR_TOP,DIR_BOT]:[DIR_LEFT,DIR_RIGHT];shuffle(g)};this.resetToStartState=function(){c=AI_FIND_DIRECTION;d=AI_STATE_NEW_COORDINATE;k=null;b=[]};this._setViableDirection=function(b){h=[];h=s_oBoardUtility.getCrossDir(b.row,
b.col);for(var c=h.length-1;0<=c;c--){var e=s_oBoardUtility.getNeighborByDir(b.row,b.col,h[c]);a.getCellState(e.row,e.col)===CELL_STATE_WATER&&h.splice(c,1)}};this._removeDirection=function(){var b=h.indexOf(k);h.splice(b,1);k=null};this._removeWaterCell=function(){for(var c=b.length-1;0<=c;c--)a.getCellState(b[c].row,b[c].col)===CELL_STATE_WATER&&b.splice(c,1)};this._init(a)}
function CTurnWaiter(a){var d,c,f,h,b;this._init=function(a){d=new createjs.Container;d.x=0;d.y=0;var g=CANVAS_WIDTH,k=CANVAS_HEIGHT,g=(new createjs.Graphics).beginFill("rgba(0,0,0,0.2)").drawRect(0,0,g,k);f=new createjs.Shape(g);f.on("click",function(){});c=new createjs.Text("","bold 60px "+PRIMARY_FONT,"#ffffff");c.x=0;c.y=-55;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=800;h=new createjs.Text("","bold 180px "+PRIMARY_FONT,"#ffffff");h.x=-85;h.y=10;h.textAlign="left";h.textBaseline=
"alphabetic";h.lineWidth=800;b=new createSprite(s_oWaitPlayerSpritesheet,"idle",0,0,0,0);b.x=CANVAS_WIDTH/2-270;b.y=CANVAS_HEIGHT/2-200;d.addChild(f,c,h,b);a.addChild(d);e.hide()};this.show=function(b){null==b&&(b="");c.text=b;d.visible=!0};this.hide=function(){c.text="";d.visible=!1};this.unload=function(){f.off("click",function(){});a.removeChild(d)};this.update=function(){};var e=this;this._init(a)}
function CAirStrike(a){var d,c,f=CANVAS_WIDTH+200,h=CANVAS_HEIGHT-400;this._init=function(b){d=new createjs.Container;d.x=f;d.y=h;d.scaleX=d.scaleY=.6;b.addChild(d);b=s_oSpriteLibrary.getSprite("air");var a=createBitmap(b);a.regX=b.width/2;a.regY=b.height/2;d.addChild(a);b=s_oSpriteLibrary.getSprite("air_shadow");a=createBitmap(b);a.x=50;a.y=500;a.scaleX=a.scaleY=.75;a.regX=b.width/2;a.regY=b.height/2;d.addChild(a)};this.unload=function(){a.removeChild(d)};this.endAnim=function(b,a,g){playSound("air_strike",
1,0);d.x=b.x;d.y=b.y;createjs.Tween.get(d).to({x:a.x,y:a.y},g).call(function(){c.unload()})};this.launch=function(){playSound("air_strike",1,0);d.x=f;d.y=h;s_oGame.setNumMissileShot(NUM_BOMB_AIRSTRIKE);createjs.Tween.get(d).to({x:-250,y:-300},2E3,createjs.Ease.cubicIn);var b=this._getCellToHit();setTimeout(function(){for(var c=0;c<NUM_BOMB_AIRSTRIKE;c++)(new CMissile(a)).launchAirMissile({x:d.x,y:d.y},{row:b[c].row,col:b[c].col},.8+.4*Math.random())},1100)};this._getCellToHit=function(){for(var b=
s_oGame.getBoard(OPPONENT),a=[],c=0;c<NUM_CELL;c++)for(var d=0;d<NUM_CELL;d++)if(b.getCellState(c,d)===CELL_STATE_VOID){for(var f=s_oBoardUtility.getCrossNeighbor(c,d),h=!0,l=0;l<f.length;l++){var n=f[l];b.getCellState(n.row,n.col)===CELL_STATE_HIT&&(h=!1)}h&&a.push({row:c,col:d})}do for(b=[],c=0;c<NUM_BOMB_AIRSTRIKE;c++)b.push(a[Math.floor(Math.random()*a.length)]);while(this._checkNearCell(b));return b};this._checkNearCell=function(b){for(var a=0;a<b.length-1;a++)for(var c=b[a],c=s_oBoardUtility.getCrossNeighbor(c.row,
c.col),d=0;d<c.length;d++)for(var f=a+1;f<b.length;f++)if(this._isEqual(b[a],b[f])||this._isEqual(c[d],b[f]))return!0;return!1};this._isEqual=function(b,a){return b.row===a.row&&b.col===a.col?!0:!1};c=this;this._init(a)}var DIR_TOPRIGHT="DIR_TOPRIGHT",DIR_RIGHT="DIR_RIGHT",DIR_BOTRIGHT="DIR_BOTRIGHT",DIR_TOPLEFT="DIR_TOPLEFT",DIR_LEFT="DIR_LEFT",DIR_BOTLEFT="DIR_BOTLEFT",DIR_TOP="DIR_TOP",DIR_BOT="DIR_BOT";
function CBoardUtility(a){var d,c,f,h;this._init=function(b){d=b.length;c=b[0].length;h=[];f=[];for(b=0;b<d;b++){f[b]=[];for(var a=0;a<c;a++)f[b][a]=[]}this._buildMap()};this._buildMap=function(){for(var b=0;b<d;b++)for(var a=0;a<c;a++)f[b][a][DIR_TOPRIGHT]=this._setNeighbor(b,a,DIR_TOPRIGHT),f[b][a][DIR_RIGHT]=this._setNeighbor(b,a,DIR_RIGHT),f[b][a][DIR_BOTRIGHT]=this._setNeighbor(b,a,DIR_BOTRIGHT),f[b][a][DIR_TOPLEFT]=this._setNeighbor(b,a,DIR_TOPLEFT),f[b][a][DIR_LEFT]=this._setNeighbor(b,a,DIR_LEFT),
f[b][a][DIR_BOTLEFT]=this._setNeighbor(b,a,DIR_BOTLEFT),f[b][a][DIR_TOP]=this._setNeighbor(b,a,DIR_TOP),f[b][a][DIR_BOT]=this._setNeighbor(b,a,DIR_BOT)};this._setNeighbor=function(a,e,f){var b=null;switch(f){case DIR_TOPRIGHT:0<a&&e<c-1&&(b={row:a-1,col:e+1});break;case DIR_RIGHT:e<c-1&&(b={row:a,col:e+1});break;case DIR_BOTRIGHT:a<d-1&&e<c-1&&(b={row:a+1,col:e+1});break;case DIR_TOPLEFT:0<a&&0<e&&(b={row:a-1,col:e-1});break;case DIR_LEFT:0<e&&(b={row:a,col:e-1});break;case DIR_BOTLEFT:a<d-1&&0<e&&
(b={row:a+1,col:e-1});break;case DIR_TOP:0<a&&(b={row:a-1,col:e});break;case DIR_BOT:a<d-1&&(b={row:a+1,col:e})}return b};this.getNeighborByDir=function(a,c,d){return f[a][c][d]};this.getAllNeighbor=function(a,c){var b=[],e;for(e in f[a][c])null!==f[a][c][e]&&b.push(f[a][c][e]);return b};this.getCrossDir=function(a,c){for(var b=[],e=[DIR_TOP,DIR_RIGHT,DIR_BOT,DIR_LEFT],d=0;d<e.length;d++)null!==this.getNeighborByDir(a,c,e[d])&&b.push(e[d]);return b};this.getCrossNeighbor=function(a,c){for(var b=[],
e=[DIR_TOP,DIR_RIGHT,DIR_BOT,DIR_LEFT],d=0;d<e.length;d++){var f=this.getNeighborByDir(a,c,e[d]);null!==f&&b.push(f)}return b};this._getMainDiagonal=function(a,c,d){var b=[],e=d[a][c].getColor();this._findInDirection(a,c,DIR_BOTRIGHT,b,99,e,d);this._findInDirection(a,c,DIR_TOPLEFT,b,99,e,d);return b};this._getSecondDiagonal=function(a,c,d){var b=[],e=d[a][c].getColor();this._findInDirection(a,c,DIR_BOTLEFT,b,99,e,d);this._findInDirection(a,c,DIR_TOPRIGHT,b,99,e,d);return b};this._getRow=function(a,
c,d){var b=[],e=d[a][c].getColor();this._findInDirection(a,c,DIR_LEFT,b,99,e,d);this._findInDirection(a,c,DIR_RIGHT,b,99,e,d);return b};this._getCol=function(a,c,d){var b=[],e=d[a][c].getColor();this._findInDirection(a,c,DIR_TOP,b,99,e,d);this._findInDirection(a,c,DIR_BOT,b,99,e,d);return b};this._getStraightByDirAndRadius=function(a,c,d,f,k){var b=[];h=[];h.push({radius:f,direction:null});var e=k[a][c].getColor();this._findInDirection(a,c,d,b,f,e,k);return b};this._getStraightRowByRadius=function(a,
c,d){var b=[];h=[];h.push({radius:d,direction:null});this._findInDirection(a,c,DIR_LEFT,b,d);this._findInDirection(a,c,DIR_RIGHT,b,d);return b};this._getStraightColByRadius=function(a,c,d){var b=[];h=[];h.push({radius:d,direction:null});this._findInDirection(a,c,DIR_TOP,b,d);this._findInDirection(a,c,DIR_BOT,b,d);return b};this._findInDirection=function(a,c,d,m,k){--k;if(null!==f[a][c][d]&&0<=k){var b=f[a][c][d].row;a=f[a][c][d].col;m.push({row:b,col:a});h.push({radius:k,direction:d});this._findInDirection(b,
a,d,m,k)}};this.getNeighborByShift=function(a,c){for(var b=[],d=0;d<a.length;d++)b[d]=this.getNeighborByDir(a[d].row,a[d].col,c);return b};this.getReverseDirection=function(a){var b;switch(a){case DIR_RIGHT:b=DIR_LEFT;break;case DIR_BOT:b=DIR_TOP;break;case DIR_LEFT:b=DIR_RIGHT;break;case DIR_TOP:b=DIR_BOT}return b};this._init(a);s_oBoardUtility=this}var s_oBoardUtility;
function CBattleCell(a,d,c,f,h,b){var e,g,m,k,p,l,n;this._init=function(a,b,c,d,f,h){e=CELL_STATE_VOID;n=l=null;g=new createjs.Container;g.x=a;g.y=b;c.addChild(g);m=new createSprite(s_oBattleCellSpritesheet,"void",0,0,0,0);g.addChild(m);k=new createSprite(s_oMissileWaterSpritesheet,"stop",0,0,0,0);k.x=a+c.x;k.y=b+c.y;h.addChild(k);p=new createSprite(s_oMissileExplosionSpritesheet,"stop",0,0,0,0);p.x=a+c.x;p.y=b+c.y;h.addChild(p)};this.unload=function(){c.removeChild(g)};this.getPos=function(){return{x:a,
y:d}};this.debug=function(){var a=new createjs.Text(f+","+h," 14px Arial","#ffffff");a.textAlign="center";a.textBaseline="middle";a.lineWidth=200;g.addChild(a)};this.playWater=function(){k.gotoAndPlay("idle");playSound("missile_water",1,0)};this.playExplosion=function(){p.gotoAndPlay("idle");playSound("missile_explosion",1,0)};this.getState=function(){return e};this.setState=function(a){e=a;m.gotoAndStop(a);a===CELL_STATE_SUNK&&m.gotoAndStop(CELL_STATE_HIT)};this.setFinalExplosion=function(){playSound("missile_sink",
1,0);n=new createSprite(s_oFinalExplosionSpritesheet,"idle",0,0,0,0);n.x=a+c.x;n.y=d+c.y;b.addChild(n)};this.setFire=function(){l=new createSprite(s_oFireSpritesheet,"idle",0,0,0,0);l.x=a+c.x;l.y=d+c.y;b.addChild(l)};this.removeFire=function(){null!==l&&l.gotoAndStop("stop")};this._init(a,d,c,f,h,b)}
function CAnimationSettings(){this._init=function(){this._initShips();this._initBattleCell();this._initMissile();this._initEnvironment();this._initGUI()};this._initShips=function(){s_aShipSpritesheet=[];for(var a=0;6>a;a++){var d=s_oSpriteLibrary.getSprite("ship"+a+"_3d");s_aShipSpritesheet[a]=new createjs.SpriteSheet({images:[d],frames:{width:d.width/6,height:d.height/5,regX:0,regY:0},animations:{idle:[0,29],stop:[30,30]}})}};this._initBattleCell=function(){var a=s_oSpriteLibrary.getSprite("cell_battle"),
d=a.width/3,c=a.height,a={images:[a],frames:{width:d,height:c,regX:d/2,regY:c/2},animations:{"void":[0],water:[1],hit:[2]}};s_oBattleCellSpritesheet=new createjs.SpriteSheet(a);a=s_oSpriteLibrary.getSprite("cell_control");d=a.width/5;c=a.height;a={images:[a],frames:{width:d,height:c,regX:d/2,regY:c/2},animations:{"void":[0],hit:[1],sunk:[2],water:[3],selection:[4]}};s_oControlCellSpritesheet=new createjs.SpriteSheet(a)};this._initMissile=function(){var a=s_oSpriteLibrary.getSprite("missile_reactor"),
d=a.width/2,c=a.height,a={images:[a],frames:{width:d,height:c,regX:d/2,regY:c/2},animations:{idle:[0,1]}};s_oMissileReactorSpritesheet=new createjs.SpriteSheet(a);a=s_oSpriteLibrary.getSprite("missile_smoke");d=a.width/5;c=a.height/10;a={images:[a],frames:{width:d,height:c,regX:d/2+20,regY:c/2},animations:{idle:[0,49,"stop"],stop:[50,50]}};s_oMissileSmokeSpritesheet=new createjs.SpriteSheet(a);a=s_oSpriteLibrary.getSprite("missile_water");d=a.width/7;c=a.height/4;a={images:[a],frames:{width:d,height:c,
regX:d/2,regY:c/2+40},animations:{idle:[0,27,"stop"],stop:[28,28]}};s_oMissileWaterSpritesheet=new createjs.SpriteSheet(a);a=s_oSpriteLibrary.getSprite("missile_explosion");d=a.width/6;c=a.height/5;a={framerate:15,images:[a],frames:{width:d,height:c,regX:d/2,regY:c/2},animations:{idle:[0,29,"stop"],stop:[30,30]}};s_oMissileExplosionSpritesheet=new createjs.SpriteSheet(a)};this._initEnvironment=function(){var a=s_oSpriteLibrary.getSprite("fire"),d=a.width/5,c=a.height/6,a={framerate:15,images:[a],
frames:{width:d,height:c,regX:d/2,regY:c-6},animations:{idle:[0,29],stop:[30,30]}};s_oFireSpritesheet=new createjs.SpriteSheet(a);a=s_oSpriteLibrary.getSprite("final_explosion");d=a.width/8;c=a.height/5;a={images:[a],frames:{width:d,height:c,regX:d/2,regY:c/2},animations:{idle:[0,39,"stop"],stop:[40,40]}};s_oFinalExplosionSpritesheet=new createjs.SpriteSheet(a);a=s_oSpriteLibrary.getSprite("wait_player");d=a.width/9;c=a.height/6;a={images:[a],frames:{width:d,height:c,regX:d/2,regY:c/2},animations:{idle:[0,
49],stop:[50,50]}};s_oWaitPlayerSpritesheet=new createjs.SpriteSheet(a)};this._initGUI=function(){var a=s_oSpriteLibrary.getSprite("but_radar"),d=a.width/15,c=a.height/4;s_oRadarSpritesheet=new createjs.SpriteSheet({images:[a],frames:{width:d,height:c,regX:d/2,regY:c/2},animations:{idle:[0,58],disable:[59,59]}})};this._init()}
var s_aShipSpritesheet,s_oBattleCellSpritesheet,s_oControlCellSpritesheet,s_oMissileReactorSpritesheet,s_oMissileSmokeSpritesheet,s_oMissileWaterSpritesheet,s_oMissileExplosionSpritesheet,s_oFireSpritesheet,s_oFinalExplosionSpritesheet,s_oWaitPlayerSpritesheet,s_oRadarSpritesheet;
function CPlayerBoard(a,d,c,f,h,b){var e,g,m,k;this._init=function(a,b,c,d,e,f){k=new createjs.Container;k.x=a;k.y=b;c.addChild(k);this._initBoard();e===PLAYER&&this._setShips()};this._initBoard=function(){g=[];var a=0,c=0;g=[];for(var d=0;d<NUM_CELL;d++){g[d]=[];for(var e=0;e<NUM_CELL;e++){var f=new CBattleCell(a,c,k,d,e,b);h===PLAYER?(a+=32,c-=18):(a-=32,c+=18);g[d][e]=f}h===PLAYER?(a=32*(d+1),c=18*(d+1)):(a=32*-(d+1),c=18*-(d+1))}};this._setShips=function(){m=[];for(var a=0;a<f.length;a++){var b=
f[a].getType(),c=f[a].getListCellOccupied(),d=c[0].row,c=c[0].col,e=new createSprite(s_aShipSpritesheet[b.battle_spritesheet],"idle",0,0,0,0);e.x=g[d][c].getPos().x;e.y=g[d][c].getPos().y;e.regX=b.reg_points.x;e.regY=b.reg_points.y;h===OPPONENT&&(e.rotation=180);f[a].isHorizontal()&&(e.scaleX=-1,e.regX=b.reg_points.inverseX,e.regY=b.reg_points.inverseY);m.push(e);k.addChild(e)}};this.isShipOn=function(a,b){for(var c=0;c<f.length;c++)for(var d=f[c].getListCellOccupied(),e=0;e<d.length;e++)if(d[e].row===
a&&d[e].col===b)return f[c];return null};this.sunkAnimation=function(a){this.hideShip(a.getType().index_type);a=a.getListCellOccupied();for(var b=[],c=0;c<a.length;c++)b.push(a[c]);shuffle(b);var d=0;e=setInterval(function(){g[b[d].row][b[d].col].removeFire();g[b[d].row][b[d].col].setFinalExplosion();d++;d===b.length&&clearInterval(e)},200)};this.setFire=function(a,b){g[a][b].setFire()};this.setCellState=function(a,b,c){g[a][b].setState(c)};this.getCellState=function(a,b){return g[a][b].getState()};
this.getCells=function(){return g};this.getCellPos=function(b,c){var e=g[b][c].getPos();return{x:e.x+a,y:e.y+d}};this.getBounds=function(){return k.getBounds()};this.getPos=function(){return{x:a,y:d}};this.playExplosion=function(a,b){g[a][b].playExplosion()};this.playWater=function(a,b){g[a][b].playWater()};this.hideShip=function(a){h===PLAYER&&(m[a].visible=!1)};this._init(a,d,c,f,h,b)}
function CControlPanel(){var a,d,c,f,h,b=null,e,g,m,k,p;this._init=function(){d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;d.on("mousedown",function(){});s_oStage.addChild(d);c=new createjs.Container;s_oStage.addChild(c);h=s_oSpriteLibrary.getSprite("control_panel");var a=createBitmap(h);a.regX=h.width/2;a.regY=h.height/2;c.addChild(a);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT+h.height/2;f=new createjs.Container;c.addChild(f);this._initControlCells();
this._setAlphabeticCoordinate();this._setNumCoordinate();m=new createjs.Text(TEXT_COST+": "+COST_AIRSTRIKE," 30px "+SECONDARY_FONT,"#1ef400");m.textAlign="left";m.textBaseline="middle";m.x=390;m.y=-352;c.addChild(m);a=s_oSpriteLibrary.getSprite("but_air_strike");e=new CToggle(450,-274,a,!1,c);e.addEventListener(ON_MOUSE_UP,this._onAirStrike,this);e.addEventListener(ON_MOUSE_OVER,this._hideRuler,this);e.addEventListener(ON_MOUSE_OUT,this._showRuler,this);e.enable(!1);s_iMode===MODE_CLASSIC&&(e.setVisible(!1),
m.visible=!1);k=new createjs.Text(TEXT_COST+": "+COST_RADAR," 30px "+SECONDARY_FONT,"#1ef400");k.textAlign="left";k.textBaseline="middle";k.x=390;k.y=-144;c.addChild(k);g=new CAnimatedButton(450,-62,s_oRadarSpritesheet,c);g.addEventListener(ON_MOUSE_UP,this._onRadar,this);g.addEventListener(ON_MOUSE_OVER,this._hideRuler,this);g.addEventListener(ON_MOUSE_OUT,this._showRuler,this);g.enable(!1);s_iMode===MODE_CLASSIC&&(g.setVisible(!1),k.visible=!1);b=new CRuler(c)};this.unload=function(){s_oStage.removeChild(d);
s_oStage.removeChild(c);e.unload();g.unload();d.off("mousedown",function(){})};this._initControlCells=function(){var b=NUM_CELL,c=CONTROL_CELL_DIM,d=NUM_CELL/2*CONTROL_CELL_DIM-c/2;a=[];for(var e=0;e<b;e++){a[e]=[];for(var h=0;h<b;h++)a[e][h]=new CControlCell(d-h*c,d-e*c,f,e,h)}};this._setAlphabeticCoordinate=function(){for(var b=NUM_CELL-1;0<=b;b--){var c=new createjs.Text(String.fromCharCode(65+NUM_CELL-b-1)," 50px "+SECONDARY_FONT,"#60ff00");c.x=a[b][NUM_CELL-1].getPos().x-60;c.y=a[b][NUM_CELL-
1].getPos().y;c.textAlign="center";c.textBaseline="middle";f.addChild(c)}};this._setNumCoordinate=function(){for(var b=NUM_CELL-1;0<=b;b--){var c=new createjs.Text(NUM_CELL-b," 34px "+SECONDARY_FONT,"#60ff00");c.x=a[0][b].getPos().x;c.y=a[0][b].getPos().y+50;c.textAlign="center";c.textBaseline="middle";f.addChild(c)}};this.show=function(){c.visible=!0;createjs.Tween.get(d).to({alpha:.7},500);createjs.Tween.get(c).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartIn)};this.hide=function(){createjs.Tween.removeTweens(d);
c.visible=!1;c.y=CANVAS_HEIGHT+h.height/2;d.alpha=0};this._showRuler=function(){b.show(!0)};this._hideRuler=function(){b.show(!1)};this.refresh=function(b){for(var c=0;c<a.length;c++)for(var d=0;d<a[c].length;d++){var f=b[c][d].getState();a[c][d].setState(f);a[c][d].disableHighlight()}b=s_oGame.getScore();b>COST_AIRSTRIKE&&e.enable(!0);b>COST_RADAR&&g.enable(!0)};this._onAirStrike=function(){this._showRuler();e.enable(!1);s_oGame.addScore(-COST_AIRSTRIKE);p.hide();s_oGame.launchAirStrike()};this._onRadar=
function(){playSound("sonar",1,0);this._showRuler();g.enable(!1);s_oGame.addScore(-COST_RADAR);for(var b=s_oGame.getRandomAvailableShip(OPPONENT).getListCellOccupied(),c=[],d=0;d<b.length;d++)b[d].hit||c.push(b[d]);b=c[Math.floor(Math.random()*c.length)];a[b.row][b.col].highlight()};this.update=function(a){a&&b.updatePos(a.x,a.y)};p=this;this._init()}
function CControlCell(a,d,c,f,h){var b,e,g,m;this._init=function(a,c,d,f,h){b=CELL_STATE_VOID;e=new createjs.Container;e.x=a;e.y=c;d.addChild(e);m=new createSprite(s_oControlCellSpritesheet,"void",0,0,0,0);e.addChild(m);g=new createSprite(s_oControlCellSpritesheet,"hit",0,0,0,0);g.alpha=0;e.addChild(g);a=new createjs.Shape;a.graphics.beginFill("rgba(158,0,0,0.01)").drawRect(-CONTROL_CELL_DIM/2,-CONTROL_CELL_DIM/2,CONTROL_CELL_DIM,CONTROL_CELL_DIM);e.addChild(a);e.on("mousedown",this._onCellClick,
this);e.on("mouseover",this._onCellOver,this);e.on("mouseout",this._onCellOut,this)};this.unload=function(){e.off("mousedown",this._onCellClick);e.off("mouseover",this._onCellOver);e.off("mouseout",this._onCellOut);c.removeChild(e)};this._onCellClick=function(){if(b===CELL_STATE_VOID)s_oGame.onCellClick(f,h)};this._onCellOver=function(){b===CELL_STATE_VOID&&m.gotoAndStop("selection")};this._onCellOut=function(){b===CELL_STATE_VOID&&m.gotoAndStop("void")};this.setState=function(a){b=a;m.gotoAndStop(a)};
this.getState=function(){return b};this.highlight=function(){createjs.Tween.get(g,{loop:!0}).to({alpha:1},500,createjs.Ease.cubicOut).to({alpha:0},500,createjs.Ease.cubicOut)};this.disableHighlight=function(){createjs.Tween.removeTweens(g);g.alpha=0};this.getPos=function(){return{x:e.x,y:e.y}};this._init(a,d,c,f,h)}
function CMissile(a,d){var c,f,h,b,e,g,m,k,p,l,n,q,r,t,v,u,w;this._init=function(a,d){c=!0;b=MISSILE_TYPE_NORMAL;e=0;g=50;m=new CVector2(0,0);p=new CVector2(0,-1);k=new CVector2(0,0);n=0;t=new createjs.Container;a.addChild(t);u=new createSprite(s_oMissileReactorSpritesheet,"idle",0,0,0,0);u.x=-1;u.y=28;u.visible=!1;t.addChild(u);var f=s_oSpriteLibrary.getSprite("missile");v=createBitmap(f);v.regX=f.width/2;v.regY=f.height/2;t.addChild(v);w=new createSprite(s_oMissileSmokeSpritesheet,"stop",0,0,0,
0);a.addChild(w)};this.reset=function(a,b,c){k.x=a;k.y=b;q=c;m=new CVector2(a,b);p=new CVector2(0,-1);k=new CVector2(a,b);n=0};this._findMiddlePoint=function(a,b,c){return c===PLAYER?a.y>b.y?a.x>b.x?new createjs.Point(a.x-.2*(a.x-b.x),b.y-200):new createjs.Point(b.x+.2*(b.x-a.x),b.y-200):a.x>b.x?new createjs.Point(a.x-.2*(a.x-b.x),a.y-200):new createjs.Point(b.x+.2*(b.x-a.x),a.y-200):a.y>b.y?a.x>b.x?new createjs.Point(a.x+.2*(a.x-b.x),b.y-200):new createjs.Point(b.x-.2*(b.x-a.x),b.y-200):a.x>b.x?
new createjs.Point(b.x+.2*(b.x-a.x),a.y-200):new createjs.Point(a.x-.2*(a.x-b.x),a.y-200)};this.launchMissileForPlayer=function(e,f){t.visible=!0;var h=this.getLaunchCoordinate(e,f,PLAYER),g=h.start;g.y-=17;var k=h.end,l=new createjs.Point(g.x,g.y),k=new createjs.Point(k.x,k.y);null!==h.ship&&4===h.ship.getType().battle_spritesheet?(b=MISSILE_TYPE_TORPEDO,h=s_oSpriteLibrary.getSprite("torpedo"),v.image=h,d.addChild(t),playSound("missile_torpedo",1,0),c=!1,r=[new createjs.Point(l.x,l.y+17),k],t.rotation=
180/Math.PI*Math.atan2(k.y-l.y,k.x-l.x)+90,t.x=l.x,t.y=l.y+17):(b=MISSILE_TYPE_NORMAL,h=s_oSpriteLibrary.getSprite("missile"),v.image=h,a.addChild(t),playSound("missile_launch",1,0),c=!1,h=this._findMiddlePoint(l,k,PLAYER),r=[l,h,k],w.gotoAndPlay("idle"),w.x=g.x,w.y=g.y,u.visible=!0,this.reset(l.x,l.y,1));return!0};this.launchMissileForOpponent=function(d,e){b=MISSILE_TYPE_NORMAL;var f=s_oSpriteLibrary.getSprite("missile");v.image=f;a.addChild(t);playSound("missile_launch",1,0);c=!1;t.visible=!0;
var h=this.getLaunchCoordinate(d,e,OPPONENT),f=h.start;f.y-=17;var g=h.end,h=new createjs.Point(f.x,f.y),g=new createjs.Point(g.x,g.y),k=this._findMiddlePoint(h,g,OPPONENT);r=[h,k,g];w.gotoAndPlay("idle");w.x=f.x;w.y=f.y;this.reset(h.x,h.y,1)};this.getLaunchCoordinate=function(a,b,c){f=a;h=b;var d=null;if(c===PLAYER){d=s_oGame.getRandomAvailableShip(PLAYER);c=d.getListCellOccupied();for(var e=[],g=0;g<c.length;g++)e.push(c[g]);for(g=e.length-1;0<=g;g--)e[g].hit&&e.splice(g,1);c=e[Math.floor(Math.random()*
e.length)];c=s_oGame.getCellPos(c.row,c.col,PLAYER);a=s_oGame.getCellPos(a,b,OPPONENT)}else c=s_oGame.getBoardPos(OPPONENT),a=s_oGame.getCellPos(a,b,PLAYER);return{start:c,end:a,ship:d}};this.setPos=function(a,b){m=new CVector2(k.x,k.y);k.x=a;k.y=b;l=new CVector2(a,b);l.subV(m);l.normalize();n=angleBetweenVector2D(p,l);n=m.getX()<a?radiansToDegree(n):-radiansToDegree(n)};this.launchAirMissile=function(a,b,c){var d=s_oGame.getCellPos(b.row,b.col,OPPONENT);t.x=a.x;t.y=a.y;t.alpha=0;t.rotation=-70;w.gotoAndPlay("idle");
w.x=a.x;w.y=a.y;createjs.Tween.get(t).to({alpha:1},300*c).call(function(){u.visible=!0;new CTremble(v,300,10,1);playSound("missile_launch",1,0)});createjs.Tween.get(t).to({x:d.x},1400*c,createjs.Ease.quartIn);var e=50+50*Math.random();createjs.Tween.get(t).to({y:a.y+e},700*c,createjs.Ease.cubicOut).to({y:d.y},700*c,createjs.Ease.cubicIn).call(function(){s_oGame.onMissileArrived(b.row,b.col);t.visible=!1})};this.updateTorpedo=function(){if(!c){e++;e>g&&(e=0);var a=easeInQuart(e,0,1,g),b=new createjs.Point(r[0].x+
a*(r[1].x-r[0].x),r[0].y+a*(r[1].y-r[0].y));t.x=b.x;t.y=b.y;1===a&&(e=0,c=!0,t.visible=!1,s_oGame.onMissileArrived(f,h))}};this.updateMissile=function(){if(!c){e++;e>g&&(e=0);var a=easeInQuart(e,0,1,g),b=this.quad(a,r);this.setPos(b.x,b.y);this.updateGfx();1===a&&(e=0,c=!0,t.visible=!1,s_oGame.onMissileArrived(f,h))}};this.quad=function(a,b){var c=new createjs.Point,d=(1-a)*(1-a),e=a*a;c.x=d*b[0].x+2*(1-a)*a*b[1].x+e*b[2].x;c.y=d*b[0].y+2*(1-a)*a*b[1].y+e*b[2].y;return c};this.updateGfx=function(){t.x=
k.x;t.y=k.y;t.rotation=n*q};this.update=function(){switch(b){case MISSILE_TYPE_NORMAL:this.updateMissile();break;case MISSILE_TYPE_TORPEDO:this.updateTorpedo()}};this._init(a,d)}
function CTremble(a,d,c,f){var h,b,e,g,m,k,p,l;this._init=function(a,c,d,f){g=e=!1;k=0;this._calculateDuration();h=a.x;b=a.y;e||(e=!0,m=setInterval(function(){l._tremble()},d))};this._tremble=function(){if(g=!g){var n;n=.5>Math.random()?-f:f;var q;q=.5>Math.random()?-f:f;a.x+=n;a.y+=q}else a.x=h,a.y=b;k++;k>p&&(k=0,e=!1,0===d?m=setInterval(function(){l._tremble()},c):clearInterval(m))};this._calculateDuration=function(){p=d/c};this.stopTremble=function(){clearInterval(m)};l=this;this._init(a,d,c,
f)}
function CVector2(a,d){var c,f;this._init=function(a,b){c=a;f=b};this.add=function(a,b){c+=a;f+=b};this.addV=function(a){c+=a.getX();f+=a.getY()};this.scalarDivision=function(a){c/=a;f/=a};this.subV=function(a){c-=a.getX();f-=a.getY()};this.scalarProduct=function(a){c*=a;f*=a};this.invert=function(){c*=-1;f*=-1};this.dotProduct=function(a){return c*a.getX()+f*a.getY()};this.set=function(a,b){c=a;f=b};this.setV=function(a){c=a.getX();f=a.getY()};this.length=function(){return Math.sqrt(c*c+f*f)};this.length2=
function(){return c*c+f*f};this.normalize=function(){var a=this.length();0<a&&(c/=a,f/=a)};this.getNormalize=function(a){this.length();a.set(c,f);a.normalize()};this.rot90CCW=function(){var a=c;c=-f;f=a};this.rot90CW=function(){var a=c;c=f;f=-a};this.getRotCCW=function(a){a.set(c,f);a.rot90CCW()};this.getRotCW=function(a){a.set(c,f);a.rot90CW()};this.ceil=function(){c=Math.ceil(c);f=Math.ceil(f)};this.round=function(){c=Math.round(c);f=Math.round(f)};this.toString=function(){return"Vector2: "+c+", "+
f};this.print=function(){trace("Vector2: "+c+", "+f+"")};this.getX=function(){return c};this.getY=function(){return f};this._init(a,d)}
function CBackground(a){var d,c,f;this._init=function(a){f=new createjs.Container;a.addChild(f);if(s_bMobile)a=s_oSpriteLibrary.getSprite("sea_mobile"),a=createBitmap(a),f.addChild(a);else{var b=a=d=0;c=[];for(var e=0;32>=e;e++)c.push(new CSeaAnimation(a,b,f)),a+=SEA_PIECE_DIM/2,0===e%8&&0<e&&(b+=SEA_PIECE_DIM/2,a=0)}a=s_oSpriteLibrary.getSprite("bg_rocks");a=createBitmap(a);f.addChild(a)};this.update=function(){d++;if(1<d)for(var a=d=0;a<c.length;a++)c[a].update()};this._init(a)}
function CSeaAnimation(a,d,c){var f,h,b,e;this._init=function(a,c,d){e=new createjs.Container;e.x=a;e.y=c;e.scaleX=e.scaleY=.5;d.addChild(e);h=37;f=Math.floor(Math.random()*h);b=[];for(a=0;a<=h;a++)c=s_oSpriteLibrary.getSprite("surface_"+a),b[a]=createBitmap(c),b[a].visible=!1,e.addChild(b[a]);b[0].visible=!0};this._idle=function(){0===f?(b[h].visible=!1,b[0].visible=!0):(b[f-1].visible=!1,b[f].visible=!0);f++;f>h&&(f=0)};this.update=function(){this._idle()};this._init(a,d,c)}
function CSummaryPanel(a,d,c){var f,h,b,e,g,m,k,p,l;this._init=function(a,b,c){e=new createjs.Container;this.setPos(a,b);c.addChild(e);a=s_oSpriteLibrary.getSprite("your_fleet_panel");g=createBitmap(a);g.regY=a.height;e.addChild(g);k=new createjs.Text(TEXT_YOUR_FLEET," 30px "+SECONDARY_FONT,"#04b700");k.x=a.width/2;k.y=-a.height+28;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=600;k.lineHeight=40;e.addChild(k);b=s_oSpriteLibrary.getSprite("enemy_fleet_panel");m=createBitmap(b);m.x=
a.width;m.regY=b.height;e.addChild(m);m=new createjs.Text(TEXT_ENEMY_FLEET," 30px "+SECONDARY_FONT,"#b81e00");m.x=a.width+130;m.y=-b.height+28;m.textAlign="center";m.textBaseline="alphabetic";m.lineWidth=600;m.lineHeight=40;e.addChild(m);c=s_oSpriteLibrary.getSprite("score_panel");p=createBitmap(c);p.x=2*a.width-50;p.y=-b.height;e.addChild(p);l=new createjs.Text(TEXT_SCORE+": 0"," 30px "+SECONDARY_FONT,"#04b700");l.x=p.x+20;l.y=p.y+18;l.textAlign="left";l.textBaseline="middle";l.lineWidth=600;e.addChild(l);
this.setYourFill();this.setText()};this.setYourFill=function(){f=[];for(var a=0;6>a;a++){var b=s_oSpriteLibrary.getSprite("fill_"+a),c=createBitmap(b);c.regX=b.width/2;c.regY=b.height/2;c.x=SHIPS_TYPE[a].fill_pos.x;c.y=SHIPS_TYPE[a].fill_pos.y;e.addChild(c);f[a]=new createjs.Shape;f[a].graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,b.width,b.height);f[a].x=SHIPS_TYPE[a].fill_pos.x-b.width/2;f[a].y=SHIPS_TYPE[a].fill_pos.y-b.height/2;e.addChild(f[a]);c.mask=f[a];f[a].scaleX=0}};this.setText=
function(){h=[];for(var a=0;6>a;a++)h[a]=new createjs.Text(TEXT_SUNK," 30px "+SECONDARY_FONT,"#ff7200"),h[a].x=SHIPS_TYPE[a].fill_pos.x,h[a].y=SHIPS_TYPE[a].fill_pos.y+10,h[a].textAlign="center",h[a].textBaseline="middle",h[a].lineWidth=200,h[a].visible=!1,h[a].rotation=15,e.addChild(h[a]);b=[];for(a=0;6>a;a++)b[a]=new createjs.Text(TEXT_SUNK," 30px "+SECONDARY_FONT,"#ff7200"),b[a].x=SHIPS_TYPE[a].enemy_sunk_pos.x,b[a].y=SHIPS_TYPE[a].enemy_sunk_pos.y,b[a].textAlign="center",b[a].textBaseline="middle",
b[a].lineWidth=200,b[a].rotation=15,b[a].visible=!1,e.addChild(b[a])};this.setDamage=function(a){for(var b=0;b<a.length;b++){for(var c=a[b].getType(),d=a[b].getListCellOccupied(),e=d.length,g=0,k=0;k<e;k++)d[k].hit&&g++;f[c.battle_spritesheet].scaleX=g/e;g===e&&(h[c.battle_spritesheet].visible=!0)}};this.setEnemySunk=function(a){for(var c=0;c<a.length;c++){for(var d=a[c].getType(),e=a[c].getListCellOccupied(),f=e.length,g=0,h=0;h<f;h++)e[h].hit&&g++;g===f&&(b[d.battle_spritesheet].visible=!0)}};this.setScore=
function(a){l.text=TEXT_SCORE+": "+a};this.setPos=function(a,b){e.x=a;e.y=b};this._init(a,d,c)}
function CAnimatedButton(a,d,c,f){var h,b,e,g,m,k,p,l,n;this._init=function(a,c,d,e){h=!1;b=1;k=[];p=[];l=createSprite(d,"disable",60,60,120,120);l.x=a;l.y=c;l.scaleX=l.scaleY=b;e.addChild(l);this._initListener()};this.unload=function(){s_bMobile?l.off("mousedown",e):(l.off("mousedown",e),l.off("mouseover",m),l.off("mouseout",_iListenerIDMouseOut));l.off("pressup",g);f.removeChild(l)};this.setVisible=function(a){l.visible=a};this.setClickable=function(a){h=!a};this._initListener=function(){s_bMobile?
e=l.on("mousedown",this.buttonDown):(e=l.on("mousedown",this.buttonDown),m=l.on("mouseover",this.buttonOver),_iListenerIDMouseOut=l.on("mouseout",this.buttonOut));g=l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){k[a]=b;p[a]=c};this.buttonRelease=function(){h||(l.scaleX=b,l.scaleY=b,k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(p[ON_MOUSE_UP]))};this.buttonDown=function(){h||(l.scaleX=.9*b,l.scaleY=.9*b,playSound("click",1,0),k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN]))};
this.buttonOver=function(a){s_bMobile||h||(a.target.cursor="pointer",k[ON_MOUSE_OVER]&&k[ON_MOUSE_OVER].call(p[ON_MOUSE_OVER]))};this.buttonOut=function(a){s_bMobile||h||(a.target.cursor="pointer",k[ON_MOUSE_OUT]&&k[ON_MOUSE_OUT].call(p[ON_MOUSE_OUT]))};this.pulseAnimation=function(){createjs.Tween.get(l).to({scaleX:.9*b,scaleY:.9*b},850,createjs.Ease.quadOut).to({scaleX:b,scaleY:b},650,createjs.Ease.quadIn).call(function(){n.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(l).to({rotation:5},
75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){n.trebleAnimation()})};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this.enable=function(a){a?(l.gotoAndPlay("idle"),this.setClickable(!0)):(l.gotoAndPlay("disable"),this.setClickable(!1))};n=this;this._init(a,
d,c,f);return this};
