var s_iScaleFactor=1,s_bIsRetina,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){isRetina();for(var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");a.length;)if(navigator.platform===a.pop())return s_bIsIphone=!0;return s_bIsIphone=!1}function isRetina(){s_bIsRetina=matchMedia("(-webkit-min-device-pixel-ratio: 2), (min-device-pixel-ratio: 2), (min-resolution: 192dpi)").matches?!0:!1}
function getSize(a){var f=a.toLowerCase(),c=window.document,b=c.documentElement;if(void 0===window["inner"+a])a=b["client"+a];else if(window["inner"+a]!=b["client"+a]){var d=c.createElement("body");d.id="vpw-test-b";d.style.cssText="overflow:scroll";var g=c.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+f+":"+b["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+f+":7px!important}}</style>";d.appendChild(g);b.insertBefore(d,c.head);
a=7==g["offset"+a]?b["client"+a]:window["inner"+a];b.removeChild(d)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var f=getSize("Width");_checkOrientation(f,a);var c=Math.min(a/CANVAS_HEIGHT,f/CANVAS_WIDTH),b=CANVAS_WIDTH*c,c=CANVAS_HEIGHT*c,d;c<a?(d=a-c,c+=d,b+=CANVAS_WIDTH/CANVAS_HEIGHT*d):b<f&&(d=f-b,b+=d,c+=CANVAS_HEIGHT/CANVAS_WIDTH*d);d=a/2-c/2;var g=f/2-b/2,h=CANVAS_WIDTH/b;if(g*h<-EDGEBOARD_X||d*h<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),
f/(CANVAS_WIDTH-2*EDGEBOARD_X)),b=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,d=(a-c)/2,g=(f-b)/2,h=CANVAS_WIDTH/b;s_iOffsetX=-1*g*h;s_iOffsetY=-1*d*h;0<=d&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oLevelMenu&&s_oLevelMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsRetina?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*b,s_oStage.canvas.height=2*c,canvas.style.width=
b+"px",canvas.style.height=c+"px",a=Math.min(b/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=2*a,s_iScaleFactor=2*a):s_bMobile?($("#canvas").css("width",b+"px"),$("#canvas").css("height",c+"px")):(s_oStage.canvas.width=b,s_oStage.canvas.height=c,s_iScaleFactor=Math.min(b/CANVAS_WIDTH,c/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>d?$("#canvas").css("top",d+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",g+"px")}}
function _checkOrientation(a,f){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>f?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function createBitmap(a,f,c){var b=new createjs.Bitmap(a),d=new createjs.Shape;f&&c?d.graphics.beginFill("#fff").drawRect(0,0,f,c):d.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=d;return b}function createSprite(a,f,c,b,d,g){a=null!==f?new createjs.Sprite(a,f):new createjs.Sprite(a);f=new createjs.Shape;f.graphics.beginFill("#000000").drawRect(-c,-b,d,g);a.hitArea=f;return a}
function randomFloatBetween(a,f,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(f-a),f).toFixed(c))}function shuffle(a){for(var f=a.length,c,b;0!==f;)b=Math.floor(Math.random()*f),--f,c=a[f],a[f]=a[b],a[b]=c;return a}function formatTime(a){a/=1E3;var f=Math.floor(a/60);a=parseFloat(a-60*f).toFixed(1);var c="",c=10>f?c+("0"+f+":"):c+(f+":");return 10>a?c+("0"+a):c+a}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var f=a.length,c,b;0<f;)b=Math.floor(Math.random()*f),f--,c=a[f],a[f]=a[b],a[b]=c;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var f=document.createEvent("MouseEvents");f.initEvent("click",!0,!0);a.dispatchEvent(f)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[f]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var f="hidden";f in document?document.addEventListener("visibilitychange",a):(f="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(f="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(f="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var f=window.location.search.substring(1).split("&"),c=0;c<f.length;c++){var b=f[c].split("=");if(b[0]==a)return b[1]}}function playSound(a,f,c){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?createjs.Sound.play(a,{loop:c,volume:f}):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.stop()}function setVolume(a,f){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.volume=f}
function setMute(a,f){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||a.setMute(f)}function saveItem(a,f){s_bStorageAvailable&&localStorage.setItem(a,f)}function getItem(a){return s_bStorageAvailable?localStorage.getItem(a):null}
function CSpriteLibrary(){var a,f,c,b,d,g;this.init=function(h,e,l){c=f=0;b=h;d=e;g=l;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},f++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){d.call(g)};this._onSpriteLoaded=function(){b.call(g);++c===f&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return f}}
var CANVAS_WIDTH=960,CANVAS_HEIGHT=540,EDGEBOARD_X=128,EDGEBOARD_Y=42,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,FONT_GAME="obelixproitalic",STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_MSG_BOX_LEFT_BUT=6,ON_MSG_BOX_CENTER_BUT=7,ON_MSG_BOX_RIGHT_BUT=8,STATE_GAME_ROLL_IN=0,STATE_GAME_BALL_MOVE=1,STATE_GAME_ROLL_OUT=2,STATE_GAME_SHOOTING=3,STATE_GAME_ATTRACT_BALLS=4,STEP_LENGTH=1.8,BALL_COLORS=5,BALL_ROLLING_IN,
BALL_SHOOTED_SPEED=24,NUM_LEVELS,COMBO_VALUE,EXTRA_SCORE,BALL_DIAMETER,BALL_RADIUS,BALL_DIAMETER_SQUARE,HERO_WIDTH=130,HERO_HEIGHT=130,DAISY_WIDTH=70,DAISY_HEIGHT=76,MIN_TIME_SPAWN_BEE=5E3,MAX_TIME_SPAWN_BEE=2E4,NUM_ROWS_PAGE_LEVEL=3,NUM_COLS_PAGE_LEVEL=5,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,TEXT_GAMEOVER="GAME OVER",TEXT_CONGRATS="CONGRATULATIONS",TEXT_PLAY="PLAY",TEXT_SCORE="SCORE",TEXT_LEVEL="LEVEL",TEXT_FINAL_SCORE="FINAL SCORE",TEXT_SELECT_LEVEL="SELECT A LEVEL",TEXT_DELETE_SAVINGS="ALL YOUR PROGRESS WILL BE DELETED! ARE YOU SURE?",
TEXT_NO="NO",TEXT_YES="YES",TEXT_ERR_LS="YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.",TEXT_CREDITS_DEVELOPED="DEVELOPED BY",TEXT_SHARE_IMAGE="200x200.jpg",TEXT_SHARE_TITLE="Congratulations!",TEXT_SHARE_MSG1="You collected <strong>",TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!",TEXT_SHARE_SHARE1="My score is ",TEXT_SHARE_SHARE2=
" points! Can you do better";
function CPreloader(){var a,f,c,b,d,g,h;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();h=new createjs.Container;s_oStage.addChild(h)};this.unload=function(){h.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(e);e=s_oSpriteLibrary.getSprite("progress_bar");b=createBitmap(e);b.x=CANVAS_WIDTH/2-e.width/2;b.y=CANVAS_HEIGHT-140;h.addChild(b);a=e.width;f=e.height;d=new createjs.Shape;d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(b.x,b.y,1,f);h.addChild(d);b.mask=
d;c=new createjs.Text("","24px "+FONT_GAME,"#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT-95;c.shadow=new createjs.Shadow("#000",2,2,2);c.textBaseline="alphabetic";c.textAlign="center";h.addChild(c);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;h.addChild(g)};this.refreshLoader=function(e){c.text=e+"%";d.graphics.clear();e=Math.floor(e*a/100);d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(b.x,b.y,e,f)};this._init()}
function CMain(a){var f,c=0,b=0,d=STATE_LOADING,g,h,e;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(35);createjs.Ticker.on("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.setLocalStorageLevel=
function(a){s_iLastLevel<a&&(s_iLastLevel=a,saveItem("frogtastic_level",s_iLastLevel))};this.setLocalStorageScore=function(a,b,d){saveItem("score_level_"+d,a)};this.clearLocalStorage=function(){s_iLastLevel=1;s_bStorageAvailable&&localStorage.clear()};this.getScoreTillLevel=function(a){if(!s_bStorageAvailable)return 0;for(var b=0,d=0;d<a-1;d++)b+=parseInt(getItem("score_level_"+(d+1)));return b};this.preloaderReady=function(){jQuery.getJSON("levels.json",this.onLoadedJSON);f=!0};this.soundLoaded=
function(){c++;h.refreshLoader(Math.floor(c/b*100));c===b&&this._allResourcesLoaded()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/game_over.ogg",
"game_over"),createjs.Sound.registerSound("./sounds/combo.ogg","combo"),createjs.Sound.registerSound("./sounds/shot.ogg","shot"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/game_over.mp3",
"game_over"),createjs.Sound.registerSound("./sounds/combo.mp3","combo"),createjs.Sound.registerSound("./sounds/shot.mp3","shot"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack")),b+=6)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_continue","./sprites/but_continue.png");
s_oSpriteLibrary.addSprite("but_generic_small","./sprites/but_generic_small.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("hero","./sprites/hero.png");s_oSpriteLibrary.addSprite("hit_area","./sprites/hit_area.png");s_oSpriteLibrary.addSprite("explosion","./sprites/explosion.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");
s_oSpriteLibrary.addSprite("extra_score","./sprites/extra_score.png");s_oSpriteLibrary.addSprite("end_path","./sprites/end_path.png");s_oSpriteLibrary.addSprite("but_level","./sprites/but_level.png");s_oSpriteLibrary.addSprite("bg_menu_level","./sprites/bg_menu_level.jpg");s_oSpriteLibrary.addSprite("arrow_left","./sprites/arrow_left.png");s_oSpriteLibrary.addSprite("arrow_right","./sprites/arrow_right.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_credits",
"./sprites/but_credits.png");s_oSpriteLibrary.addSprite("but_exit_small","./sprites/but_exit_small.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("base_hero","./sprites/base_hero.png");s_oSpriteLibrary.addSprite("bee","./sprites/bee.png");s_oSpriteLibrary.addSprite("daisy_spritesheet","./sprites/daisy_spritesheet.png");for(var a=0;a<BALL_COLORS;a++)s_oSpriteLibrary.addSprite("ball_"+a,"./sprites/ball_"+a+".png");for(a=0;a<NUM_LEVELS;a++)s_oSpriteLibrary.addSprite("bg_game_"+
(a+1),"./sprites/bg_game_"+(a+1)+".jpg");s_oSpriteLibrary.addSprite("fg_game_1","./sprites/fg_game_1.png");s_oSpriteLibrary.addSprite("fg_game_2","./sprites/fg_game_2.png");s_oSpriteLibrary.addSprite("fg_game_3","./sprites/fg_game_3.png");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;h.refreshLoader(Math.floor(c/b*100));c===b&&this._allResourcesLoaded()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};
this._allResourcesLoaded=function(){h.unload();try{saveItem("ls_available","ok")}catch(l){s_bStorageAvailable=!1}isIOS()||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}));s_oMain.gotoMenu()};this.onLoadedJSON=function(a){s_oLevelSettings=new CLevelSettings(a);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_oMain._initSounds();s_oMain._loadImages()};this.stopUpdate=function(){f=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");createjs.Sound.setMute(!0)};
this.startUpdate=function(){s_iPrevTime=(new Date).getTime();f=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");s_bAudioActive&&createjs.Sound.setMute(!1)};this.gotoMenu=function(){new CMenu;d=STATE_MENU};this.gotoLevelMenu=function(){new CLevelMenu};this.gotoGame=function(a,b){e=new CGame(g,a,b);d=STATE_GAME};this.gotoHelp=function(){new CHelp;d=STATE_HELP};this.levelSelected=function(a){a>=s_iLastLevel&&(s_iLastLevel=a);var b=this.getScoreTillLevel(a);this.gotoGame(a,b)};this._update=
function(a){if(!1!==f){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);d===STATE_GAME&&e.update();void 0!==s_oStage&&s_oStage.update(a)}};s_oMain=this;g=a;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oSoundTrack=null,s_oDrawLayer,s_oStage,s_oMain=null,s_oSpriteLibrary,s_oLevelSettings,s_iLastLevel=1,s_bFullscreen=!1,s_bStorageAvailable=!0;
function CTextButton(a,f,c,b,d,g,h,e){var l,q,p,v,r,n,t,u,y,A;this._init=function(a,b,d,e,c,f,g,h){l=!1;v=[];r=[];A=h;t=createBitmap(d);q=d.width;p=d.height;h=Math.ceil(g/20);u=new createjs.Text(e,"bold "+g+"px "+c,"#000000");var m=u.getBounds();u.textAlign="center";u.textBaseline="alphabetic";u.x=d.width/2+h;u.y=Math.floor(d.height/2)+m.height/3+h;y=new createjs.Text(e,"bold "+g+"px "+c,f);y.textAlign="center";y.textBaseline="alphabetic";y.x=d.width/2;y.y=Math.floor(d.height/2)+m.height/3;n=new createjs.Container;
n.x=a;n.y=b;n.regX=d.width/2;n.regY=d.height/2;n.cursor="pointer";n.addChild(t,u,y);A.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");A.removeChild(n)};this.setVisible=function(a){n.visible=a};this.enable=function(){l=!1;t.filters=[];t.cache(0,0,q,p)};this.disable=function(){l=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100);t.filters=[new createjs.ColorMatrixFilter(a)];t.cache(0,0,q,p)};this._initListener=function(){oParent=this;n.on("mousedown",
this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){v[a]=b;r[a]=d};this.buttonRelease=function(){l||(playSound("press_but",1,0),n.scaleX=1,n.scaleY=1,v[ON_MOUSE_UP]&&v[ON_MOUSE_UP].call(r[ON_MOUSE_UP]))};this.buttonDown=function(){l||(n.scaleX=.9,n.scaleY=.9,v[ON_MOUSE_DOWN]&&v[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){n.x=a;n.y=b};this.changeText=function(a){y.text=a;u.text=a};this.setX=function(a){n.x=a};this.setY=function(a){n.y=
a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(a,f,c,b,d,g,h,e);return this}
function CGfxButton(a,f,c,b){var d,g,h=[],e,l;this._init=function(a,b,c){d=[];g=[];e=createBitmap(c);e.x=a;e.y=b;e.regX=c.width/2;e.regY=c.height/2;e.cursor="pointer";l.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);l.removeChild(e)};this.setVisible=function(a){e.visible=a};this._initListener=function(){e.on("mousedown",this.buttonDown);e.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){d[a]=b;
g[a]=e};this.addEventListenerWithParams=function(a,b,e,c){d[a]=b;g[a]=e;h=c};this.buttonRelease=function(){playSound("press_but",1,0);e.scaleX=1;e.scaleY=1;d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(g[ON_MOUSE_UP],h)};this.buttonDown=function(){e.scaleX=.9;e.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],h)};this.setPosition=function(a,b){e.x=a;e.y=b};this.setX=function(a){e.x=a};this.setY=function(a){e.y=a};this.getButtonImage=function(){return e};this.getX=function(){return e.x};this.getY=
function(){return e.y};l=b;this._init(a,f,c);return this}
function CToggle(a,f,c,b){var d,g,h,e;this._init=function(a,b,c,f){g=[];h=[];var l=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});d=f;e=createSprite(l,"state_"+d,c.width/2/2,c.height/2,c.width/2,c.height);e.x=a;e.y=b;e.stop();e.cursor="pointer";s_oStage.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);s_oStage.removeChild(e)};
this._initListener=function(){e.on("mousedown",this.buttonDown);e.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){g[a]=b;h[a]=d};this.setActive=function(a){d=a;e.gotoAndStop("state_"+d)};this.buttonRelease=function(){e.scaleX=1;e.scaleY=1;playSound("press_but",1,0);d=!d;e.gotoAndStop("state_"+d);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(h[ON_MOUSE_UP],d)};this.buttonDown=function(){e.scaleX=.9;e.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=
function(a,b){e.x=a;e.y=b};this._init(a,f,c,b)}
function CMenu(){var a,f,c,b,d,g,h,e,l=null,q,p,v,r,n=null,t=null;this._init=function(){h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(h);if(s_bStorageAvailable){var u=getItem("frogtastic_level");null!==u&&void 0!==u?s_iLastLevel=parseInt(getItem("frogtastic_level")):saveItem("frogtastic_level",1)}1===s_iLastLevel?(e=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-120,s_oSpriteLibrary.getSprite("but_play"),s_oStage),e.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this)):
(e=new CGfxButton(CANVAS_WIDTH/2-150,CANVAS_HEIGHT-120,s_oSpriteLibrary.getSprite("but_play"),s_oStage),e.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this),l=new CGfxButton(CANVAS_WIDTH/2+150,CANVAS_HEIGHT-120,s_oSpriteLibrary.getSprite("but_continue"),s_oStage),l.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this));if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u=s_oSpriteLibrary.getSprite("audio_icon"),d=CANVAS_WIDTH-u.height/2-10,g=u.height/2+10,q=new CToggle(d,g,u,s_bAudioActive),
q.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);u=s_oSpriteLibrary.getSprite("but_credits");c=u.height/2+10;b=u.height/2+10;p=new CGfxButton(c,b,u,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onButCreditsRelease,this);var u=window.document,y=u.documentElement;n=y.requestFullscreen||y.mozRequestFullScreen||y.webkitRequestFullScreen||y.msRequestFullscreen;t=u.exitFullscreen||u.mozCancelFullScreen||u.webkitExitFullscreen||u.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(n=!1);n&&!1===inIframe()&&
(u=s_oSpriteLibrary.getSprite("but_fullscreen"),a=c+u.width/2+10,f=b-2,r=new CToggle(a,f,u,s_bFullscreen,s_oStage),r.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));v=new createjs.Shape;v.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(v);s_bStorageAvailable||new CAlertSavingBox(TEXT_ERR_LS,s_oStage);createjs.Tween.get(v).to({alpha:0},400).call(function(){v.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){e.unload();
e=null;p.unload();null!==l&&l.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q.unload(),q=null;n&&!1===inIframe()&&r.unload();s_oStage.removeChild(h);h=null;s_oStage.removeChild(v);s_oMenu=v=null};this.refreshButtonPos=function(e,h){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||q.setPosition(d-e,h+g);n&&!1===inIframe()&&r.setPosition(a+e,f+h);p.setPosition(c+e,b+h)};this._exitFromMenu=function(){this.unload();s_oMain.gotoLevelMenu();$(s_oMain).trigger("start_session")};this._onButPlayRelease=
function(){!isIOS()||null!==s_oSoundTrack||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}));if(1<s_iLastLevel){var a=new CMsgBox(TEXT_DELETE_SAVINGS,TEXT_NO,"",TEXT_YES);a.addEventListener(ON_MSG_BOX_LEFT_BUT,function(){a.hide()},this);a.addEventListener(ON_MSG_BOX_RIGHT_BUT,function(){a.hide();s_oMain.clearLocalStorage();s_oMenu._exitFromMenu()},this)}else s_oMenu._exitFromMenu()};this._onButContinueRelease=function(){!isIOS()||null!==s_oSoundTrack||
!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1}));s_oMenu._exitFromMenu()};this._onButCreditsRelease=function(){new CCreditsPanel};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(t.call(window.document),s_bFullscreen=!1):(n.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a,f,c){var b=!1,d,g,h,e,l,q,p,v,r=-1,n,t,u,y,A,D,B,E,w,k,m,z,x,F=null,R,H,Q=null,I=null,C,K,L,O,G,P,J,S,M,N;this._init=function(a,d){createjs.MotionGuidePlugin.install();w=a;e=d;s_oBezier=new CBezier;M=new createjs.Container;L=createBitmap(s_oSpriteLibrary.getSprite(s_oLevelSettings.getBgForLevel(w)));M.addChild(L);s_oStage.addChild(M);L.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);var c=s_oSpriteLibrary.getSprite("base_hero");K=createBitmap(c);K.regX=c.width/2;K.regY=c.height/2;s_oStage.addChild(K);
C=new CHero;J=new createjs.Container;P=new createjs.Container;S=new createjs.Container;s_oStage.addChild(J);s_oStage.addChild(P);s_oStage.addChild(S);N=new createjs.Container;s_oStage.addChild(N);O=createBitmap(s_oSpriteLibrary.getSprite(s_oLevelSettings.getFgForLevel(w)));N.addChild(O);G=new CInterface(e);this.reset();if(!1===s_bMobile){var T=this;s_oStage.addEventListener("stagemousemove",function(a){T._onMouseMove(a.stageX,a.stageY)})}b=!0};this.unload=function(){b=!1;clearInterval(u);createjs.Sound.stop();
G.unload();C.unload();s_oStage.removeAllChildren()};this.reset=function(){d=!0;h=g=!1;v=s_oLevelSettings.getBallSpeedForLevel(w);p=s_oLevelSettings.getBallNumberForLevel(w);A=s_oLevelSettings.getBallColorsForLevel(w);BALL_ROLLING_IN=Math.floor(.33*p);n=0;q=t=1;B=D=0;E=Math.floor(Math.random()*(MAX_TIME_SPAWN_BEE-MIN_TIME_SPAWN_BEE+1))+MIN_TIME_SPAWN_BEE;l=0;R=[];this._initDaisies();var a=s_oLevelSettings.getHeroPosForLevel(w);C.reset(a,A);K.x=a.x;K.y=a.y;null!==Q&&(J.removeChild(Q),J.removeChild(I));
this._initCurve();this._initBall();G.refreshLevel(w);$(s_oMain).trigger("start_level",w)};this._normalize=function(a){var b=this._length(a);return 0<b?{x:a.x/b,y:a.y/b}:a};this._length=function(a){return Math.sqrt(a.x*a.x+a.y*a.y)};this._dotProductV2=function(a,b){return a.x*b.x+a.y*b.y};this._angleBetweenVectors=function(a,b){var d=Math.acos(this._dotProductV2(a,b)/(this._length(a)*this._length(b)));return!0===isNaN(d)?0:d};this._rot90CW=function(a){return{x:a.y,y:-a.x}};this._rot90CCW=function(a){return{x:-a.y,
y:a.x}};this._rotateVector2D=function(a,b){return{x:b.x*Math.cos(a)+b.y*Math.sin(a),y:b.x*-Math.sin(a)+b.y*Math.cos(a)}};this._initCurve=function(){var a,b;a=s_oLevelSettings.getCurveForLevel(w);var d=new createjs.Graphics;m=[];for(b=0;b<a.length-2;++b)for(var c=0===b?new createjs.Point(a[0][0],a[0][1]):new createjs.Point((a[b][0]+a[b+1][0])/2,(a[b][1]+a[b+1][1])/2),e=new createjs.Point(a[b+1][0],a[b+1][1]),f=b<=a.length-4?new createjs.Point((a[b+1][0]+a[b+2][0])/2,(a[b+1][1]+a[b+2][1])/2):new createjs.Point(a[b+
2][0],a[b+2][1]),c=s_oBezier.init(c,e,f,STEP_LENGTH),e=1;e<=c;++e)f=s_oBezier.getAnchorPoint(e),m.push(f);d.beginFill("rgba(0,0,0,0.5)");c={x:m[1][0]-m[0][0],y:m[1][1]-m[0][1]};c=this._normalize(c);c=this._rot90CW(c);c.x*=10;c.y*=10;c.x+=m[0][0];c.y+=m[0][1];a=c.x;b=c.y;d.moveTo(c.x,c.y);for(e=1;e<m.length-1;e++)c={x:m[e+1][0]-m[e][0],y:m[e+1][1]-m[e][1]},c=this._normalize(c),c=this._rot90CW(c),c.x*=10,c.y*=10,c.x+=m[e][0],c.y+=m[e][1],d.lineTo(c.x,c.y);d.lineTo(c.x,c.y);c={x:m[m.length-1][0]-m[m.length-
2][0],y:m[m.length-1][1]-m[m.length-2][1]};c=this._normalize(c);c=this._rot90CCW(c);c.x*=10;c.y*=10;c.x+=m[m.length-1][0];c.y+=m[m.length-1][1];d.lineTo(c.x,c.y);for(e=m.length-2;1<e;e--)c={x:m[e][0]-m[e-1][0],y:m[e][1]-m[e-1][1]},c=this._normalize(c),c=this._rot90CCW(c),c.x*=10,c.y*=10,c.x+=m[e][0],c.y+=m[e][1],d.lineTo(c.x,c.y);d.lineTo(a,b);d.endFill();Q=new createjs.Shape(d);J.addChild(Q);d=m.length;a=s_oSpriteLibrary.getSprite("end_path");I=createBitmap(a);I.x=m[d-9][0];I.y=m[d-9][1];I.regX=
a.width/2;I.regY=a.height/2;J.addChild(I);J.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT)};this._initBall=function(){k=[];var a=this.getRandomBall();k.unshift(a);a.setPos(16,m);r=STATE_GAME_ROLL_IN};this.getRandomBall=function(){p--;return new CBall(Math.floor(Math.random()*A),P)};this._pushNextBall=function(a,b){var c=[];c.push(k[a]);for(var e=a;e<k.length-1;++e)if(16>=k[e+1].getFotogram()-k[e].getFotogram())16>k[e+1].getFotogram()-k[e].getFotogram()&&k[e+1].setPos(k[e].getFotogram()+16,m),c.push(k[e+1]);
else break;for(e=0;e<c.length;++e)c[e].increasePos(b,m);if(k[k.length-1].getFotogram()>=m.length-17){d=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack.pause(),playSound("game_over",1,0).addEventListener("complete",this._onSoundGameOverComplete);s_oStage.removeEventListener("stagemousemove");h=g=!1;q=1;k[k.length-1].unload();k.splice(k.length-1,1);r=STATE_GAME_ROLL_OUT}};this.onIntroduceBall=function(){if(0!==k.length&&(s_oGame._pushNextBall(0,1),32===k[0].getFotogram()&&0!==p)){var a=
s_oGame.getRandomBall();k.unshift(a);a.setPos(16,m)}};this._initDaisies=function(){if(H)for(var a=0;a<H.length;a++)H[a].unload();a=s_oLevelSettings.getDaisyPosForLevel(w);H=[];for(var b=0;b<a.length;b++)H[b]=new CDaisy(a[b].x,a[b].y,M)};this._spawnBee=function(){B=0;new CBee(s_oLevelSettings.getRandBeeTrajectory(),N);E=Math.floor(Math.random()*(MAX_TIME_SPAWN_BEE-MIN_TIME_SPAWN_BEE+1))+MIN_TIME_SPAWN_BEE};this.showDaisies=function(){for(var a=0;a<H.length;a++)H[a].show(1500*Math.random())};this.shoot=
function(){playSound("shot",1,0);C.playAnim("shot");var a=(C.getRotation()+90)*Math.PI/180,b=C.getCurrentBall();b.changePos(C.getX()+60*Math.cos(a),C.getY()+60*Math.sin(a));P.addChild(b.getSprite());b.setContainer(P);z.push([b,a]);r=STATE_GAME_SHOOTING};this._checkCollision=function(a){a=a[0];for(var b=0;b<k.length;++b)if((k[b].getX()-a.getX())*(k[b].getX()-a.getX())+(k[b].getY()-a.getY())*(k[b].getY()-a.getY())<=BALL_DIAMETER_SQUARE)return b;return-1};this._insertBall=function(a,b,c){var d;"next"===
c?(d=k[b].getFotogram()+16,k[b+1]&&32>k[b+1].getFotogram()-k[b].getFotogram()&&(x.push([a,k[b+1]]),g=!0)):k[b-1]&&32>k[b].getFotogram()-k[b-1].getFotogram()?(d=k[b-1].getFotogram()+16,x.push([a,k[b]]),g=!0):d=k[b].getFotogram()-16;b=m[d][0];c=m[d][1];var e=this;createjs.Tween.get(a.getSprite()).to({x:b,y:c},200).call(function(){e.motionFinished(a,d)})};this.motionFinished=function(a,b){for(var c,d=0;d<k.length;++d){if(k[d].getFotogram()>b){c=d;break}d===k.length-1&&(c=d+1)}x.splice(x.indexOf(a),1);
a.setPos(b,m);k.splice(c,0,a);k[c-1]&&k[c-1].getIndex()===k[c].getIndex()&&17<k[c].getFotogram()-k[c-1].getFotogram()&&this._addToBallAttracted(k[c]);k[c+1]&&k[c+1].getIndex()===k[c].getIndex()&&17<k[c+1].getFotogram()-k[c].getFotogram()&&this._addToBallAttracted(k[c+1]);this._clearCheck(c,!0)};this._addToBallAttracted=function(a){null===F&&(F=[]);F.push(a);setTimeout(function(){h=!0},400)};this._clearCheck=function(a,b){var c=[];c.push(k[a]);for(var d=k[a].getIndex(),e=a+1;k[e];)if(k[e].getIndex()===
d)if(17>=k[e].getFotogram()-k[e-1].getFotogram())c.push(k[e]),++e;else if(b)break;else c.push(k[e]),++e;else break;for(e=a-1;k[e];)if(k[e].getIndex()===d)if(17>=k[e+1].getFotogram()-k[e].getFotogram())c.push(k[e]),--e;else if(b)break;else c.push(k[e]),--e;else break;++e;2<c.length&&b&&this._clearBall(e,c);return c.length};this._attract=function(){if(0!==F.length)for(var a=0;a<F.length;++a){var b=k.indexOf(F[a]);if(-1!==b&&k[b-1])if(F[a].getIndex()===k[b-1].getIndex()){var c=19<F[a].getFotogram()-
k[b-1].getFotogram()?3:F[a].getFotogram()-k[b-1].getFotogram()-16;this._pushNextBall(b,-c);16>=F[a].getFotogram()-k[b-1].getFotogram()&&(q++,F.splice(a,1),this._clearCheck(b-1,!0),0===F.length&&(h=!1,q=1))}else F.splice(a,1),n>t&&(t=n),n=0}else h=!1,q=1};this._checkPushCollision=function(){if(0!==x.length)for(var a=0;a<x.length;++a){for(var b=(x[a][0].getX()-x[a][1].getX())*(x[a][0].getX()-x[a][1].getX())+(x[a][0].getY()-x[a][1].getY())*(x[a][0].getY()-x[a][1].getY()),b=b<BALL_DIAMETER_SQUARE?!0:
!1,c=0;b;)++c,b=(x[a][0].getX()-m[x[a][1].getFotogram()+c][0])*(x[a][0].getX()-m[x[a][1].getFotogram()+c][0])+(x[a][0].getY()-m[x[a][1].getFotogram()+c][1])*(x[a][0].getY()-m[x[a][1].getFotogram()+c][1]),b=b<BALL_DIAMETER_SQUARE?!0:!1;b=k.indexOf(x[a][1]);-1!==b&&this._pushNextBall(b,c)}else g=!1};this._clearBall=function(a,c){++n;playSound("combo",1,0);for(var f=0,m=0;m<c.length;++m)c[m].explode(),f+=COMBO_VALUE;f*=q;e+=f;l+=f;G.refreshScore(e);if(k.length===c.length){d=!1;y=k[k.length-1].getFotogram();
setTimeout(this._gamePass,600);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack.pause(),playSound("win",1,0).addEventListener("complete",this._onSoundGameOverComplete);b=!1;this.showDaisies()}k.splice(a,c.length);0===p&&this._checkColor(c[0].getIndex());k[a-1]&&k[a]&&k[a-1].getIndex()===k[a].getIndex()?(3>this._clearCheck(a,!1)&&(n>t&&(t=n),n=0),this._addToBallAttracted(k[a])):(n>t&&(t=n),n=0)};this._gamePass=function(){u=setInterval(s_oGame._extraScore,v)};this._extraScore=function(){y+
16<m.length-17?(y+=16,new CExtraScore(m[y][0],m[y][1],S),e+=EXTRA_SCORE,l+=EXTRA_SCORE,G.refreshScore(e)):($(s_oMain).trigger("end_level",w),clearInterval(u),s_oStage.removeEventListener("stagemousemove"),d=!1,s_oMain.setLocalStorageScore(l,e,w),w++,w>s_oLevelSettings.getNumLevels()?(w--,G.win(e)):(s_oMain.setLocalStorageLevel(w),G.nextLevel(w,e)))};this._checkColor=function(a){for(var b=0;b<k.length;++b)if(k[b].getIndex()===a)return;for(b=0;b<z.length;++b)if(z[b].getIndex()===a)return;C.colorCleared(a)};
this.nextLevel=function(){M.removeChild(L);N.removeChild(O);L=createBitmap(s_oSpriteLibrary.getSprite(s_oLevelSettings.getBgForLevel(w)));M.addChild(L);O=createBitmap(s_oSpriteLibrary.getSprite(s_oLevelSettings.getFgForLevel(w)));N.addChild(O);this.reset();b=!0};this.onShot=function(a,b){if(d&&C.canShoot()){if(s_bMobile){var c=a-C.getX()*s_iScaleFactor,e=b-C.getY()*s_iScaleFactor;C.rotate(180*Math.atan2(e,c)/Math.PI-90)}this.shoot()}};this._onMouseMove=function(a,b){var c=a-C.getX()*s_iScaleFactor,
e=b-C.getY()*s_iScaleFactor;C.rotate(180*Math.atan2(e,c)/Math.PI-90)};this.onExit=function(){createjs.Sound.stop();this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",e)};this._onSoundGameOverComplete=function(){s_oSoundTrack.resume()};this._updateMove=function(){D+=s_iTimeElaps;D>v&&(D=0,this.onIntroduceBall())};this._updateRollOut=function(){for(var a=k.length-1;0<=a;--a)k[a].getFotogram()>m.length-17?(k[a].unload(),k.splice(a,1),0===k.length&&(r=
-1,G.gameOver(e),b=!1)):k[a].increasePos(8,m)};this._updateRollIn=function(){if(k.length<BALL_ROLLING_IN){for(var a=0;a<k.length;++a)k[a].increasePos(4,m);32===k[0].getFotogram()&&(a=this.getRandomBall(),k.unshift(a),a.setPos(16,m))}else r=-1,z=[],x=[],C.start(),r=STATE_GAME_BALL_MOVE};this._updateShooting=function(){if(0!==z.length)for(var a=0;a<z.length;++a)if(0<z[a][0].getX()&&z[a][0].getX()<CANVAS_WIDTH&&0<z[a][0].getY()&&z[a][0].getY()<CANVAS_HEIGHT){var b=this._checkCollision(z[a]);if(-1===
b)z[a][0].increasePosWithNumbers(Math.cos(z[a][1])*BALL_SHOOTED_SPEED,Math.sin(z[a][1])*BALL_SHOOTED_SPEED);else{var c=z[a][0],e=z[a][1],d=Math.sqrt((k[b].getX()-c.getX())*(k[b].getX()-c.getX())+(k[b].getY()-c.getY())*(k[b].getY()-c.getY()));z[a][0].decreasePos((BALL_DIAMETER-d)*Math.cos(e),(BALL_DIAMETER-d)*Math.sin(e));var e=m[k[b].getFotogram()-BALL_RADIUS][0],d=m[k[b].getFotogram()-BALL_RADIUS][1],e=Math.sqrt((c.getX()-e)*(c.getX()-e)+(c.getY()-d)*(c.getY()-d)),d=m[k[b].getFotogram()+BALL_RADIUS][0],
f=m[k[b].getFotogram()+BALL_RADIUS][1],c=Math.sqrt((c.getX()-d)*(c.getX()-d)+(c.getY()-f)*(c.getY()-f));this._insertBall(z[a][0],b,e>c?"next":"previous");z.splice(a,1)}}else z[a][0].unload(),z.splice(a,1);else r=-1};this.update=function(){if(!1!==b){!0===h&&this._attract();!0===g&&this._checkPushCollision();switch(r){case STATE_GAME_ROLL_IN:this._updateRollIn();break;case STATE_GAME_ROLL_OUT:this._updateRollOut();break;case STATE_GAME_SHOOTING:this._updateShooting();this._updateMove();break;default:this._updateMove()}for(var a=
0;a<R.length;a++)R[a].refreshPos();B+=s_iTimeElaps;B>E&&this._spawnBee()}};s_oGame=this;COMBO_VALUE=a.combo_value;EXTRA_SCORE=a.extra_score;this._init(f,c)}var s_oGame,s_oBezier;
function CInterface(a){var f,c,b,d,g,h,e,l,q,p,v,r,n,t,u,y,A,D,B,E,w=null,k=null;this._init=function(a){l=e=10;t=new createjs.Text(TEXT_SCORE+" "+a,"26px "+FONT_GAME,"#008733");t.x=e;t.y=l;t.textAlign="left";t.outline=2;s_oStage.addChild(t);n=new createjs.Text(TEXT_SCORE+" "+a,"26px "+FONT_GAME,"#fff");n.x=e;n.y=l;n.textAlign="left";s_oStage.addChild(n);g=10;h=46;r=new createjs.Text(TEXT_LEVEL+" "+s_iLastLevel,"22px "+FONT_GAME,"#008733");r.x=g;r.y=h;r.textAlign="left";r.outline=2;s_oStage.addChild(r);
v=new createjs.Text(TEXT_LEVEL+" "+s_iLastLevel,"22px "+FONT_GAME,"#fff");v.x=g;v.y=h;v.textAlign="left";s_oStage.addChild(v);var m=this;y=createBitmap(s_oSpriteLibrary.getSprite("hit_area"));s_oStage.addChild(y);y.on("pressup",function(a){m._onTapScreen(a.stageX,a.stageY)});a=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-a.width/2;c=a.height/2+4;u=new CGfxButton(f,c,a,s_oStage);u.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(q=f-a.width,p=a.height/
2+4,a=s_oSpriteLibrary.getSprite("audio_icon"),A=new CToggle(q,p,a,s_bAudioActive),A.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),b=q-a.width/2,d=p):(b=u.getX()-a.width,d=a.height/2+4);a=window.document;var x=a.documentElement;w=x.requestFullscreen||x.mozRequestFullScreen||x.webkitRequestFullScreen||x.msRequestFullscreen;k=a.exitFullscreen||a.mozCancelFullScreen||a.webkitExitFullscreen||a.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(w=!1);w&&!1===inIframe()&&(a=s_oSpriteLibrary.getSprite("but_fullscreen"),
E=new CToggle(b,d,a,s_bFullscreen,s_oStage),E.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));B=new CNextLevel;D=new CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){u.unload();u=null;!1===DISABLE_SOUND_MOBILE&&(A.unload(),A=null);w&&!1===inIframe()&&E.unload();s_oStage.removeAllChildren();s_oInterface=null};this.refreshButtonPos=function(a,k){n.x=e+a;n.y=l+k;v.x=g+a;v.y=h+k;t.x=e+a;t.y=l+k;r.x=g+a;r.y=h+k;u.setPosition(f-
a,c+k);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||A.setPosition(q-a,k+p);w&&!1===inIframe()&&E.setPosition(b-a,d+k)};this._onTapScreen=function(a,b){s_oGame.onShot(a,b)};this.gameOver=function(a){D.show(a,!1)};this.win=function(a){D.show(a,!0)};this.nextLevel=function(a,b){B.show(a,b)};this.refreshScore=function(a){n.text=TEXT_SCORE+" "+a;t.text=TEXT_SCORE+" "+a};this.refreshLevel=function(a){v.text=TEXT_LEVEL+" "+a;r.text=TEXT_LEVEL+" "+a};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=
function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(k.call(window.document),s_bFullscreen=!1):(w.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CEndPanel(a){var f,c,b,d,g,h;this._init=function(a){f=createBitmap(a);d=new createjs.Text(TEXT_CONGRATS,"32px "+FONT_GAME,"#008733");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-70;d.outline=3;d.textAlign="center";g=new createjs.Text(TEXT_CONGRATS,"32px "+FONT_GAME,"#ffffff");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-70;g.textAlign="center";c=new createjs.Text(TEXT_FINAL_SCORE+"\n99999","26px "+FONT_GAME,"#008733");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;c.lineHeight=50;c.outline=3;c.textAlign="center";
b=new createjs.Text(TEXT_FINAL_SCORE+"\n99999","26px "+FONT_GAME,"#ffffff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;b.lineHeight=50;b.textAlign="center";h=new createjs.Container;h.alpha=0;h.visible=!1;h.addChild(f,c,b,d,g);s_oStage.addChild(h)};this.unload=function(){h.off("mousedown",this._onExit);s_oStage.removeChild(h)};this._initListener=function(){h.on("mousedown",this._onExit);$(s_oMain).trigger("show_interlevel_ad")};this.show=function(a,f){f?(d.text=TEXT_CONGRATS,g.text=TEXT_CONGRATS):(d.text=
TEXT_GAMEOVER,g.text=TEXT_GAMEOVER);c.text=TEXT_FINAL_SCORE+"\n"+a;b.text=TEXT_FINAL_SCORE+"\n"+a;h.visible=!0;var e=this;createjs.Tween.get(h).to({alpha:1},500).call(function(){e._initListener()});$(s_oMain).trigger("save_score",a)};this._onExit=function(){h.off("mousedown");s_oGame.onExit()};this._init(a);return this}
function CTweenController(){this.tweenValue=function(a,f,c){return a+c*(f-a)};this.easeLinear=function(a,f,c,b){return c*a/b+f};this.easeInCubic=function(a,f,c,b){b=(a/=b)*a*a;return f+c*b};this.easeBackInQuart=function(a,f,c,b){b=(a/=b)*a;return f+c*(2*b*b+2*b*a+-3*b)};this.easeInBack=function(a,f,c,b){return c*(a/=b)*a*(2.70158*a-1.70158)+f};this.easeOutCubic=function(a,f,c,b){return c*((a=a/b-1)*a*a+1)+f}}
function CLevelSettings(a){var f,c,b,d,g,h,e,l,q,p;this._init=function(a){f=a;NUM_LEVELS=Object.keys(f).length;this._initBallSpeed();this._initBallNumber();this._initBallColors();this._initHeroPos();this._initCurveLevel();this._initBgLevel();this._initBeeTraj();this._initDaisySpawnPos()};this._initBallSpeed=function(){c=[];for(var a=0;a<NUM_LEVELS;a++)c[a]=f[a].ball_speed};this._initBallNumber=function(){b=[];for(var a=0;a<NUM_LEVELS;a++)b[a]=f[a].ball_number};this._initBallColors=function(){d=[];
for(var a=0;a<NUM_LEVELS;a++)d[a]=f[a].num_colors};this._initHeroPos=function(){g=[];for(var a=0;a<NUM_LEVELS;a++)g[a]=new createjs.Point(f[a].hero_pos.x,f[a].hero_pos.y)};this._initCurveLevel=function(){h=[];for(var a=0;a<NUM_LEVELS;a++){h[a]=[];for(var b=f[a].curve_point,c=0;c<b.length;c++)h[a].push([b[c].x,b[c].y])}};this._initBgLevel=function(){e=[];l=[];for(var a=0;a<NUM_LEVELS;a++)e[a]=f[a].bg_image,l[a]=f[a].fg_image};this._initBeeTraj=function(){q=[{path:[-58,267,100,100,1005,352],start_rot:0,
final_rot:25,start:0,end:1,time:12E3},{path:[-33,458,300,470,980,329],start_rot:0,final_rot:-25,start:0,end:1,time:12E3},{path:[304,574,300,54,500,-100],start_rot:-90,final_rot:-50,start:0,end:1,time:12E3}]};this._initDaisySpawnPos=function(){p=[[{x:80,y:274},{x:224,y:296},{x:452,y:358},{x:616,y:288},{x:845,y:344}],[{x:850,y:470},{x:877,y:152},{x:256,y:126},{x:650,y:277}],[{x:57,y:277},{x:627,y:150},{x:867,y:433},{x:238,y:510}],[{x:600,y:35},{x:85,y:186},{x:200,y:496},{x:782,y:160},{x:720,y:470},
{X:890,Y:400}],[{x:82,y:166},{x:325,y:205},{x:373,y:338},{x:571,y:200},{x:845,y:278}],[{x:93,y:150},{x:374,y:30},{x:334,y:342},{x:870,y:163},{x:892,y:405}],[{x:70,y:150},{x:135,y:480},{x:387,y:258},{x:786,y:360},{x:880,y:194}],[{x:87,y:154},{x:141,y:478},{x:314,y:260},{x:571,y:347},{x:847,y:160},{x:854,y:425}],[{x:69,y:154},{x:83,y:332},{x:289,y:500},{x:834,y:155},{x:900,y:392}],[{x:77,y:170},{x:200,y:490},{x:328,y:311},{x:682,y:344},{x:896,y:217}],[{x:52,y:147},{x:300,y:248},{x:576,y:284},{x:847,
y:168},{x:873,y:427}],[{x:82,y:122},{x:90,y:343},{x:308,y:113},{x:784,y:146},{x:894,y:334}],[{x:49,y:162},{x:400,y:61},{x:607,y:34},{x:482,y:266},{x:893,y:200}]]};this.getBallSpeedForLevel=function(a){return c[a-1]};this.getBallNumberForLevel=function(a){return b[a-1]};this.getBallColorsForLevel=function(a){return d[a-1]};this.getHeroPosForLevel=function(a){return g[a-1]};this.getCurveForLevel=function(a){return h[a-1]};this.getNumLevels=function(){return h.length};this.getBgForLevel=function(a){return e[a-
1]};this.getFgForLevel=function(a){return l[a-1]};this.getRandBeeTrajectory=function(){return q[Math.floor(Math.random()*q.length)]};this.getDaisyPosForLevel=function(a){return p[a-1]};this._init(a)}
function CHero(){var a=!1,f,c,b,d,g,h,e,l;this._init=function(){var a={images:[s_oSpriteLibrary.getSprite("hero")],frames:{width:HERO_WIDTH,height:HERO_HEIGHT},animations:{idle:[0],shot:[0,11,"idle"]}},a=new createjs.SpriteSheet(a);l=new createjs.Container;l.regX=HERO_WIDTH/2;l.regY=HERO_HEIGHT/2;s_oStage.addChild(l);h=new createjs.Container;l.addChild(h);e=new createjs.Container;l.addChild(e);g=createSprite(a,"idle",0,0,HERO_WIDTH,HERO_HEIGHT);e.addChild(g)};this.reset=function(a,e){f=e;void 0!==
b&&null!==b&&b.unload();void 0!==d&&null!==d&&d.unload();l.x=a.x;l.y=a.y;c=[];for(var g=0;g<f;g++)c[g]=!0};this.unload=function(){};this.rotate=function(a){l.rotation=a};this.start=function(){b=this._getRandomBall();b.changePos(HERO_WIDTH/2,HERO_HEIGHT/2+36);d=this._getRandomBall();d.changePos(HERO_WIDTH/2,HERO_HEIGHT/2-12);var a=this;createjs.Tween.get(b.getSprite()).to({y:b.getY()+25},300).call(function(){a._onBallReady()});createjs.Tween.get(d.getSprite()).to({y:d.getY()+16},300)};this._getRandomBall=
function(){var a;if(!0===this._checkIfAllColorsNotAvailable())return null;do{var b=Math.floor(Math.random()*f),d=!1;if(!0===c[b]){a=new CBall(b,h);break}}while(!1===d);return a};this._checkIfAllColorsNotAvailable=function(){for(var a=!0,b=0;b<c.length;b++)!0===c[b]&&(a=!1);return a};this._nextShoot=function(){null!==b&&b.unload();b=d;b.changePos(HERO_WIDTH/2,HERO_HEIGHT/2+36);d=this._getRandomBall();d.changePos(HERO_WIDTH/2,HERO_HEIGHT/2-12);var a=this;createjs.Tween.get(b.getSprite()).to({y:b.getY()+
25},300).call(function(){a._onBallReady()});createjs.Tween.get(d.getSprite()).to({y:d.getY()+16},300)};this.playAnim=function(a){g.gotoAndPlay(a)};this.colorCleared=function(a){c[a]=!1;b.getIndex()===a&&(b.unload(),b=this._getRandomBall(),null!==b&&b.changePos(HERO_WIDTH/2,HERO_HEIGHT/2+61));d.getIndex()===a&&(d.unload(),d=this._getRandomBall(),null!==d&&d.changePos(HERO_WIDTH/2,HERO_HEIGHT/2+4))};this._onBallReady=function(){a=!0};this.getCurrentBall=function(){a=!1;var c=b;this._nextShoot();return c};
this.getX=function(){return l.x};this.getY=function(){return l.y};this.getRotation=function(){return l.rotation};this.canShoot=function(){return a};this._init()}
function CBezier(){var a,f,c,b,d,g,h,e,l,q,p,v;this.init=function(r,n,t,u){a=r;f=n;c=t;d=a.x-2*f.x+c.x;g=a.y-2*f.y+c.y;h=2*f.x-2*a.x;e=2*f.y-2*a.y;l=4*(d*d+g*g);q=4*(d*h+g*e);p=h*h+e*e;v=this._length(1);b=Math.floor(v/u);v%u>u/2&&b++;return b};this._speed=function(a){return Math.sqrt(l*a*a+q*a+p)};this._length=function(a){var b=Math.sqrt(p+a*(q+l*a));return(2*Math.sqrt(l)*(2*l*a*b+q*(b-Math.sqrt(p)))+(q*q-4*l*p)*(Math.log(q+2*Math.sqrt(l)*Math.sqrt(p))-Math.log(q+2*l*a+2*Math.sqrt(l)*b)))/(8*Math.pow(l,
1.5))};this.invertL=function(a,b){var c=a,d;do{d=c-(this._length(c)-b)/this._speed(c);if(1E-6>Math.abs(c-d))break;c=d}while(1);return d};this.getAnchorPoint=function(d){if(0<=d&&d<=b){var e=d/b,e=this.invertL(e,e*v);d=(1-e)*(1-e)*a.x+2*(1-e)*e*f.x+e*e*c.x;var g=(1-e)*(1-e)*a.y+2*(1-e)*e*f.y+e*e*c.y,h=new createjs.Point((1-e)*a.x+e*f.x,(1-e)*a.y+e*f.y),e=new createjs.Point((1-e)*f.x+e*c.x,(1-e)*f.y+e*c.y);return[d,g,180*Math.atan2(e.y-h.y,e.x-h.x)/Math.PI]}return[]}}
function CBall(a,f){var c,b,d,g,h;this._init=function(a,f){c=a;b=0;h=f;var e=s_oSpriteLibrary.getSprite("ball_"+c);BALL_DIAMETER=e.width;BALL_DIAMETER_SQUARE=BALL_DIAMETER*BALL_DIAMETER;BALL_RADIUS=BALL_DIAMETER/2;e=new createjs.SpriteSheet({images:[e],frames:{width:BALL_DIAMETER,height:BALL_DIAMETER,regX:BALL_RADIUS,regY:BALL_RADIUS},animations:{move:[0,49]}});d=createSprite(e,null,BALL_RADIUS,BALL_RADIUS,BALL_DIAMETER,BALL_DIAMETER);d.stop();h.addChild(d)};this.unload=function(){h.removeChild(g);
h.removeChild(d)};this.nextFrame=function(){d.gotoAndStop(50===d.currentFrame+1?0:d.currentFrame+1)};this.prevFrame=function(){d.gotoAndStop(0>d.currentFrame-1?49:d.currentFrame-1)};this.setPos=function(a,c){a>b?this.nextFrame():a<b&&this.prevFrame();b=a;d.x=c[b][0];d.y=c[b][1];d.rotation=c[b][2]-90};this.changePos=function(a,b){d.x=a;d.y=b};this.increasePosWithNumbers=function(a,b){d.x+=a;d.y+=b};this.decreasePos=function(a,b){d.x-=a;d.y-=b};this.increasePos=function(a,c){this.setPos(b+a,c)};this.setContainer=
function(a){d.mask=null;h=a};this.explode=function(){var a={images:[s_oSpriteLibrary.getSprite("explosion")],frames:{width:30,height:30,regX:15,regY:15},animations:{show:[0,19],hide:[20]}},b=this,a=new createjs.SpriteSheet(a,"show");g=new createjs.Sprite(a);g.addEventListener("animationend",function(){b.onExplosionEnd()});h.addChild(g);g.x=d.x;g.y=d.y;g.gotoAndPlay("show");d.visible=!1};this.onExplosionEnd=function(){h.removeChild(g);h.removeChild(d)};this.rollInStage=function(){};this.getFotogram=
function(){return b};this.getSprite=function(){return d};this.getIndex=function(){return c};this.getX=function(){return d.x};this.getY=function(){return d.y};this._init(a,f)}
function CNextLevel(){var a,f,c,b,d,g;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));c=new createjs.Text("LEVEL 2","48px "+FONT_GAME,"#008733");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2-30;c.outline=2;c.textAlign="center";f=new createjs.Text("LEVEL 2","48px "+FONT_GAME,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-30;f.textAlign="center";d=new createjs.Text("SCORE 99999","34px "+FONT_GAME,"#008733");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2+30;d.outline=2;d.textAlign="center";
b=new createjs.Text("SCORE 99999","34px "+FONT_GAME,"#ffffff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2+30;b.textAlign="center";g=new createjs.Container;g.alpha=0;g.visible=!1;g.addChild(a,c,f,d,b);s_oStage.addChild(g)};this.show=function(a,e){c.text=TEXT_LEVEL+" "+a;f.text=TEXT_LEVEL+" "+a;d.text=TEXT_SCORE+" "+e;b.text=TEXT_SCORE+" "+e;g.visible=!0;var h=this;createjs.Tween.get(g).to({alpha:1},500).call(function(){h._initListener()})};this._initListener=function(){g.on("mousedown",this._onExit);$(s_oMain).trigger("show_interlevel_ad")};
this._onExit=function(){g.off("mousedown");g.alpha=0;g.visible=!1;s_oGame.nextLevel()};this._init()}function CExtraScore(a,f,c){var b;this._init=function(a,c,f){var e=s_oSpriteLibrary.getSprite("extra_score");b=createBitmap(e);b.x=a;b.y=c;b.regX=e.width/2;b.regY=e.height/2;b.alpha=0;f.addChild(b);createjs.Tween.get(b).to({alpha:1},1E3).call(function(){f.removeChild(b)})};this._init(a,f,c)}
function CLevelMenu(){var a,f,c,b,d,g,h,e,l,q,p,v,r,n,t,u=null,y=null,A,D,B,E,w=null,k=null;this._init=function(){l=0;B=new createjs.Container;s_oStage.addChild(B);var m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu_level"));B.addChild(m);h=CANVAS_WIDTH/2;e=60;D=new createjs.Text(TEXT_SELECT_LEVEL,"40px "+FONT_GAME,"#008733");D.x=h;D.y=e;D.textAlign="center";D.outline=3;B.addChild(D);A=new createjs.Text(TEXT_SELECT_LEVEL,"40px "+FONT_GAME,"#fff");A.x=h;A.y=e;A.textAlign="center";B.addChild(A);
m=createBitmap(s_oSpriteLibrary.getSprite("fg_game_1"));B.addChild(m);m=s_oSpriteLibrary.getSprite("but_exit");d=CANVAS_WIDTH-m.width/2-10;g=m.height/2+10;n=new CGfxButton(d,g,m,B);n.addEventListener(ON_MOUSE_UP,this._onExit,this);q=m.height;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c=n.getX()-m.width-10,b=m.height/2+10,t=new CToggle(c,b,s_oSpriteLibrary.getSprite("audio_icon"),s_bAudioActive),t.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);var m=window.document,p=m.documentElement;w=
p.requestFullscreen||p.mozRequestFullScreen||p.webkitRequestFullScreen||p.msRequestFullscreen;k=m.exitFullscreen||m.mozCancelFullScreen||m.webkitExitFullscreen||m.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(w=!1);w&&!1===inIframe()&&(m=s_oSpriteLibrary.getSprite("but_fullscreen"),a=m.width/4+10,f=m.height/2+4,E=new CToggle(a,f,m,s_bFullscreen,s_oStage),E.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));this._checkBoundLimits();v=[];for(var m=Math.floor((CANVAS_WIDTH-2*EDGEBOARD_X)/NUM_COLS_PAGE_LEVEL)/
2,x=p=0;x<NUM_COLS_PAGE_LEVEL;x++)v.push(p),p+=2*m;r=[];this._createNewLevelPage(0,NUM_LEVELS);if(1<r.length){for(m=1;m<r.length;m++)r[m].visible=!1;u=new CGfxButton(CANVAS_WIDTH/2+280,CANVAS_HEIGHT-80,s_oSpriteLibrary.getSprite("arrow_right"),B);u.addEventListener(ON_MOUSE_UP,this._onRight,this);y=new CGfxButton(CANVAS_WIDTH/2-280,CANVAS_HEIGHT-80,s_oSpriteLibrary.getSprite("arrow_left"),B);y.addEventListener(ON_MOUSE_UP,this._onLeft,this)}this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=
function(){for(var a=0;a<p.length;a++)p[a].unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||t.unload();w&&!1===inIframe()&&E.unload();n.unload();null!==y&&(y.unload(),u.unload());s_oStage.removeChild(B);s_oLevelMenu=null};this.refreshButtonPos=function(h,k){D.y=e+k;A.y=e+k;n.setPosition(d-h,g+k);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||t.setPosition(c-h,k+b);w&&!1===inIframe()&&E.setPosition(a+h,f+k)};this._checkBoundLimits=function(){for(var a=s_oSpriteLibrary.getSprite("but_level"),b=0,c=CANVAS_HEIGHT-
2*EDGEBOARD_Y-2*q,e=0;b<c;)b+=a.height+20,e++;NUM_ROWS_PAGE_LEVEL>e&&(NUM_ROWS_PAGE_LEVEL=e);c=b=0;e=CANVAS_WIDTH-2*EDGEBOARD_X;for(a=s_oSpriteLibrary.getSprite("but_level");c<e;)c+=a.width/2+5,b++;NUM_COLS_PAGE_LEVEL>b&&(NUM_COLS_PAGE_LEVEL=b)};this._createNewLevelPage=function(a,b){var c=new createjs.Container;B.addChild(c);r.push(c);p=[];for(var e=0,d=0,f=1,g=!1,h=s_oSpriteLibrary.getSprite("but_level"),k=a;k<b;k++){var l=new CLevelBut(v[e]+h.width/4,d+h.height/2,k+1,h,k+1>s_iLastLevel?!1:!0,c);
l.addEventListenerWithParams(ON_MOUSE_UP,this._onButLevelRelease,this,k);p.push(l);e++;if(e===v.length&&(e=0,d+=h.height+20,f++,f>NUM_ROWS_PAGE_LEVEL)){g=!0;break}}c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2+30;c.regX=c.getBounds().width/2;c.regY=c.getBounds().height/2;g&&this._createNewLevelPage(k+1,b)};this._onRight=function(){r[l].visible=!1;l++;l>=r.length&&(l=0);r[l].visible=!0};this._onLeft=function(){r[l].visible=!1;l--;0>l&&(l=r.length-1);r[l].visible=!0};this._onButLevelRelease=function(a){s_oLevelMenu.unload();
s_oMain.levelSelected(a+1)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?(k.call(window.document),s_bFullscreen=!1):(w.call(window.document.documentElement),s_bFullscreen=!0);sizeHandler()};this._onExit=function(){s_oMain.gotoMenu()};s_oLevelMenu=this;this._init()}var s_oLevelMenu=null;
function CLevelBut(a,f,c,b,d,g){var h,e,l,q=[],p=[],v,r,n,t,u;this._init=function(a,b,c,d,f){e=[];l=[];t=new createjs.Container;u.addChild(t);var g=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});h=f;n=createSprite(g,"state_"+h,d.width/2/2,d.height/2,d.width/2,d.height);n.mouseEnabled=f;n.x=a;n.y=b;n.stop();s_bMobile||(t.cursor="pointer");t.addChild(n);q.push(n);v=new createjs.Text(c,"40px "+
FONT_GAME,"#008733");v.x=a;v.y=b+20;v.textAlign="center";v.textBaseline="alphabetic";v.lineWidth=200;v.outline=4;t.addChild(v);r=new createjs.Text(c,"40px "+FONT_GAME,"#fff");r.x=a;r.y=b+20;r.textAlign="center";r.textBaseline="alphabetic";r.lineWidth=200;t.addChild(r);f||(r.color="#b4b4b4",v.color="#606161");this._initListener()};this.unload=function(){t.off("mousedown",this.buttonDown);t.off("pressup",this.buttonRelease);t.removeChild(n)};this._initListener=function(){t.on("mousedown",this.buttonDown);
t.on("pressup",this.buttonRelease)};this.viewBut=function(a){t.addChild(a)};this.addEventListener=function(a,b,c){e[a]=b;l[a]=c};this.addEventListenerWithParams=function(a,b,c,d){e[a]=b;l[a]=c;p=d};this.ifClickable=function(){return!0===t.mouseEnabled?1:0};this.setActive=function(a,b){h=b;q[a].gotoAndStop("state_"+h);q[a].mouseEnabled=!0;h?(r.color="#69b8d5",v.color="#004e6f"):(r.color="#b4b4b4",v.color="#606161")};this.buttonRelease=function(){h&&(playSound("click",1,0),e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(l[ON_MOUSE_UP],
p))};this.buttonDown=function(){e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],p)};this.setPosition=function(a,b){t.x=a;t.y=b};this.setVisible=function(a){t.visible=a};u=g;this._init(a,f,c,b,d,g)}
function CMsgBox(a,f,c,b){var d,g,h,e,l,q,p;this._init=function(a,b,c,f){d=[];g=[];p=new createjs.Container;s_oStage.addChild(p);var n=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));p.addChild(n);h=new createjs.Text("","30px "+FONT_GAME,"#fff");h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=320;h.lineHeight=40;h.x=CANVAS_WIDTH/2;h.y=220;p.addChild(h);e=new CTextButton(CANVAS_WIDTH/2-100,CANVAS_HEIGHT-180,s_oSpriteLibrary.getSprite("but_generic_small"),"LEFT",FONT_GAME,"#ffffff",
24,p);e.addEventListener(ON_MOUSE_UP,this._onButLeftDownRelease,this);l=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-180,s_oSpriteLibrary.getSprite("but_generic_small"),"CENTER",FONT_GAME,"#ffffff",24,p);l.addEventListener(ON_MOUSE_UP,this._onButCenterDownRelease,this);q=new CTextButton(CANVAS_WIDTH/2+90,CANVAS_HEIGHT-180,s_oSpriteLibrary.getSprite("but_generic_small"),"LEFT",FONT_GAME,"#ffffff",24,p);q.addEventListener(ON_MOUSE_UP,this._onButRightDownRelease,this);this.show(a,b,c,f)};this.show=function(a,
b,c,d){h.text=a;""!==b?(e.changeText(b),e.setVisible(!0)):e.setVisible(!1);""!==c?(l.changeText(c),l.setVisible(!0)):l.setVisible(!1);""!==d?(q.changeText(d),q.setVisible(!0)):q.setVisible(!1)};this.hide=function(){this.unload();s_oStage.removeChild(p)};this.unload=function(){e.unload();l.unload();q.unload()};this.addEventListener=function(a,b,c){d[a]=b;g[a]=c};this._onButLeftDownRelease=function(){d[ON_MSG_BOX_LEFT_BUT]&&(d[ON_MSG_BOX_LEFT_BUT].call(g[ON_MSG_BOX_LEFT_BUT]),p.visible=!1)};this._onButCenterDownRelease=
function(){d[ON_MSG_BOX_CENTER_BUT]&&(d[ON_MSG_BOX_CENTER_BUT].call(g[ON_MSG_BOX_CENTER_BUT]),p.visible=!1)};this._onButRightDownRelease=function(){d[ON_MSG_BOX_RIGHT_BUT]&&(d[ON_MSG_BOX_RIGHT_BUT].call(g[ON_MSG_BOX_RIGHT_BUT]),p.visible=!1)};this._init(a,f,c,b)}
function CCreditsPanel(){var a,f,c,b,d,g,h,e,l;this._init=function(){l=new createjs.Container;l.alpha=0;s_oStage.addChild(l);var q=new createjs.Shape;q.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(q);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));l.addChild(a);g=new createjs.Shape;g.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=.01;g.on("click",this._onLogoButRelease);l.addChild(g);q=s_oSpriteLibrary.getSprite("but_exit_small");
c=new CGfxButton(616,180,q,l);c.addEventListener(ON_MOUSE_UP,this.unload,this);d=new createjs.Text(TEXT_CREDITS_DEVELOPED,"24px "+FONT_GAME,"#008733");d.textAlign="center";d.textBaseline="alphabetic";d.x=CANVAS_WIDTH/2;d.y=240;d.outline=2;l.addChild(d);b=new createjs.Text(TEXT_CREDITS_DEVELOPED,"24px "+FONT_GAME,"#fff");b.textAlign="center";b.textBaseline="alphabetic";b.x=CANVAS_WIDTH/2;b.y=240;l.addChild(b);q=s_oSpriteLibrary.getSprite("logo_ctl");f=createBitmap(q);f.regX=q.width/2;f.regY=q.height/
2;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;l.addChild(f);e=new createjs.Text("www.codethislab.com","18px "+FONT_GAME,"#008733");e.textAlign="center";e.textBaseline="alphabetic";e.x=CANVAS_WIDTH/2;e.y=320;e.outline=2;l.addChild(e);h=new createjs.Text("www.codethislab.com","18px "+FONT_GAME,"#fff");h.textAlign="center";h.textBaseline="alphabetic";h.x=CANVAS_WIDTH/2;h.y=320;l.addChild(h);createjs.Tween.get(l).to({alpha:1},600,createjs.Ease.cubicOut);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=
function(a,b){};this.unload=function(){g.off("click",this._onLogoButRelease);c.unload();c=null;s_oStage.removeChild(l)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()}
function CAlertSavingBox(a,f){var c,b,d,g,h;this._init=function(a){g=new createjs.Container;h.addChild(g);var d;d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=.5;d.on("click",function(){});g.addChild(d);d=s_oSpriteLibrary.getSprite("msg_box");var e=createBitmap(d);e.x=.5*CANVAS_WIDTH;e.y=.5*CANVAS_HEIGHT;e.regX=.5*d.width;e.regY=.5*d.height;g.addChild(e);c=new createjs.Text(a,"16px "+FONT_GAME,"#fff");c.x=CANVAS_WIDTH/2;c.y=240;c.textAlign="center";
c.textBaseline="middle";c.lineWidth=300;g.addChild(c);b=new CGfxButton(CANVAS_WIDTH/2+140,180,s_oSpriteLibrary.getSprite("but_exit_small"),g);b.addEventListener(ON_MOUSE_UP,this._onButOk,this)};this._onButOk=function(){d.unload()};this.unload=function(){b.unload();h.removeChild(g)};d=this;h=f;this._init(a)}
function CBee(a,f){var c,b,d,g,h;this._init=function(a){d=a;a=s_oSpriteLibrary.getSprite("bee");c=a.width/2;b=a.height;a=new createjs.SpriteSheet({framerate:15,images:[a],frames:{width:c,height:b,regX:c/2,regY:b/2},animations:{idle:[0,1]}});g=createSprite(a,"idle",c/2,b/2,c,b);h.addChild(g);d.start>d.end&&(g.scaleX*=-1);g.rotation=d.start_rot;var e=this;createjs.Tween.get(g).to({guide:{path:d.path,start:d.start,end:d.end},rotation:d.final_rot},d.time).call(function(){e.unload()})};this.unload=function(){h.removeChild(g)};
h=f;this._init(a)}
function CDaisy(a,f,c){var b,d;this._init=function(a,c){var e={framerate:15,images:[s_oSpriteLibrary.getSprite("daisy_spritesheet")],frames:{width:DAISY_WIDTH,height:DAISY_HEIGHT,regX:DAISY_WIDTH/2,regY:DAISY_HEIGHT/2},animations:{start:[0],idle:[20],anim:[0,20,"idle"]}},e=new createjs.SpriteSheet(e);b=createSprite(e,"start",DAISY_WIDTH/2,DAISY_HEIGHT/2,DAISY_WIDTH,DAISY_HEIGHT);b.stop();b.visible=!1;b.x=a;b.y=c;d.addChild(b)};this.show=function(a){setTimeout(function(){b.visible=!0;b.gotoAndPlay("anim")},
a)};this.unload=function(){d.removeChild(b)};d=c;this._init(a,f)};
